// Transcripción manual del cuadernillo. Cada enunciado y opción se escribe
// como HTML; las figuras se construyen con SVG en manual_figures.js.
const QUESTIONS = [
{lead:`El terreno de un corral para caballos tiene forma circular, cuyo centro está ubicado a 12 m al este y 18 m al norte de la entrada a una propiedad. La medida del radio de la circunferencia, que representa el borde de ese terreno, es 6 m.`, pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones Q del centro del terreno del corral, P de la entrada a esa propiedad y C de la circunferencia correspondiente al borde de ese terreno:`, fig:'1', ask:`De acuerdo con la información anterior, ¿cuál es la representación algebraica, cuyas unidades están en metros, de C?`, options:[`(x − 12)<sup>2</sup> + (y − 18)<sup>2</sup> = 36`,`(x + 12)<sup>2</sup> + (y − 18)<sup>2</sup> = 12`,`(x + 12)<sup>2</sup> + (y + 18)<sup>2</sup> = 6`]},
{lead:`En el patio de un colegio se pintó una zona de juegos, cuya superficie tiene forma circular. La medida del radio de la circunferencia que representa el borde de la superficie de esa zona es 4 m. La ubicación D, del centro de esa zona, corresponde a 10 m al norte y 5 m al este de la ubicación E de la entrada del colegio. ¿Cuál opción corresponde a la representación gráfica, cuyas unidades están en metros, de la circunferencia que representa el borde de esa zona de juegos?`,options:[`<span data-fig="2A"></span>`,`<span data-fig="2B"></span>`,`<span data-fig="2C"></span>`]},
{lead:`La siguiente representación gráfica, cuyas unidades están en kilómetros, muestra las ubicaciones S de un puerto, R de un barco y C de la circunferencia correspondiente al alcance máximo de la señal emitida por el radar de ese barco:`,fig:'3',ask:`De acuerdo con la información anterior, si una hora después la nueva ubicación del barco es 5 km al oeste de R, entonces, ¿cuál es la representación gráfica, cuyas unidades están en kilómetros, de la circunferencia correspondiente al alcance máximo de la señal emitida por el radar de ese barco en su nueva ubicación W?`,options:[`<span data-fig="3A"></span>`,`<span data-fig="3B"></span>`,`<span data-fig="3C"></span>`]},
{lead:`El tiro con arco es un deporte olímpico en el cual se utiliza un arco para lanzar flechas a un objetivo (diana), el cual tiene forma circular y la medida de su diámetro es 122 cm. La siguiente representación gráfica, cuyas unidades están en centímetros, muestra la forma que tiene una diana utilizada en un juego:`,fig:'4',ask:`De acuerdo con la información anterior, si durante el juego una persona deportista lanzó tres flechas, identificadas con R, S y T, que impactaron, respectivamente, en los puntos correspondientes a (61, 133), (61, 123) y (61, 113), entonces, ¿cuál flecha impactó en el interior de la diana?`,options:['R','S','T']},
{lead:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones P de un vehículo, R del centro de un terreno circular y Q de la entrada a ese terreno. Además, se muestra la recta n que representa una carretera, así como la circunferencia C correspondiente al borde de ese terreno:`,fig:'5',ask:`De acuerdo con la información anterior, si la medida del diámetro de la circunferencia es 20 m, entonces, ¿a qué distancia está el vehículo del centro del terreno?`,options:['26,00 m','49,03 m','52,00 m']},
{lead:`La siguiente figura representa una superficie lateral (cara) de una columna de una iglesia, la cual está formada por un hexágono regular y dos cuadrados congruentes entre sí:`,fig:'6',ask:`De acuerdo con la información anterior, si se requiere pintar la totalidad de esa cara de la columna, entonces, ¿cuántos metros cuadrados se requieren pintar?`,options:[`<math data-latex="56\\sqrt{3}"><mn>56</mn><mspace width="0.16em"/><msqrt><mn>3</mn></msqrt></math>`,`<math data-latex="16+24\\sqrt{3}"><mn>16</mn><mo>+</mo><mn>24</mn><mspace width="0.16em"/><msqrt><mn>3</mn></msqrt></math>`,`<math data-latex="32+24\\sqrt{3}"><mn>32</mn><mo>+</mo><mn>24</mn><mspace width="0.16em"/><msqrt><mn>3</mn></msqrt></math>`]},
{lead:`Una persona tiene dos espejos del mismo tamaño y cada uno de ellos tiene forma de hexágono regular. Esa persona, algunas veces coloca los espejos separados y otras veces juntos donde comparten uno de los lados, tal y como se muestra a continuación:`,fig:'7',ask:`De acuerdo con la información anterior, el perímetro de la figura formada por los espejos juntos es`,options:['igual que la suma de los perímetros de los espejos separados.','mayor que la suma de los perímetros de los espejos separados.','menor que la suma de los perímetros de los espejos separados.']},
{lead:`La siguiente representación gráfica muestra el polígono ABCDE que representa la superficie de un terreno:`,fig:'8',ask:`De acuerdo con la información anterior, si se requiere colocar una malla en el borde de la totalidad de la superficie del terreno, entonces, ¿cuántos metros de malla, como mínimo, se requieren colocar?`,options:['29','36','62']},
{lead:`En una empresa se requiere construir una tapa de un motor industrial a partir de una lámina metálica.`,pre:`La siguiente representación gráfica, cuyas unidades están en decímetros, muestra la figura ABCDEF correspondiente a la forma que tendrá la superficie de la tapa:`,fig:'9',ask:`De acuerdo con la información anterior, la cantidad mínima de decímetros cuadrados de la lámina metálica que se requiere para construir la totalidad de la superficie de esa tapa es mayor que`,options:['24 y menor que 28.','29 y menor que 33.','34 y menor que 38.']},
{lead:`Considere la siguiente información:`,pre:`El piso de un quiosco, ubicado en el parque de una ciudad, tiene forma de octágono regular, cuya medida de uno de sus lados es 3 m. Además, se sabe que la medida de una apotema, del octágono que representa ese piso, es aproximadamente 3,62 m.`,ask:`De acuerdo con la información anterior, si se requiere pintar la totalidad del piso de ese quiosco, entonces la cantidad aproximada de metros cuadrados que se requieren pintar corresponde a`,options:['24,00','43,44','86,88']},
{lead:`En un taller se fabricaron dos basureros (M y N) a partir de dos recipientes metálicos (estañones). Cada estañón tiene forma de cilindro circular recto. Para fabricar los basureros se procedió de la siguiente manera:`,pre:`<ul><li>El basurero M se fabricó a partir de un estañón al que se le realizó un corte plano que pasa por el centro de cada una de sus bases.</li><li>El basurero N se fabricó a partir de otro estañón al que se le realizó un corte plano oblicuo a sus bases y sin intersecarlas.</li></ul>`,ask:`De acuerdo con la información anterior, las secciones planas obtenidas en los basureros M y N, producto de los cortes realizados, corresponden respectivamente a`,options:['un rectángulo y una elipse.','una elipse y una circunferencia.','un rectángulo y una circunferencia.']},
{lead:`Un recipiente aromatizante se fabricó a partir de una esfera de cerámica a la cual se le realizaron dos cortes para obtener dos secciones planas, paralelas y del mismo tamaño, que representan la base y la abertura del recipiente. La medida del radio de esa esfera es 5 cm. Además, cuando se realizaron los cortes, la distancia entre los centros de esas secciones fue de 6 cm. La siguiente figura muestra la forma del recipiente:`,fig:'12',ask:`De acuerdo con la información anterior, ¿cuál es aproximadamente el área, en centímetros cuadrados, de la base del recipiente?`,options:['25,12','50,24','78,50']},
{lead:`¿Cuál fue la temperatura, en grados Celsius, que tuvo ese líquido a los 24 min desde el inicio del experimento?`,options:['0','12','48']},
{lead:`Durante todo ese tiempo, ¿cuál fue la mayor temperatura, en grados Celsius, que tuvo ese líquido?`,options:['36','48','60']},
{lead:`Durante todo ese tiempo, ¿en cuántas ocasiones la temperatura que tuvo ese líquido fue igual a 24 °C?`,options:['en tres ocasiones','en dos ocasiones','en una ocasión']},
{lead:`Considere la siguiente información:`,pre:`La función d, que determina el ingreso diario “d(u)” en colones, obtenido en una panadería, está dada por d(u) = 750u, donde “u” representa la cantidad diaria de unidades de pan vendidas en esa panadería, con 60 ≤ u ≤ 200.<br><br>Además, la función u, que determina la cantidad diaria “u(t)” de unidades de pan vendidas por la panadería, está dada por u(t) = 20t + 40, donde “t” representa el tiempo en horas cumplidas, desde que esa panadería comienza a vender cada día, con 1 ≤ t ≤ 8.`,ask:`De acuerdo con la información anterior, si para un estudio financiero el personal de la panadería requiere conocer el criterio de la función (d ∘ u), entonces, ¿cuál opción corresponde a ese criterio?`,options:['(d ∘ u)(t) = 30 000t + 15 000','(d ∘ u)(t) = 15 000t + 30 000','(d ∘ u)(t) = 15 000t + 40']},
{lead:`La siguiente representación gráfica corresponde a la función exponencial m que determina la cantidad de datos “y” en megabytes, procesados por una red informática, en función del tiempo “x” en minutos, desde que esa red comenzó a procesar datos, con 0 &lt; x ≤ 2:`,fig:'17',ask:`De acuerdo con la información anterior, ¿cuál opción podría corresponder a la representación gráfica de m<sup>−1</sup>?`,options:[`<span data-fig="17A"></span>`,`<span data-fig="17B"></span>`,`<span data-fig="17C"></span>`]},
{lead:`Considere la siguiente información:`,pre:`En un laboratorio se utiliza la función r para convertir la concentración “c” de una sustancia a un valor interno llamado índice de reactividad “r(c)”, el cual indica cuán rápida y fácilmente una sustancia reacciona con otra. Esta función está dada por r(c) = <math data-latex="\\frac{c-2}{3}"><mfrac><mrow><mi>c</mi><mo>−</mo><mn>2</mn></mrow><mn>3</mn></mfrac></math>, con 2 ≤ c ≤ 8.<br><br>Además, debido a un error se perdieron algunos datos de concentración; sin embargo, se conservaron los valores del índice de reactividad. Para reconstruir las concentraciones originales, se necesita utilizar la función c, la cual corresponde a la función inversa de r.`,ask:`De acuerdo con la información anterior, ¿cuál es el criterio de c?`,options:['c(r) = 3r + 2','c(r) = 3r − 2','c(r) = 2r − 3']},
{lead:`Considere la siguiente información:`,pre:`La función g, la cual determina la altura “g(t)” en centímetros de una planta, está dada por g(t) = 4(t<sup>2</sup> + 10), donde “t” representa el tiempo en meses desde el inicio de una observación, con 0 ≤ t ≤ 5.`,ask:`De acuerdo con la información anterior, si para un análisis biológico se requiere determinar el criterio de la función t, la cual corresponde a la función inversa de g, entonces, ¿cuál opción corresponde a ese criterio?`,options:[`t(g) = <math data-latex="\\sqrt{\\frac{g-10}{4}}"><msqrt><mfrac><mrow><mi>g</mi><mo>−</mo><mn>10</mn></mrow><mn>4</mn></mfrac></msqrt></math>`,`t(g) = <math data-latex="\\sqrt{\\frac{g-40}{4}}"><msqrt><mfrac><mrow><mi>g</mi><mo>−</mo><mn>40</mn></mrow><mn>4</mn></mfrac></msqrt></math>`,`t(g) = <math data-latex="\\sqrt{-4g^2-40}"><msqrt><mrow><mo>−</mo><mn>4</mn><msup><mi>g</mi><mn>2</mn></msup><mo>−</mo><mn>40</mn></mrow></msqrt></math>`]},
{lead:`La siguiente representación gráfica corresponde a la función n, que determina la altura “n(x)” en decímetros que tenía el nivel del agua contenida en el interior de un tanque, en función del tiempo “x” en horas, desde el inicio de una observación, con 0 ≤ x ≤ 8:`,fig:'20',pre:`Además, en un estudio científico se requiere registrar el tiempo en función de la altura del nivel del agua contenida en ese tanque. Para ello, se debe determinar un posible intervalo del dominio de n tal que esta función tenga inversa.`,ask:`De acuerdo con la información anterior, ¿cuál opción corresponde a ese posible intervalo?`,options:['[1, 3]','[2, 6]','[5, 7]']},
{lead:`Considere la siguiente información:`,pre:`En ciertas condiciones especiales se establece que la función v, la cual determina el nivel de intensidad del sonido “v(m)” en decibeles, percibido por una persona debido al paso de un avión, está dada por v(m) = 75 − <math data-latex="3\\sqrt{m-1}"><mn>3</mn><msqrt><mrow><mi>m</mi><mo>−</mo><mn>1</mn></mrow></msqrt></math>, donde “m” representa la distancia en hectómetros a la que se ubica la persona con respecto a ese avión, con 5 ≤ m ≤ 26.`,ask:`De acuerdo con la información anterior, si el nivel de intensidad del sonido percibido por Luis Diego debido al paso del avión es igual a 63 decibeles, entonces, ¿cuál es la distancia en hectómetros a la que se ubica él con respecto al avión?`,options:['2','17','51']},
{lead:`La siguiente representación gráfica corresponde a la función r, la cual determina la rapidez “r(x)” en metros por segundo que tenía un vehículo, en función del tiempo “x” en segundos desde el inicio de un experimento, con 4 ≤ x ≤ 25:`,fig:'22',ask:`De acuerdo con la información anterior, si r involucra a la función raíz cuadrada, entonces, ¿cuál opción corresponde al criterio de r?`,options:[`r(x) = <math class="q22-root" data-latex="4\\sqrt{x}"><mn>4</mn><msqrt><mi>x</mi></msqrt></math>`,`r(x) = <math class="q22-root" data-latex="\\sqrt{x+4}"><msqrt><mrow><mi>x</mi><mo>+</mo><mn>4</mn></mrow></msqrt></math>`,`r(x) = <math class="q22-root" data-latex="\\sqrt{x}"><msqrt><mi>x</mi></msqrt></math> + 4`]},
{lead:`La siguiente representación gráfica corresponde a la función cuadrática p, la cual determina el precio “p(x)” en dólares que tuvo cada una de las acciones de una empresa, en función del tiempo “x” en años transcurridos desde la fundación de esa empresa, con 0 &lt; x ≤ 8:`,fig:'23',ask:`De acuerdo con la información anterior, ¿cuántos años han transcurrido desde la fundación de esa empresa para que el precio de cada una de sus acciones fuera el mayor posible?`,options:['4','8','34']},
{lead:`En una planta embotelladora la cantidad total de botellas que fueron llenadas por día está linealmente relacionada con el número de máquinas que había en funcionamiento:`,pre:`<ul><li>Si el lunes de una semana había cuatro máquinas en funcionamiento, entonces fueron llenadas 1100 botellas en total.</li><li>Si el martes de esa semana la cantidad de máquinas que había en funcionamiento aumentó en seis con respecto al día anterior, entonces fueron llenadas 2300 botellas en total.</li></ul>`,ask:`De acuerdo con la información anterior, ¿cuál es la ecuación de la recta que representa la cantidad total de botellas “y” que fueron llenadas por día en esa planta, en función del número de máquinas “x” que había en funcionamiento?`,options:['y = 600x − 1300','y = 200x + 300','y = 500x']},
{lead:`Considere la siguiente información:`,pre:`La función c, que determina la cantidad diaria “c(t)” de clientes atendidos en un restaurante durante un festival de comida, está dada por c(t) = 5 · 2<sup>t</sup>, donde “t” representa el tiempo en días transcurridos desde el inicio del festival, con 1 ≤ t ≤ 6.`,ask:`De acuerdo con la información anterior, si el restaurante atendió 160 clientes en un día, entonces, ¿cuántos días han transcurrido desde el inicio del festival?`,options:['5','16','64']},
{lead:`Considere la siguiente información:`,pre:`Un recipiente contiene 2 L de agua y, a partir de cierto instante, se le realizó un orificio en su parte inferior.<br><br>La función c, la cual determina la cantidad de agua “c(x)” en litros que pierde ese recipiente, está dada por c(x) = log(x), donde “x” representa el tiempo en minutos transcurridos desde que se le realizó ese orificio, con 3 ≤ x ≤ 100.`,ask:`De acuerdo con la información anterior, ¿cuántos minutos han transcurrido desde que se le realizó el orificio para que el recipiente perdiera 1 L de agua?`,options:['3','7','10']},
{lead:`Considere la siguiente información:`,pre:`En ciertas condiciones la cantidad de energía consumida por un vehículo eléctrico al desplazarse es de 0,18 kilovatios hora por cada kilómetro recorrido. Además, se debe pagar ₡90 por cada kilovatio hora debido a ese consumo de energía.`,ask:`De acuerdo con la información anterior, ¿cuál opción muestra la ecuación de la recta correspondiente al monto total “y” en colones que se debe pagar por la cantidad de energía consumida por el vehículo al desplazarse, en función de la cantidad “x” de kilómetros recorridos?`,options:['y = 0,18x + 90','y = 16,20x','y = 90,18x']},
{lead:`La siguiente representación gráfica corresponde a la función cuadrática t, la cual determina la temperatura “t(x)” en grados Celsius que tuvo un horno, en función del tiempo “x” en minutos desde el inicio de un experimento científico, con 0 ≤ x ≤ 20:`,fig:'28',ask:`De acuerdo con la información anterior, durante todo ese tiempo, la temperatura en grados Celsius que tuvo ese horno fue mayor o igual que`,options:['0 y menor o igual que 20.','10 y menor o igual que 70.','70 y menor o igual que 210.']},
{lead:`Considere la siguiente información:`,pre:`La función b, que determina la cantidad de bacterias “b(x)” en miles que permanecieron vivas en una superficie luego de aplicar un desinfectante, está dada por b(x) = 128 · <math data-latex="\\left(\\frac{1}{2}\\right)^x"><msup><mrow><mo>(</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>)</mo></mrow><mi>x</mi></msup></math>, donde “x” representa el tiempo en minutos transcurridos desde la aplicación de ese desinfectante, con 0 &lt; x ≤ 9.`,ask:`De acuerdo con la información anterior, ¿cuántos minutos han transcurrido luego de aplicar el desinfectante para que permaneciera viva en la superficie una cantidad de bacterias, en miles, igual a cuatro?`,options:['5','8','9']},
{lead:`Considere la siguiente información:`,pre:`La función m, que determina el nivel de intensidad del sonido “m(x)” en decibeles registrado en un auditorio, está dada por m(x) = 15 · log<sub>2</sub>(x), donde “x” representa el número de altavoces encendidos en ese auditorio, con 16 ≤ x ≤ 64.`,ask:`De acuerdo con la información anterior, ¿cuál es el nivel de intensidad del sonido, en decibeles, registrado en el auditorio si hay 32 altavoces encendidos?`,options:['4','75','240']},
{lead:`Considere la siguiente información:`,pre:`Una imprenta produce únicamente afiches y calendarios. Para esa producción se toma en cuenta lo siguiente:<ul><li>Cada afiche requiere dos hojas de papel y dos tubos de tinta.</li><li>Cada calendario requiere tres hojas de papel y un tubo de tinta.</li></ul>`,ask:`De acuerdo con la información anterior, si en una semana para la producción de afiches y calendarios en la imprenta se requirieron 216 hojas de papel y 132 tubos de tinta, entonces, ¿cuántos afiches en total se produjeron en la semana?`,options:['12','45','129']},
{lead:`Luis, Ricardo y Alejandro fueron juntos de compras a una librería:`,pre:`<ul><li>Luis compró dos cuadernos y cuatro lapiceros, por los cuales pagó ₡11 378.</li><li>Ricardo compró tres cuadernos y dos lapiceros, por los cuales pagó ₡11 939.</li><li>Alejandro compró únicamente tres lapiceros.</li></ul>Además, se sabe que en esa librería cada cuaderno tenía el mismo precio y cada lapicero tenía el mismo precio.`,ask:`De acuerdo con la información anterior, ¿cuál fue el monto total que pagó Alejandro por los lapiceros que compró?`,options:['₡3846','₡4898','₡5970']},
{lead:`La siguiente tabla muestra la función g, la cual determina la distancia “g(t)” en kilómetros recorrida por un vehículo, en función del tiempo “t” en horas desde el inicio de ese recorrido, con 0 ≤ t ≤ 8:`,fig:'33',ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar a g?`,options:['Función lineal','Función logarítmica','Función exponencial']},
{lead:`La siguiente representación gráfica corresponde a la función b, la cual determina el volumen de un gas “b(x)” en metros cúbicos contenido en un tanque, en función del tiempo “x” en horas desde el inicio de un experimento científico, con 0 ≤ x ≤ 3:`,fig:'34',ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función involucrada en el modelo matemático que se adapta mejor para representar a b?`,options:['Función cuadrática','Función logarítmica','Función exponencial']},
{lead:`La siguiente tabla muestra la función k, la cual determina la cantidad “k(x)” de tomates producidos por una planta durante una temporada, en función de la cantidad “x” en gramos de fertilizante orgánico aplicado a esa planta antes de iniciar cada temporada, con 0 ≤ x ≤ 40:`,fig:'35',ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar a k?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`Con certeza, ¿cuál opción corresponde al gasto en transporte de al menos dos estudiantes durante el último cuatrimestre?`,options:['₡10 000','₡15 000','₡25 000']},
{lead:`Ninguno de los estudiantes gastó en transporte, durante el último cuatrimestre, una cantidad de dinero`,options:['mayor que ₡40 000.','menor que ₡10 000.','igual que ₡15 000.']},
{lead:`Al menos el 50 % del total de esos estudiantes gastó en transporte, durante el último cuatrimestre, una cantidad de dinero mayor o igual que`,options:['₡25 000 y menor o igual que ₡40 000.','₡10 000 y menor o igual que ₡25 000.','₡5 000 y menor o igual que ₡10 000.']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondientes a la cantidad diaria de agua en litros consumida en una casa al finalizar un semestre. Además, se muestran en litros la moda (90) y la mediana (110) de esos datos:`,fig:'39',ask:`De acuerdo con la información anterior, si la moda de esos datos es única, entonces el promedio de la cantidad de agua consumida en esa casa`,options:['es menor que 90 L.','es mayor que 110 L.','está entre 90 L y 110 L.']},
{lead:`La siguiente tabla muestra la distribución de frecuencias correspondientes a la cantidad de páginas que cada participante de un programa de lectura leyó durante una semana:`,fig:'40',ask:`De acuerdo con la información anterior, ¿cuál es el promedio de la cantidad de páginas leídas por esos participantes durante la semana?`,options:['7,2','14,4','15,4']}
];
const SHARED={
  13:{lead:`Para responder los ítems 13, 14 y 15, considere la siguiente información:`,pre:`La siguiente representación gráfica corresponde a la función t, que determina la temperatura “t(x)” en grados Celsius que tuvo un líquido en un laboratorio, en función del tiempo “x” en minutos desde el inicio de un experimento científico, con 0 ≤ x ≤ 60:`,fig:'context13'},
  36:{lead:`Para responder los ítems 36, 37 y 38, considere la siguiente información:`,pre:`La siguiente tabla muestra algunas medidas de posición relacionadas con la cantidad de dinero, en colones, que gastaron en transporte 31 estudiantes universitarios durante el último cuatrimestre:`,fig:'context36'}
};
if(QUESTIONS.length!==40||QUESTIONS.some(q=>q.options.length!==3))throw Error('Transcripción incompleta');
