// Explicaciones para la revisión que aparece después de finalizar la prueba.
const SOLUTIONS = [
  `El centro es (12, 18) y el radio es 6. Por eso, (x − 12)<sup>2</sup> + (y − 18)<sup>2</sup> = 6<sup>2</sup> = 36.`,
  `El centro D está en (5, 10) respecto a E y el radio es 4. La opción C muestra el centro y el punto (9, 10) sobre la circunferencia.`,
  `El centro original es (20, 5). Al moverse 5 km al oeste, W queda en (15, 5); el radio permanece igual.`,
  `La diana tiene centro (61, 61) y radio 61. R y S distan 72 y 62 cm del centro; T dista 52 cm. Solo T está en el interior.`,
  `P está en (48, 30) y R en (24, 20). La distancia es <math data-latex="\\sqrt{(48-24)^2+(30-20)^2}"><msqrt><mrow><msup><mrow><mo>(</mo><mn>48</mn><mo>−</mo><mn>24</mn><mo>)</mo></mrow><mn>2</mn></msup><mo>+</mo><msup><mrow><mo>(</mo><mn>30</mn><mo>−</mo><mn>20</mn><mo>)</mo></mrow><mn>2</mn></msup></mrow></msqrt></math> = <math data-latex="\\sqrt{676}"><msqrt><mn>676</mn></msqrt></math> = 26 m.`,
  `El hexágono regular de lado 4 m tiene área <math data-latex="24\\sqrt{3}"><mn>24</mn><mspace width="0.16em"/><msqrt><mn>3</mn></msqrt></math> m<sup>2</sup>. Los dos cuadrados aportan 2 · 4<sup>2</sup> = 32 m<sup>2</sup>. Total: 32 + <math data-latex="24\\sqrt{3}"><mn>24</mn><mspace width="0.16em"/><msqrt><mn>3</mn></msqrt></math> m<sup>2</sup>.`,
  `Al unir los espejos, el lado compartido queda en el interior y deja de contar dos veces en el perímetro exterior. Por eso el perímetro es menor.`,
  `Los lados miden DE = 5, EA = 4, AB = 4, BC = 10 y CD = 13. El perímetro es 5 + 4 + 4 + 10 + 13 = 36 m.`,
  `Al descomponer la figura en regiones rectangulares y curvas, las áreas de los dos cuartos de círculo de radio 2 se compensan. El área total es 36 dm<sup>2</sup>, mayor que 34 y menor que 38.`,
  `El perímetro del octágono es 8 · 3 = 24 m. Su área es perímetro · apotema ÷ 2 = 24 · 3,62 ÷ 2 = 43,44 m<sup>2</sup>.`,
  `Un plano que pasa por los centros de ambas bases del cilindro forma una sección rectangular. Un corte oblicuo a las bases, sin tocarlas, forma una elipse.`,
  `Los cortes iguales están a 3 cm del centro de la esfera, uno a cada lado. El radio de la base es <math data-latex="\\sqrt{5^2-3^2}"><msqrt><mrow><msup><mn>5</mn><mn>2</mn></msup><mo>−</mo><msup><mn>3</mn><mn>2</mn></msup></mrow></msqrt></math> = 4 cm. Área = π · 4<sup>2</sup> ≈ 50,24 cm<sup>2</sup>.`,
  `En la gráfica, el punto correspondiente a x = 24 minutos está sobre el eje horizontal. La temperatura fue 0 °C.`,
  `El punto más alto de la gráfica corresponde a 48 °C, a los 36 minutos.`,
  `La gráfica alcanza 24 °C dos veces: al subir entre los 24 y 36 minutos y en el punto de los 48 minutos.`,
  `Se sustituye u(t) en d(u): (d ∘ u)(t) = 750(20t + 40) = 15 000t + 30 000.`,
  `Al invertir la función se intercambian las coordenadas: (0, 1) abierto pasa a (1, 0) abierto; (1, 2) pasa a (2, 1), y (2, 4) a (4, 2). Esa es la opción C.`,
  `De r = <math data-latex="\\frac{c-2}{3}"><mfrac><mrow><mi>c</mi><mo>−</mo><mn>2</mn></mrow><mn>3</mn></mfrac></math> se obtiene 3r = c − 2. Al despejar, c(r) = 3r + 2.`,
  `g = 4(t<sup>2</sup> + 10) implica g − 40 = 4t<sup>2</sup>. Como t ≥ 0, la inversa es t(g) = <math data-latex="\\sqrt{\\frac{g-40}{4}}"><msqrt><mfrac><mrow><mi>g</mi><mo>−</mo><mn>40</mn></mrow><mn>4</mn></mfrac></msqrt></math>.`,
  `Una función tiene inversa en un intervalo donde no repite alturas. Entre x = 5 y x = 7 la gráfica es estrictamente decreciente.`,
  `63 = 75 − <math data-latex="3\\sqrt{m-1}"><mn>3</mn><msqrt><mrow><mi>m</mi><mo>−</mo><mn>1</mn></mrow></msqrt></math> implica <math data-latex="\\sqrt{m-1}"><msqrt><mrow><mi>m</mi><mo>−</mo><mn>1</mn></mrow></msqrt></math> = 4. Entonces m − 1 = 16 y m = 17 hm.`,
  `La gráfica pasa por (4, 8), (9, 12), (16, 16) y (25, 20). En cada punto se cumple r(x) = <math data-latex="4\\sqrt{x}"><mn>4</mn><msqrt><mi>x</mi></msqrt></math>.`,
  `El precio máximo se alcanza en el vértice de la parábola, cuya coordenada horizontal es x = 4 años.`,
  `Los puntos son (4, 1100) y (10, 2300). La pendiente es <math data-latex="\\frac{2300-1100}{10-4}"><mfrac><mrow><mn>2300</mn><mo>−</mo><mn>1100</mn></mrow><mrow><mn>10</mn><mo>−</mo><mn>4</mn></mrow></mfrac></math> = 200; al sustituir, el intercepto es 300. Así, y = 200x + 300.`,
  `5 · 2<sup>t</sup> = 160 implica 2<sup>t</sup> = 32 = 2<sup>5</sup>. Han transcurrido 5 días.`,
  `Si el recipiente perdió 1 L, entonces log(x) = 1. Como el logaritmo es decimal, x = 10<sup>1</sup> = 10 minutos.`,
  `Cada kilómetro consume 0,18 kWh y cada kWh cuesta ₡90. El costo por kilómetro es 0,18 · 90 = ₡16,20; por eso y = 16,20x.`,
  `La menor temperatura de la parábola es 70 °C en x = 10, y la mayor en el intervalo es 210 °C. Por tanto, 70 ≤ t(x) ≤ 210.`,
  `128<math data-latex="\\left(\\frac{1}{2}\\right)^x"><msup><mrow><mo>(</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>)</mo></mrow><mi>x</mi></msup></math> = 4 implica <math data-latex="\\left(\\frac{1}{2}\\right)^x"><msup><mrow><mo>(</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>)</mo></mrow><mi>x</mi></msup></math> = <math data-latex="\\frac{1}{32}"><mfrac><mn>1</mn><mn>32</mn></mfrac></math> = <math data-latex="\\left(\\frac{1}{2}\\right)^5"><msup><mrow><mo>(</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>)</mo></mrow><mn>5</mn></msup></math>. Por eso x = 5 minutos.`,
  `m(32) = 15 · log<sub>2</sub>(32) = 15 · 5 = 75 decibeles.`,
  `Si a es el número de afiches y c el de calendarios: 2a + 3c = 216 y 2a + c = 132. Al restar, c = 42 y luego a = 45.`,
  `Sea c el precio de un cuaderno y p el de un lapicero. De 2c + 4p = 11 378 y 3c + 2p = 11 939 se obtiene p = ₡1282. Alejandro pagó 3p = ₡3846.`,
  `La distancia aumenta 74 km por cada hora: 0, 74, 148, 296 y 592 corresponden a g(t) = 74t. Es una función lineal.`,
  `El volumen se reduce a la mitad en cada hora: 64, 32, 16 y 8 m<sup>3</sup>. Ese cambio por razón constante es exponencial.`,
  `Para aumentos iguales de 10 g, las diferencias son 9, 18, 27 y 36; las segundas diferencias son constantes e iguales a 9. El modelo es cuadrático.`,
  `La moda de la tabla es ₡10 000, es decir, ese es el gasto que se repite con mayor frecuencia. Por eso al menos dos estudiantes gastaron esa cantidad.`,
  `El máximo registrado es ₡40 000. Por lo tanto, ningún estudiante gastó una cantidad mayor que ₡40 000.`,
  `El primer cuartil es ₡10 000 y el tercero ₡25 000. Entre ambos se encuentra al menos la mitad de los datos.`,
  `La distribución tiene una cola más larga hacia los valores altos. Esos valores desplazan el promedio por encima de la mediana de 110 L.`,
  `Se usan las marcas de clase 5, 15 y 25: <math data-latex="\\frac{6\\cdot5+12\\cdot15+7\\cdot25}{25}"><mfrac><mrow><mn>6</mn><mo>·</mo><mn>5</mn><mo>+</mo><mn>12</mn><mo>·</mo><mn>15</mn><mo>+</mo><mn>7</mn><mo>·</mo><mn>25</mn></mrow><mn>25</mn></mfrac></math> = <math data-latex="\\frac{385}{25}"><mfrac><mn>385</mn><mn>25</mn></mfrac></math> = 15,4 páginas.`
];
if(SOLUTIONS.length!==40)throw Error('Faltan soluciones de la prueba');
