const ANSWER_KEY=["D","D","D","C","A","C","C","A","D","D","A","B","B","C","C","B","B","D","B","A","C","C","B","B","C","C","C","D","C","B","A","A","D","D","A","D","B","D","D","B","B","C","D","A","A","C","B","A","B","C","B","B","A","A","C","A","C","B","C","C"];
const SOLUTIONS=[
  "La asimetría negativa ubica la mediana entre el promedio 40 y la moda 48.",
  "120/160 = 75 %. El tercer cuartil es 250 L: al menos el 75 % consumió 250 L o menos.",
  "450 L supera el máximo registrado de 400 L.",
  "Marcas 10, 30, 50, 70. Promedio (10·12 + 30·8 + 50·8 + 70·6)/34 ≈ 34,7 km.",
  "Múltiplo de 5 o mayor que 9 es A ∪ B.",
  "A ∩ Cᶜ significa múltiplo de cinco e impar.",
  "Usan transporte público 11 + 6 = 17; 17/25 = 0,68.",
  "Hombre de A: 20 entre 81 oferentes; 20/81 ≈ 0,25.",
  "I es falsa: el mínimo de M es 15, menor que 17 de N. II es verdadera: el tercer cuartil es 22 en ambas ciudades. Solo II.",
  "Primer cuartil de M = 17 y de N = 19. Al menos 75 % de ambas ciudades registra 17 °C o más.",
  "CV de R = 15/51·100 ≈ 29,4 %; S = 12/45·100 ≈ 26,7 %. R tiene mayor variabilidad relativa que S.",
  "Ana z = 1; Laura (85 − 81)/9 ≈ 0,44; Guillermo (70 − 93)/10 = −2,3. Ana supera la posición relativa de Laura.",
  "Entre los días 40 y 50 el volumen permanece en 30 millones de metros cúbicos; v(45)=30.",
  "La horizontal v=40 corta dos segmentos: el creciente entre 0 y 10 y el decreciente entre 20 y 40. Son dos ocasiones.",
  "m(3) = 5 + 3·3³ = 5 + 81 = 86 decenas.",
  "9 = 3 + 1,5x; 1,5x = 6, x = 4 días.",
  "d(u(t)) = 750(20t + 40) = 15 000t + 30 000.",
  "La gráfica crece estrictamente en [4,6]; cada cantidad de miel tiene un único tiempo en ese intervalo. La función restringida es inyectiva y tiene inversa.",
  "La inversa intercambia (1, 2) y (5, 8) por (2, 1) y (8, 5), respectivamente: gráfica B.",
  "m=30d+5; al despejar d se obtiene d(m)=(m−5)/30.",
  "k = 4ⁿ; al despejar n, n(k) = log₄(k).",
  "r(27) = 10 + 5√(27 − 2) = 35 g.",
  "t(22) = 20 + 2√(22 + 3) = 30 °C.",
  "La curva comienza en (4,2). La raíz cuadrada se traslada 4 unidades a la derecha y 2 hacia arriba: m(x)=√(x−4)+2.",
  "Pendiente (5750 − 7750)/(11 − 3) = −250; intercepto 8500. y = −250x + 8500.",
  "La recta pasa por (0, 120) y (6, 360). Pendiente 40; m(x) = 40x + 120.",
  "El máximo de −2t² + 24t + 80 ocurre en t = −24/(−4) = 6 horas.",
  "La mayor altura es la ordenada del vértice: 12 m.",
  "100·(4/5)² = 100·0,64 = 64. Transcurrieron 2 horas.",
  "100 = −20 log(d) + 120; log(d) = 1, d = 10 m.",
  "r + c = 26 y 4r + 3c = 90; r = 12 bloques rectangulares.",
  "4c + 3g = 38 945 y 3c + 5g = 45 475. Eliminando g: 11c = 58 300, c = ₡5300.",
  "m y p se cortan en un único punto, así que I es falsa. n y m son paralelas distintas: II es verdadera. Solo II.",
  "Cada valor se multiplica por 1,5: modelo exponencial.",
  "La distancia aumenta 4,5 km por hora: modelo lineal.",
  "Cada cantidad de bacterias se duplica: modelo exponencial.",
  "La gráfica pasa por (2, 400), (4, 800), (8, 1200): el tiempo se duplica al sumar 400 m. Modelo logarítmico.",
  "Centro (6, 5), radio 4. (x − 6)² + (y − 5)² = 16.",
  "Centro (5, 10), radio 4: gráfica D. El borde alcanza y = 14.",
  "Centro (60,−90), radio 5. La ecuación es (x−60)²+(y+90)²=25.",
  "El radio es la raíz cuadrada de 196: 14.",
  "El centro (2, 1) se traslada a (−2, −1), radio 1. (x + 2)² + (y + 1)² = 1.",
  "El centro (−4, −3) se traslada sumando (5, 6) a (1, 3), radio 2. (x − 1)² + (y − 3)² = 4.",
  "El centro (1,0) se traslada a (−1,5). El radio sigue siendo 9: (x+1)²+(y−5)²=81.",
  "Centro (1, 1), radio 2,5. M(1, 4) está a 3 unidades del centro, por lo que queda fuera.",
  "El radio es perpendicular a la tangente. Distancia banca-centro √(6² + 8²) = 10 m.",
  "Marcela (7, −2) está a 3 m del centro (4, −2), dentro del radio 8. Los otros puntos están a más de 8 m.",
  "La recta BM es secante y la recta BD es exterior a la circunferencia: opción A.",
  "Al unir el hexágono y el cuadrado, el lado común deja de formar parte del borde. Quedan 8 lados de 3 m: perímetro 24 m.",
  "La figura se aproxima a un rectángulo de 6 × 6 = 36 dm². Las dos regiones curvas, de aspecto semejante, compensan aproximadamente lo agregado y lo retirado. La estimación queda entre 34 y 38 dm².",
  "La descomposición del cuadrilátero A(2, 4), B(10, 9), C(10, 4), D(6, 2) da 20 + 8 = 28 m².",
  "El área delimitada por Q(1, 1), M(4, 5), N(8, 2), P(8, 1), con el borde curvo, es aproximadamente 15 m², entre 14 y 17.",
  "Un corte oblicuo a las bases de un cilindro circular recto, sin intersecarlas, produce una elipse.",
  "I: un plano paralelo a una generatriz produce una parábola. II: un plano perpendicular a la base, sin pasar por el vértice, produce una hipérbola. Ambas son verdaderas.",
  "Cada sección está a 6 cm del centro de la esfera. Radio √(10² − 6²) = 8 cm; diámetro 16 cm.",
  "El papalote es simétrico respecto a la recta horizontal y = −4.",
  "I es verdadera: A(0,−4) se refleja en x=4 y pasa a D(8,−4). II es falsa: la reflexión en y=−4 no lleva el segmento CD a AC. Solo I.",
  "N=(6,0) está sobre el eje x, por lo que su reflexión respecto a ese eje es el mismo punto (6,0).",
  "P=(2,0). Al trasladarlo por (−3,+1), su imagen es (−1,1).",
  "D=(6,12). La reflexión en el eje x conserva x y cambia el signo de y: (6,−12)."
];