// Transcripción manual de 2025-N06. Se mantiene el orden del cuadernillo.
const m=body=>`<math xmlns="http://www.w3.org/1998/Math/MathML" displaystyle="true">${body}</math>`;
const root=body=>`<msqrt><mrow>${body}</mrow></msqrt>`;
const frac=(a,b)=>`<mfrac><mrow>${a}</mrow><mrow>${b}</mrow></mfrac>`;
const num=n=>`<mn>${n}</mn>`,mi=x=>`<mi>${x}</mi>`,mo=x=>`<mo>${x}</mo>`;
const tableHTML=(rows,open=false)=>`<div class="table-wrap"><table class="exam-table${open?' open-table':''}">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'}>${c}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table></div>`;
const QUESTIONS=[
{lead:`Un dispositivo mecánico se coloca en el jardín de una casa y lanza un chorro continuo de agua, cuyo alcance máximo es 3 m alrededor de este dispositivo.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones M de esa casa, A del dispositivo y C de la circunferencia correspondiente al alcance máximo del chorro de agua lanzado por ese dispositivo:`,fig:'1',ask:`De acuerdo con la información anterior, ¿cuál es la representación algebraica de C?`,options:['(x − 13)<sup>2</sup> + (y − 12)<sup>2</sup> = 3','(x − 12)<sup>2</sup> + (y − 10)<sup>2</sup> = 6','(x − 10)<sup>2</sup> + (y − 12)<sup>2</sup> = 9']},
{lead:`En un aeropuerto hay un radar que emite una señal capaz de detectar aviones que se encuentran a una distancia menor o igual que 2 km a su alrededor. La ubicación R de ese radar es 6 km al este y 4 km al norte de la ubicación T de la torre de control de ese aeropuerto, la cual se considera como origen. ¿Cuál es la representación gráfica, cuyas unidades están en kilómetros, correspondiente al alcance máximo de la señal que emite ese radar?`,options:['<span data-fig="2A"></span>','<span data-fig="2B"></span>','<span data-fig="2C"></span>']},
{lead:`Un sensor de movimiento se ubica a 12 m al norte y 18 m al este de la entrada de una propiedad. Además, el alcance máximo de la señal inalámbrica, emitida por ese sensor, es 6 m a su alrededor.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones F del sensor de movimiento, G de la entrada a la propiedad y C de la circunferencia correspondiente al alcance máximo de la señal emitida por ese sensor:`,fig:'3',ask:`Además, se desea colocar ese sensor en otro lugar de la propiedad, por lo tanto, este se traslada, desde su ubicación actual, a 12 m al oeste y 11 m al norte.<br><br>De acuerdo con la información anterior, ¿cuál es la representación algebraica de la circunferencia correspondiente al alcance máximo de la señal inalámbrica emitida por ese sensor en la nueva ubicación?`,options:['(x − 6)<sup>2</sup> + (y − 1)<sup>2</sup> = 36','(x − 6)<sup>2</sup> + (y − 23)<sup>2</sup> = 36','(x − 30)<sup>2</sup> + (y − 23)<sup>2</sup> = 36']},
{lead:`Una empresa construyó una pista de baile con forma circular, cuya medida del diámetro es 5 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra esa pista de baile:`,fig:'4',ask:`Además, durante un evento bailable se colocaron tres parlantes en distintos lugares:<ul><li>El parlante K se colocó en el punto correspondiente a (9, 4).</li><li>El parlante L se colocó en el punto correspondiente a (11, 6).</li><li>El parlante M se colocó en el punto correspondiente a (8, 12).</li></ul>De acuerdo con la información anterior, ¿cuál de esos parlantes se colocó sobre la pista de baile?`,options:['K','L','M']},
{lead:`En un parque nacional hay un sendero, una oficina de guardaparques y un mirador. El sendero tiene forma de línea recta con dirección de este a oeste y pasa por un lugar ubicado a 2 m al norte de esa oficina. Además, el mirador tiene forma circular, cuya medida de su diámetro es 4 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones N de la oficina del guardaparques y C de la circunferencia correspondiente al borde de ese mirador:`,fig:'5',ask:`De acuerdo con la información anterior, la recta que representa ese sendero es`,options:['exterior a C.','secante a C.','tangente a C.']},
{lead:`La siguiente figura, que representa la superficie de un jardín, está compuesta por un rectángulo y dos triángulos congruentes entre sí:`,fig:'6',ask:`De acuerdo con la información anterior, si se requiere colocar zacate a la totalidad de la superficie de ese jardín, entonces ¿cuántos metros cuadrados de zacate se requieren?`,options:['45','55','75']},
{lead:`La siguiente representación gráfica, cuyas unidades están en centímetros, muestra el trapecio ABCD correspondiente a la superficie de un pupitre:`,fig:'7',ask:`De acuerdo con la información anterior, si se requiere colocar una cinta adhesiva alrededor de la totalidad del borde de esa superficie, entonces, ¿cuántos centímetros de cinta, como mínimo, se requieren?`,options:['193','220','240']},
{lead:`En una feria de arte, hay nueve cuadros del mismo tamaño y la superficie de cada uno de ellos tiene forma de cuadrado. Se juntan cinco cuadros que forman una figura y los otros cuatro cuadros se colocan separados, tal y como se muestra a continuación:`,fig:'8',ask:`De acuerdo con la información anterior, el perímetro de la figura formada por los cuadros juntos es`,options:['igual que la suma de los perímetros de los cuadros separados.','mayor que la suma de los perímetros de los cuadros separados.','menor que la suma de los perímetros de los cuadros separados.']},
{lead:`La siguiente representación gráfica corresponde a la forma que tiene la ventana de un vehículo:`,fig:'9',ask:`De acuerdo con la información anterior, el área en centímetros cuadrados de esa ventana es mayor que`,options:['2300 pero menor que 2800.','2800 pero menor que 3300.','3300 pero menor que 3800.']},
{lead:`Considere la siguiente información:`,pre:`Un tallo de bambú, que tiene forma de cilindro circular recto, se utilizó para elaborar dos instrumentos musicales. Para ello, a ese tallo se le realizó un corte oblicuo con respecto a sus bases sin intersecarlas.`,ask:`De acuerdo con la información anterior, las secciones planas que se obtuvieron en ese tallo, producto del corte realizado, corresponden a`,options:['elipses.','rectángulos.','circunferencias.']},
{lead:`Un farol decorativo se fabrica a partir de una esfera de vidrio, a la cual se le realiza un corte para obtener una sección plana que representa la base del farol. La medida del radio de esa esfera es 25 cm. Además, cuando se realizó ese corte, el centro de la base quedó a 15 cm del centro de la esfera. ¿Cuál es la medida de la longitud de la circunferencia, en centímetros, que representa el borde de la base de ese farol?`,options:[m(num(20)+mi('π')),m(num(40)+mi('π')),m(num(58)+mi('π'))]},
{lead:`¿Cuántos litros de agua contiene ese tanque transcurridas 12 h, desde el inicio de ese día?`,options:['0','200','375']},
{lead:`Conforme avanzó el tiempo entre las 17 h y 23 h, desde el inicio de ese día, la cantidad de litros de agua contenida en ese tanque fue`,options:['constante.','aumentando.','disminuyendo.']},
{lead:`Considere la siguiente información:`,pre:`La función c, que determina la cantidad “c(x)” de suscriptores, en miles, que tuvo una plataforma de videos, está dada por c(x) = x<sup>3</sup> + 4, donde “x” representa el tiempo en años, desde la creación de esa plataforma, con 0 &lt; x ≤ 6.`,ask:`De acuerdo con la información anterior, ¿cuántos suscriptores, en miles, tuvo la plataforma de videos transcurridos cinco años desde su creación?`,options:['1','19','129']},
{lead:`La siguiente representación gráfica corresponde a la de la función f que determina la altura “y” en kilómetros desde el suelo a la que viaja un avión, en función del tiempo “x” en horas transcurridas a partir del inicio de ese viaje, con 1 ≤ x ≤ 3:`,fig:'15',ask:`De acuerdo con la información anterior, la representación gráfica de la función inversa de f corresponde a`,options:['<span data-fig="15A"></span>','<span data-fig="15B"></span>','<span data-fig="15C"></span>']},
{lead:`Considere la siguiente información:`,pre:`Un biólogo establece que la función b, la cual determina la cantidad de bacterias “b(n)” en millones que tiene una colonia, está dada por b(n) = 30(n + 5), donde “n” representa el tiempo en semanas transcurridas desde el inicio de un experimento, con 1 ≤ n ≤ 5.`,ask:`De acuerdo con la información anterior, si el biólogo requiere determinar la función n que relaciona el tiempo “n(b)” en semanas transcurridas desde el inicio del experimento, con la cantidad de bacterias “b” en millones que tiene esa colonia, entonces, ¿cuál es el criterio de n?`,options:['n(b) = −30b − 150',m(mi('n')+mo('(')+mi('b')+mo(')')+mo('=')+frac(mi('b')+mo('−')+num(150),num(30))),m(mi('n')+mo('(')+mi('b')+mo(')')+mo('=')+frac(mi('b')+mo('−')+num(5),num(30)))]},
{lead:`La siguiente representación gráfica muestra la función h que determina la altura “h(t)” en metros desde el suelo que alcanza un papalote (cometa), en función del tiempo “t” en minutos transcurridos a partir de su lanzamiento, con 0 &lt; t ≤ 8:`,fig:'17',ask:`De acuerdo con la información anterior, si para realizar un análisis de la altura alcanzada por el papalote se requiere determinar un posible intervalo del dominio de h tal que esta función tenga inversa, entonces, ¿cuál de las siguientes opciones corresponde a ese posible intervalo?`,options:['[0, 4]','[3, 7]','[6, 8]']},
{lead:`Considere la siguiente información:`,pre:`La función r, que determina la cantidad de litros de agua potable “r(n)” producidos en una planta de tratamiento, está dada por r(n) = 4(n<sup>2</sup> + 40), donde “n” representa el número de días que esa planta está en funcionamiento, con 10 ≤ n ≤ 20.`,ask:`De acuerdo con la información anterior, si se requiere determinar la función n, la cual relaciona el número de días “n(r)” que la planta de tratamiento está en funcionamiento con la cantidad de litros de agua potable “r” producidos por esa planta, entonces, ¿cuál es el criterio de n?`,options:[m(mi('n')+mo('(')+mi('r')+mo(')')+mo('=')+root(mi('r')+mo('−')+num(44))),m(mi('n')+mo('(')+mi('r')+mo(')')+mo('=')+root(frac(mi('r')+mo('−')+num(40),num(4)))),m(mi('n')+mo('(')+mi('r')+mo(')')+mo('=')+root(frac(mi('r')+mo('−')+num(160),num(4))))]},
{lead:`Considere la siguiente información:`,pre:`La función t, que determina la temperatura “t(x)” en grados Celsius, que es medida por una persona en el interior de una cueva, está dada por ${m(mi('t')+mo('(')+mi('x')+mo(')')+mo('=')+num(4)+root(mi('x')+mo('+')+num(1))+mo('+')+num(11))}, donde “x” representa la cantidad de metros de profundidad, desde la entrada de la cueva, a la que se ubica esa persona, con 0 ≤ x ≤ 99.`,ask:`De acuerdo con la información anterior, si Andrés se ubica a 24 m de profundidad, desde la entrada de la cueva, entonces ¿cuál es la temperatura que es medida por Andrés en esa ubicación?`,options:['24 °C','31 °C','64 °C']},
{lead:`El salario mensual en colones, que obtiene un agente de ventas, está relacionado linealmente con la cantidad de artículos que él vende en cada mes de un año. En la siguiente tabla se muestran la cantidad de artículos vendidos por el agente y el salario mensual de este, durante dos meses de ese año:`,pre:tableHTML([['Mes','Cantidad de artículos vendidos','Salario mensual del agente de ventas'],['Mayo','10','₡555 000'],['Agosto','16','₡588 000']],true),ask:`De acuerdo con la información anterior, la ecuación de la recta que representa el salario mensual “y” obtenido por el agente de ventas, en función de la cantidad “x” de artículos que él vende en cada mes de ese año, corresponde a`,options:['y = 5500x + 500 000','y = 500 000x + 5500','y = 5500x + 610 000']},
{lead:`Considere la siguiente información:`,pre:`La función h, que determina la altura “h(x)” en metros desde el suelo, de una pelota lanzada verticalmente hacia arriba durante un juego, está dada por h(x) = −5x<sup>2</sup> + 20x + 5, donde “x” representa el tiempo en segundos transcurridos desde que la pelota fue lanzada, con 0 &lt; x ≤ 5.`,ask:`De acuerdo con la información anterior, ¿cuál fue la altura en metros desde el suelo alcanzada por la pelota transcurridos 3 s desde que fue lanzada?`,options:['4','20','35']},
{lead:`Considere la siguiente información:`,pre:`La función v, que determina el valor “v(t)” en miles de dólares de una máquina, está dada por v(t) = 2 · (0,9)<sup>t</sup>, donde “t” representa el tiempo en años transcurridos desde que la máquina fue adquirida, con 0 &lt; t ≤ 8.`,ask:`De acuerdo con la información anterior, ¿cuál es el valor aproximado, en miles de dólares, de esa máquina transcurridos cuatro años desde que fue adquirida?`,options:['1,31','7,20','10,50']},
{lead:`Considere la siguiente información:`,pre:`En una campaña de donación de sangre se determinó que la función b, que determina la cantidad “b(x)” de bolsas de sangre recolectadas, está dada por b(x) = 4 · log<sub>2</sub>(x), donde “x” representa el tiempo en días transcurridos desde que inició esa campaña, con 1 &lt; x ≤ 128.`,ask:`De acuerdo con la información anterior, ¿cuántas bolsas de sangre fueron recolectadas transcurridos 8 días desde que inició la campaña?`,options:['4','12','16']},
{lead:`Considere la siguiente información:`,pre:`Al inicio de un experimento científico un gusano tenía una longitud de 3 cm. Además, se determinó que, por cada semana trascurrida desde el inicio del experimento, ese gusano crecía 6 cm.`,ask:`De acuerdo con la información anterior, la ecuación de la recta correspondiente a la longitud “y” en centímetros de ese gusano, en función de la cantidad “x” de semanas transcurridas desde el inicio del experimento, es`,options:['y = 9x','y = 6x + 3','y = 3x + 6']},
{lead:`A continuación, se muestra la representación gráfica de la función cuadrática p correspondiente a la cantidad “p(x)” en kilogramos de un tipo de fruta cosechada de un árbol, en función de la cantidad de fertilizante “x” en kilogramos utilizados en ese árbol, con 0 &lt; x ≤ 14:`,fig:'25',ask:`De acuerdo con la información anterior, ¿cuántos kilogramos de ese fertilizante se utilizaron en el árbol para que se cosechara la mayor cantidad de ese tipo de fruta?`,options:['7','14','69']},
{lead:`Considere la siguiente información:`,pre:`La función q, que determina la cantidad “q(t)” en millones de partículas, que tiene una muestra de un elemento radiactivo, está dada por ${m(mi('q')+mo('(')+mi('t')+mo(')')+mo('=')+num(5)+'<msup><mrow>'+mo('(')+frac(num(1),num(2))+mo(')')+'</mrow><mi>t</mi></msup>')}, donde “t” representa el tiempo, en días, desde el inicio de un experimento, con 0 &lt; t ≤ 6.`,ask:`De acuerdo con la información anterior, ¿cuántas partículas aproximadamente, en millones, tendrá esa muestra a los tres días desde el inicio de ese experimento?`,options:['0,63','0,74','0,83']},
{lead:`Considere la siguiente información:`,pre:`La función n, que determina la cantidad de nutrientes “n(h)” que una planta absorbe de la tierra, durante un periodo continuo de exposición a la luz del sol, está dada por n(h) = 8 · log<sub>2</sub>(h), donde “h” representa el tiempo en horas continuas de exposición a la luz del sol, con 4 ≤ h ≤ 12.`,ask:`De acuerdo con la información anterior, si una planta estuvo expuesta a la luz del sol durante 8 h continuas, entonces, ¿cuántos nutrientes absorbió de la tierra esa planta?`,options:['2','24','32']},
{lead:`Elena compró 5 kg de papas y 3 kg de carne, por los cuales pagó en total ₡21 841. Javier compró 3 kg de papas y 4 kg de carne, por los cuales pagó en total ₡23 383. Si cada kilogramo de papas tiene el mismo precio y cada kilogramo de carne tiene el mismo precio, entonces, ¿cuál es el precio de cada kilogramo de papas?`,options:['₡1565','₡2546','₡2760']},
{lead:`Jorge compró 3 kg de café y 4 kg de azúcar, por los cuales pagó en total ₡18 000. Elizabeth compró 4 kg de café y 2 kg de azúcar, por los cuales pagó en total ₡19 000. Si cada kilogramo de ese café tenía el mismo precio y cada kilogramo de esa azúcar tenía el mismo precio, entonces, ¿cuál es el precio que tenía cada kilogramo de café?`,options:['₡3400','₡4000','₡8500']},
{lead:`En la siguiente tabla se muestra la función p que determina la cantidad “p(x)” de plantas que crecieron cada año en una reserva natural, en función del tiempo “x” en años transcurridos desde el inicio de un experimento, con 1 ≤ x ≤ 7:`,pre:tableHTML([['x','1','2','3','4','5','6','7'],['p(x)','80','85','90','95','100','105','110']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar p?`,options:['Función lineal','Función logarítmica','Función exponencial']},
{lead:`La siguiente tabla muestra la función m que determina la cantidad de residuos “m(x)”, en miles de kilogramos, reciclada por una planta de tratamiento, en función del tiempo “x” en años transcurridos desde su apertura, con 1 ≤ x ≤ 5:`,pre:tableHTML([['x','1','2','3','4','5'],['m(x)','10','40','90','160','250']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar m?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondientes a los tiempos en minutos, que tardaron varios atletas en completar una carrera:`,fig:'32',ask:`De acuerdo con la información anterior, si 20 min corresponde a la mediana de esos datos, entonces el tiempo promedio que tardaron los atletas en completar esa carrera fue`,options:['igual que 20 min.','mayor que 20 min.','menor que 20 min.']},
{lead:`¿Cuál fue el tiempo que con mayor frecuencia tardaron los repartidores en entregar los pedidos solicitados por los clientes?`,options:['13 min','15 min','16 min']},
{lead:`¿Cuál fue el menor tiempo que tardó un repartidor en entregar un pedido a un cliente?`,options:['6 min','10 min','28 min']},
{lead:`La siguiente tabla muestra el valor porcentual en cada uno de los tres componentes que se consideraron al calificar un proyecto de diseño en un concurso de arquitectura. Además, se muestra la calificación obtenida por componente, en una escala de 1 a 100, del diseño presentado por Daniel:`,pre:tableHTML([['Componente','Porcentaje','Calificación obtenida por componente'],['Innovación','50 %','83'],['Funcionalidad','30 %','89'],['Estética','20 %','93']],true),ask:`Asimismo, la nota final de ese proyecto corresponderá a la media aritmética ponderada de todos los componentes evaluados:<br><br>De acuerdo con la información anterior, ¿cuál será la nota final del proyecto presentado por Daniel en ese concurso?`,options:['89,0','88,3','86,8']},
{lead:`La siguiente tabla muestra tres polígonos regulares que representan, cada uno, el piso de cada una de las cabañas que construyó Julieta:`,fig:'36',ask:`De acuerdo con la información anterior, si Julieta le colocó cerámica a la totalidad del piso de cada una de las cabañas, entonces ¿en cuál de esas cabañas Julieta colocó la mayor cantidad de metros cuadrados de cerámica?`,options:['W','R','T']},
{lead:`La función p, que determina la cantidad “p(x)” de personas que tenía una ciudad, está dada por p(x) = 500x<sup>3</sup> + 2000, donde “x” representa el tiempo en años transcurridos desde que la ciudad fue fundada, con 0 &lt; x ≤ 5. ¿Cuál fue la cantidad de personas que tenía esa ciudad transcurridos cuatro años desde que fue fundada?`,options:['8000','34 000','42 500']},
{lead:`Considere la siguiente información:`,pre:`Un estudio científico determinó que la función q, que representa la cantidad de energía “q(t)” en kilovatios-hora, generada por un panel solar, está dada por ${m(mi('q')+mo('(')+mi('t')+mo(')')+mo('=')+num('0,2')+mo('+')+num('0,7')+root(mi('t')+mo('+')+num(3)))}, donde “t” representa el tiempo, en horas, que ese panel estuvo expuesto a la luz del sol, con 4 ≤ t ≤ 8.`,ask:`De acuerdo con la información anterior, ¿cuál es la cantidad de energía, en kilovatios-hora, generada por ese panel si estuvo expuesto a la luz del sol durante 6 h?`,options:['2,3','2,7','4,9']},
{lead:`Considere la siguiente información referente a la función n que determina la cantidad de clientes “n(t)” que visitaron una cafetería durante una semana, en función del tiempo “t” en días transcurridos desde el inicio de esa semana, con 1 ≤ t ≤ 7:`,pre:tableHTML([['t','1','2','3','4','5','6','7'],['n(t)','120','250','380','510','640','770','900']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar n?`,options:['Función exponencial','Función cuadrática','Función lineal']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondientes a la masa en kilogramos, de los niños que nacieron en un hospital durante un mes:`,fig:'40',ask:`De acuerdo con la información anterior, si 2,95 kg corresponde a la mediana de esos datos, entonces la masa promedio de los niños que nacieron en el hospital durante ese mes fue`,options:['igual que 2,95 kg.','mayor que 2,95 kg.','menor que 2,95 kg.']}
];
const SHARED={
12:{lead:`Para responder los ítems 12 y 13, considere la siguiente información:`,pre:`La siguiente representación gráfica muestra la función a que determina la cantidad de litros de agua “a(t)” contenida en un tanque de almacenamiento, en función del tiempo “t” en horas transcurridas, desde el inicio de un día, con 0 &lt; t &lt; 24:`,fig:'12'},
33:{lead:`Para responder los ítems 33 y 34, considere la siguiente información:`,pre:`En la siguiente tabla se presentan algunas medidas de posición referidas a los tiempos, en minutos, que tardaron los repartidores de una empresa en entregar los pedidos solicitados por los clientes, durante un día:${tableHTML([['Medida de posición','Valor'],['Tercer cuartil','21'],['Primer cuartil','10'],['Promedio','16'],['Mediana','15'],['Moda','13'],['Máximo','28'],['Mínimo','6']],true)}`}
};
if(QUESTIONS.length!==40||QUESTIONS.some(q=>q.options.length!==3))throw Error('Transcripción incompleta.');
