const ANSWER_KEY='C B B B A B C C B A B C C C B B C C B A B A B B A A B A B A B C A A C A B A C B'.replace(/\s/g,'');
const SOLUTIONS=[
`La circunferencia tiene centro (10, 12) y radio 3. Su ecuación es (x − 10)<sup>2</sup> + (y − 12)<sup>2</sup> = 9.`,
`La gráfica B tiene centro (6, 4) y radio 2: el extremo derecho está en x = 8.`,
`El centro se traslada de (18, 12) a (18 − 12, 12 + 11) = (6, 23). El radio sigue siendo 6 y su cuadrado es 36.`,
`El centro de la pista es (10, 7,5) y el radio es 2,5 m. Para L(11, 6), la distancia al centro es ${m(root(num(1)+mo('+')+num('2,25')))} m, menor que 2,5. Los otros parlantes quedan fuera.`,
`La circunferencia va desde y = 4 hasta y = 8. La recta del sendero es y = 2 y no la interseca: es exterior.`,
`El rectángulo tiene área 7 · 5 = 35 m<sup>2</sup>. Las alturas de los dos triángulos suman 15 − 7 = 8 m. Juntos tienen área ${m(frac(num(5)+mo('·')+num(8),num(2)))} = 20 m<sup>2</sup>. En total: 55 m<sup>2</sup>.`,
`AB = 120 − 20 = 100 cm y DC = 90 − 50 = 40 cm. Aplicando Pitágoras con catetos 30 y 40 se obtiene ${m(root('<msup><mn>30</mn><mn>2</mn></msup>'+mo('+')+'<msup><mn>40</mn><mn>2</mn></msup>')+mo('=')+num(50))} cm por lado oblicuo. Perímetro: 100 + 40 + 50 + 50 = 240 cm.`,
`Si el lado mide L, los cinco cuadrados juntos forman un rectángulo de 5L por L, cuyo perímetro es 12L. Los cuatro cuadrados separados suman 16L. Por tanto, el perímetro de la figura formada es menor.`,
`Cada cuadrado representa 20 · 20 = 400 cm<sup>2</sup>. La ventana ocupa aproximadamente 7,5 cuadrados de la cuadrícula, cerca de 3000 cm<sup>2</sup>. Su área es mayor que 2800 y menor que 3300 cm<sup>2</sup>.`,
`Un plano oblicuo que corta un cilindro circular recto sin intersecar sus bases produce una sección elíptica.`,
`Por Pitágoras, el radio de la base es ${m(root('<msup><mn>25</mn><mn>2</mn></msup>'+mo('−')+'<msup><mn>15</mn><mn>2</mn></msup>')+mo('=')+num(20))} cm. La longitud de su circunferencia es 2π · 20 = 40π cm.`,
`Entre las horas 10 y 16, la gráfica es horizontal a 375 litros. A las 12 h contiene 375 litros.`,
`Entre las horas 16 y 24, la gráfica desciende. Por ello, entre las 17 h y 23 h la cantidad de agua disminuye.`,
`c(5) = 5<sup>3</sup> + 4 = 125 + 4 = 129 miles de suscriptores.`,
`La gráfica de f une (1, 2) y (3, 4). La inversa intercambia las coordenadas y une (2, 1) y (4, 3), como muestra B.`,
`b = 30(n + 5) = 30n + 150. Se despeja ${m(mi('n')+mo('=')+frac(mi('b')+mo('−')+num(150),num(30)))}.`,
`En [6, 8], la altura aumenta estrictamente y cada altura corresponde a un solo tiempo. Los otros intervalos incluyen un tramo horizontal, donde se repiten alturas.`,
`r = 4n<sup>2</sup> + 160. Entonces ${m(mi('n')+mo('=')+root(frac(mi('r')+mo('−')+num(160),num(4))))}, tomando la raíz positiva por tratarse de días.`,
`t(24) = ${m(num(4)+root(num(24)+mo('+')+num(1))+mo('+')+num(11)+mo('=')+num(4)+mo('·')+num(5)+mo('+')+num(11)+mo('=')+num(31))} °C.`,
`La pendiente es ${m(frac(num(588000)+mo('−')+num(555000),num(16)+mo('−')+num(10))+mo('=')+num(5500))}. El salario fijo es 555 000 − 5500 · 10 = 500 000. Por tanto, y = 5500x + 500 000.`,
`h(3) = −5 · 3<sup>2</sup> + 20 · 3 + 5 = −45 + 60 + 5 = 20 m.`,
`v(4) = 2 · (0,9)<sup>4</sup> = 1,3122, aproximadamente 1,31 miles de dólares.`,
`b(8) = 4 · log<sub>2</sub>(8) = 4 · 3 = 12 bolsas.`,
`El gusano comienza con 3 cm y aumenta 6 cm por semana. La longitud es y = 6x + 3.`,
`La mayor cantidad de fruta corresponde al vértice de la parábola. Su coordenada horizontal es 7 kg de fertilizante.`,
`q(3) = ${m(num(5)+mo('·')+'<msup><mrow>'+mo('(')+frac(num(1),num(2))+mo(')')+'</mrow><mn>3</mn></msup>'+mo('=')+frac(num(5),num(8))+mo('=')+num('0,625'))}, aproximadamente 0,63 millones de partículas.`,
`n(8) = 8 · log<sub>2</sub>(8) = 8 · 3 = 24 nutrientes.`,
`Si p es el precio del kilogramo de papas y c el de carne: 5p + 3c = 21 841 y 3p + 4c = 23 383. Multiplicando por 4 y 3 y restando: 11p = 17 215. Por tanto, p = ₡1565.`,
`Si c es el precio del café y a el del azúcar: 3c + 4a = 18 000 y 4c + 2a = 19 000. Al duplicar la segunda ecuación y restar la primera, 5c = 20 000. Cada kilogramo de café costó ₡4000.`,
`La cantidad aumenta 5 plantas por año. Una tasa constante corresponde a una función lineal.`,
`Los valores son 10x<sup>2</sup>: 10, 40, 90, 160 y 250. El modelo es cuadrático.`,
`La distribución tiene una cola hacia la izquierda. En esta distribución, el promedio es menor que la mediana de 20 min.`,
`La moda indica el tiempo más frecuente. Según la tabla, es 13 min.`,
`El mínimo de la tabla es 6 min, el menor tiempo de entrega.`,
`La nota ponderada es 0,50 · 83 + 0,30 · 89 + 0,20 · 93 = 41,5 + 26,7 + 18,6 = 86,8.`,
`El hexágono W, de lado 10 m, tiene área ${m(num(150)+root(num(3)))} ≈ 259,81 m<sup>2</sup>. El triángulo R, de lado 20 m, tiene área ${m(num(100)+root(num(3)))} ≈ 173,21 m<sup>2</sup>. El cuadrado T tiene área 15<sup>2</sup> = 225 m<sup>2</sup>. La mayor área es W.`,
`p(4) = 500 · 4<sup>3</sup> + 2000 = 32 000 + 2000 = 34 000 personas.`,
`q(6) = ${m(num('0,2')+mo('+')+num('0,7')+root(num(6)+mo('+')+num(3))+mo('=')+num('0,2')+mo('+')+num('0,7')+mo('·')+num(3)+mo('=')+num('2,3'))} kWh.`,
`La cantidad de clientes aumenta 130 cada día. Una tasa constante corresponde a una función lineal.`,
`La distribución tiene una cola hacia la derecha. Por eso, el promedio es mayor que la mediana de 2,95 kg.`
];
if(ANSWER_KEY.length!==40||SOLUTIONS.length!==40)throw Error('Clave o soluciones incompletas.');
