const TOTAL=35,SECONDS=3*60*60,EXAM='n01_2023';
const KEY=ANSWER_KEY;
const BACKEND_READY=true;
const API='https://script.google.com/macros/s/AKfycbzTbcCEbXGaZgIHfiBo8MExOJ5o8wpPSTuvLgdaGHhRNzuwRCwPeyJy5xHXhy2P518HJQ/exec';
const LEGACY_API='https://script.google.com/macros/s/AKfycbwtRGWJPNc8n413pPLvQE5ntBUFfJeG2qKJVxhhNG9CM8tlxqXb-j07anfudEV7Zz0y/exec';
const STORE='pne_2023_n01_attempt_v1',$=id=>document.getElementById(id);
let answers=Array(TOTAL).fill(null),index=0,attemptId='',ticket='',student=null,endsAt=0,finished=false,timedOut=false,submitted=false,sending=false,available=false,ticker;
const area=n=>n<=11?'Geometría':n<=31?'Relaciones y Álgebra':'Estadística y Probabilidad';
const context=n=>n>=12&&n<=13?12:n>=33&&n<=34?33:null;
function renderManual(item,target,number){
  target.innerHTML=`<article class="manual-item"><p class="lead">${item.lead}</p>${item.pre?`<div class="pre">${item.pre}</div>`:''}${item.fig?`<div class="figure">${drawFigure(item.fig)}</div>`:''}${item.ask?`<p class="ask">${item.ask}</p>`:''}${item.options?`<div class="choice-list" role="group" aria-label="Selecciona tu respuesta">${item.options.map((option,i)=>{const letter='ABC'[i];return `<button type="button" class="choice${number&&answers[number-1]===letter?' selected':''}" data-answer="${letter}" aria-pressed="${number&&answers[number-1]===letter?'true':'false'}"><span class="choice-letter">${letter})</span><span class="choice-content">${option}</span></button>`}).join('')}</div>`:''}</article>`;
  target.querySelectorAll('[data-fig]').forEach(el=>{el.innerHTML=drawFigure(el.dataset.fig)});
  if(number)target.querySelectorAll('[data-answer]').forEach(button=>{button.onclick=()=>{answers[number-1]=button.dataset.answer;show(number-1)}});
}
function save(){try{localStorage.setItem(STORE,JSON.stringify({answers,index,attemptId,ticket,student,endsAt,finished,timedOut,submitted}))}catch{}}
function restore(){try{const s=JSON.parse(localStorage.getItem(STORE)||'null');if(!s)return;answers=Array.from({length:TOTAL},(_,i)=>'ABC'.includes(s.answers?.[i])?s.answers[i]:null);index=Math.max(0,Math.min(TOTAL-1,Number(s.index)||0));attemptId=s.attemptId||'';ticket=s.ticket||'';student=s.student||null;endsAt=Number(s.endsAt)||0;finished=!!s.finished;timedOut=!!s.timedOut;submitted=!!s.submitted}catch{}}
function uuid(){return crypto.randomUUID?crypto.randomUUID():'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g,c=>(Math.random()*16|0).toString(16))}
function jsonp(op,extra={}){return new Promise((resolve,reject)=>{const callback='examStatus_'+Math.random().toString(36).slice(2),script=document.createElement('script'),url=new URL(API);let timeout;const clean=()=>{clearTimeout(timeout);delete window[callback];script.remove()};window[callback]=data=>{clean();resolve(data)};script.onerror=()=>{clean();reject(Error('No se pudo conectar con el horario.'))};timeout=setTimeout(()=>{clean();reject(Error('La consulta tardó demasiado.'))},12000);Object.entries({op,exam:EXAM,callback,...extra,_:Date.now()}).forEach(([key,value])=>url.searchParams.set(key,value));script.src=url;document.head.append(script)})}
async function check(){if(!BACKEND_READY){available=false;$('start').disabled=true;$('retry').hidden=true;$('availability').textContent='Esta prueba aún no está habilitada.';return}available=false;$('start').disabled=true;$('retry').hidden=true;$('availability').textContent='Consultando disponibilidad de la prueba…';try{const chosen=$('section').value;const status=await jsonp('status',chosen?{section:chosen}:{});if(chosen!==$('section').value)return;if(Array.isArray(status.sections)){const options=status.sections.filter(s=>/^(?:11-1|11-2)$/.test(s));const current=$('section').value;$('section').replaceChildren(new Option('Selecciona tu sección',''),...options.map(s=>new Option(s,s)));$('section').value=options.includes(current)?current:''}available=!!status.open&&!!$('section').value;$('availability').textContent=available?`Prueba disponible para ${$('section').value}${status.endsAt?' hasta '+status.endsAt+' (Costa Rica)':''}.`:status.message||'La prueba está cerrada.';$('start').disabled=!available}catch(e){$('availability').textContent=e.message;$('retry').hidden=false}}
function count(){const n=answers.filter(Boolean).length;$('counter').textContent=`${n} / ${TOTAL} respondidas`;$('sidebarCount').textContent=`${n} de ${TOTAL} respondidos`;return n}
function show(n){index=n;const id=n+1,c=context(id);$('qtitle').textContent=`Ítem ${id} de ${TOTAL}`;$('area').textContent=`Área: ${area(id)}`;$('qstatus').textContent=answers[n]?`Respuesta: ${answers[n]}`:'Sin responder';renderManual(QUESTIONS[n],$('questionVector'),id);$('context').hidden=!c;if(c)renderManual(SHARED[c],$('contextVector'));$('prev').disabled=n===0;$('next').textContent=n===TOTAL-1?'Finalizar':'Siguiente →';const grid=$('grid');grid.replaceChildren();answers.forEach((answer,i)=>{const button=document.createElement('button');button.type='button';button.textContent=i+1;button.className=(answer?'answered ':'')+(i===n?'current':'');button.setAttribute('aria-label',`Ir al ítem ${i+1}${answer?', respondido':''}`);button.onclick=()=>show(i);grid.append(button)});count();save()}
function format(t){const h=Math.floor(t/3600),m=Math.floor(t%3600/60),s=t%60;return[h,m,s].map(x=>String(x).padStart(2,'0')).join(':')}
function clock(){const remaining=Math.max(0,Math.ceil((endsAt-Date.now())/1000));$('clock').textContent=format(remaining);if(!remaining&&!finished)finish(true)}
function enter(){if(!attemptId||!ticket)return;$('welcome').hidden=true;$('results').hidden=true;$('exam').hidden=false;show(index);clock();clearInterval(ticker);ticker=setInterval(clock,1000)}
async function start(){const firstName=$('firstName').value.trim().replace(/\s+/g,' '),lastName=$('lastName').value.trim().replace(/\s+/g,' '),section=$('section').value,valid=/^[A-Za-zÁÉÍÓÚÜÑáéíóúüñÀ-ÿ' .-]{2,70}$/;if(!valid.test(firstName)||!valid.test(lastName)){$('availability').textContent='Escribe tu nombre y tus apellidos.';return}if(!section){$('availability').textContent='Selecciona tu sección.';return}if(!available){await check();if(!available)return}$('start').disabled=true;$('availability').textContent='Confirmando horario de inicio…';try{const attempt=uuid(),status=await jsonp('start',{id:attempt,section});if(!status.open||!status.ticket)throw Error(status.message||'La prueba no está disponible.');student={firstName,lastName,section};attemptId=attempt;ticket=status.ticket;endsAt=Number(status.attemptEndsAtEpoch)||0;if(endsAt<=Date.now())throw Error('El horario de la prueba terminó.');save();enter()}catch(e){$('availability').textContent=e.message;await check()}}
function grade(){const correct=answers.filter((a,i)=>a===KEY[i]).length,blank=answers.filter(a=>!a).length;$('score').textContent=`${correct} / ${TOTAL}`;$('scorePercent').textContent=`${Math.round(100*correct/TOTAL)} % de respuestas correctas${timedOut?' · Tiempo agotado':''}`;const passed=100*correct/TOTAL>=70;$('gradeStatus').textContent=`Nota: ${Math.round(100*correct/TOTAL)}/100 · ${passed?'Aprobado':'Reprobado'}`;$('gradeStatus').style.color=passed?'#166534':'#991b1b';$('correct').textContent=correct;$('wrong').textContent=TOTAL-correct-blank;$('blank').textContent=blank;const chart=$('areaCharts');chart.replaceChildren();for(const [label,first,last] of [['Geometría',1,11],['Relaciones y Álgebra',12,31],['Estadística y Probabilidad',32,35]]){let c=0,w=0,b=0;for(let i=first-1;i<last;i++){if(answers[i]===KEY[i])c++;else if(answers[i])w++;else b++}let total=last-first+1,pct=100*c/total;const card=document.createElement('article'),heading=document.createElement('h3'),pie=document.createElement('div'),rate=document.createElement('div'),legend=document.createElement('div');card.className='chart';heading.textContent=label;pie.className='pie';pie.style.setProperty('--c',pct+'%');pie.style.setProperty('--w',100*(c+w)/total+'%');pie.setAttribute('role','img');pie.setAttribute('aria-label',`${label}: ${c} correctas, ${w} incorrectas, ${b} sin responder, de ${total} ítems`);rate.className='rate';rate.textContent=pct.toFixed(0)+' %';legend.className='legend';legend.textContent=`Correctas ${c} · Incorrectas ${w} · Sin responder ${b}`;card.append(heading,pie,rate,legend);chart.append(card)}renderReview()}
function renderReview(){const review=$('review');review.replaceChildren();answers.forEach((answer,i)=>{const row=document.createElement('article'),top=document.createElement('div'),label=document.createElement('b'),yours=document.createElement('span'),correct=document.createElement('span'),solution=document.createElement('div');row.className='review-row';top.className='review-top';label.textContent=`Ítem ${i+1}`;yours.textContent='Tu respuesta: ';const given=document.createElement('strong');given.className=answer===KEY[i]?'ok':'bad';given.textContent=answer||'—';yours.append(given);correct.textContent='Correcta: ';const key=document.createElement('strong');key.className='ok';key.textContent=KEY[i];correct.append(key);top.append(label,yours,correct);solution.className='review-solution';solution.innerHTML=`<b>Solución:</b><div>${SOLUTIONS[i]}</div>`;row.append(top,solution);review.append(row)})}
function result(){clearInterval(ticker);$('welcome').hidden=true;$('exam').hidden=true;$('results').hidden=false;$('clock').textContent='00:00:00';grade();window.scrollTo(0,0)}
function finish(auto=false){$('finishDialog').close();if(finished){result();return}if(!auto){const missing=TOTAL-count();$('finishMessage').textContent=missing?`Aún tienes ${missing} ${missing===1?'ítem':'ítems'} sin responder. ¿Deseas finalizar de todas formas?`:'Has respondido todos los ítems. ¿Deseas finalizar?';$('finishDialog').showModal();return}clearInterval(ticker);finished=true;timedOut=endsAt<=Date.now();save();result();send()}
function send(){if(submitted||sending||!ticket)return;sending=true;$('delivery').textContent='Enviando respuestas al registro privado…';$('delivery').hidden=false;$('retryDelivery').hidden=true;const nonce=uuid(),frame=document.createElement('iframe'),form=document.createElement('form');frame.name='upload_'+nonce.replace(/-/g,'');frame.hidden=true;form.hidden=true;form.method='POST';form.action=student?.section?API:LEGACY_API;form.target=frame.name;const payload={attemptId,ticket,sessionId:'',firstName:student.firstName,lastName:student.lastName,section:student.section,answers,elapsedSeconds:SECONDS-Math.max(0,(endsAt-Date.now())/1000),timedOut};for(const [name,value] of Object.entries({exam:EXAM,nonce,payload:JSON.stringify(payload)})){const input=document.createElement('input');input.name=name;input.value=value;form.append(input)}document.body.append(frame,form);let timeout;const done=(message,retry)=>{clearTimeout(timeout);window.removeEventListener('message',onMessage);form.remove();frame.remove();sending=false;submitted=!retry;save();$('delivery').textContent=message;$('delivery').hidden=!message;$('retryDelivery').hidden=!retry};const onMessage=e=>{if(!/^https:\/\/(?:script\.google\.com|script\.googleusercontent\.com|[a-z0-9-]+[.-]script\.googleusercontent\.com)$/.test(e.origin)||e.data?.kind!=='educacion-abierta-exam-save'||e.data.nonce!==nonce)return;if(e.data.status==='ok'||e.data.status==='duplicate')done('',false);else done(e.data.message||'No se pudo guardar el resultado.',true)};window.addEventListener('message',onMessage);timeout=setTimeout(()=>done('No se confirmó la recepción. Pulsa «Reintentar envío».',true),22000);form.submit()}
function reset(){clearInterval(ticker);localStorage.removeItem(STORE);answers=Array(TOTAL).fill(null);index=0;attemptId='';ticket='';student=null;endsAt=0;finished=false;timedOut=false;submitted=false;$('review').hidden=true;$('reviewBtn').textContent='Revisar respuestas';$('reviewBtn').setAttribute('aria-expanded','false');$('results').hidden=true;$('exam').hidden=true;$('welcome').hidden=false;$('clock').textContent=format(SECONDS);$('firstName').value='';$('lastName').value='';$('section').value='';count();check()}
$('section').addEventListener('change',check);$('start').onclick=start;$('retry').onclick=check;$('retryDelivery').onclick=send;$('menuBtn').onclick=()=>location.assign('../');$('reviewBtn').onclick=()=>{const open=$('review').hidden;$('review').hidden=!open;$('reviewBtn').textContent=open?'Ocultar revisión':'Revisar respuestas';$('reviewBtn').setAttribute('aria-expanded',String(open))};$('restart').onclick=reset;$('prev').onclick=()=>show(Math.max(0,index-1));$('next').onclick=()=>index<TOTAL-1?show(index+1):finish(false);$('finish').onclick=()=>finish(false);$('cancelFinish').onclick=()=>$('finishDialog').close();$('confirmFinish').onclick=()=>{finish(true)};
if(new URLSearchParams(location.search).has('nuevo'))localStorage.removeItem(STORE);restore();count();if(finished){result();if(!submitted)$('retryDelivery').hidden=false}else if(attemptId&&ticket){if(endsAt<=Date.now())finish(true);else enter()}else check();
