// Transcripción manual cotejada con el cuadernillo 2025-T01, en su orden original.
const m=body=>`<math xmlns="http://www.w3.org/1998/Math/MathML" displaystyle="true">${body}</math>`;
const root=body=>`<msqrt><mrow>${body}</mrow></msqrt>`;
const frac=(a,b)=>`<mfrac><mrow>${a}</mrow><mrow>${b}</mrow></mfrac>`;
const num=n=>`<mn>${n}</mn>`,mi=x=>`<mi>${x}</mi>`,mo=x=>`<mo>${x}</mo>`;
const tableHTML=(rows,open=false)=>`<div class="table-wrap"><table class="exam-table${open?' open-table':''}">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'}>${c}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table></div>`;
const QUESTIONS=[
{lead:`El centro de un carrusel (juego mecánico con forma circular) se ubicó 5 m al norte y 6 m al este de la entrada a un parque, la cual se considera como el origen. La medida del radio de la circunferencia, que representa el borde de ese carrusel, es 4 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones M del centro del carrusel, A de la entrada a ese parque y C de la circunferencia correspondiente al borde del carrusel:`,fig:'1',ask:`De acuerdo con la información anterior, ¿cuál es la representación algebraica, cuyas unidades están en metros, de C?`,options:['(x + 6)<sup>2</sup> + (y + 5)<sup>2</sup> = 4','(x − 6)<sup>2</sup> + (y + 5)<sup>2</sup> = 8','(x − 6)<sup>2</sup> + (y − 5)<sup>2</sup> = 16']},
{lead:`La medida del radio, de la circunferencia que representa el borde de un terreno, es 10 m. La ubicación T del centro del terreno corresponde a 15 m al este y 20 m al norte de la ubicación Q de una casa, la cual se considera como el origen. ¿Cuál es la representación gráfica, cuyas unidades están en metros, de la circunferencia que representa el borde de ese terreno?`,options:['<span data-fig="2A"></span>','<span data-fig="2B"></span>','<span data-fig="2C"></span>']},
{lead:`Una cámara de vigilancia se colocó en un lugar ubicado a 2 km al este y 2 km al norte de la sala de control, la cual se considera como el origen. El alcance máximo de la zona vigilada por la cámara es 1 km a su alrededor.`,pre:`La siguiente representación gráfica, cuyas unidades están en kilómetros, muestra las ubicaciones M de la cámara, G de la sala de control y C de la circunferencia correspondiente al alcance máximo de zona vigilada por esa cámara:`,fig:'3',ask:`Además, debido a prioridades en la seguridad se decidió colocar la cámara en otro lugar. Para ello, la cámara se trasladó, desde su ubicación actual, a 1 km al sur y 3 km al oeste.<br><br>De acuerdo con la información anterior, ¿cuál es la representación algebraica, cuyas unidades están en kilómetros, de la circunferencia correspondiente al alcance máximo de la zona vigilada por esa cámara en la nueva ubicación?`,options:['(x + 1)<sup>2</sup> + (y − 1)<sup>2</sup> = 1','(x + 1)<sup>2</sup> + (y − 3)<sup>2</sup> = 1','(x − 5)<sup>2</sup> + (y − 1)<sup>2</sup> = 1']},
{lead:`Considere la siguiente información:`,pre:`En un parque ecológico se diseñó en el suelo una zona de descanso con forma circular. El borde de esta zona está representado por la circunferencia C cuya representación algebraica corresponde a (x − 2)<sup>2</sup> + (y + 1)<sup>2</sup> = 9. Además, se colocaron dos postes de iluminación en los puntos correspondientes a (5, 2) y (−1, −4) con la finalidad de conectarlos mediante un cable tensado (estirado) colocado encima del suelo.`,ask:`De acuerdo con la información anterior, la recta que representa ese cable, con respecto a C, será`,options:['exterior.','secante.','tangente.']},
{lead:`Un juego consiste en lanzar con una mano, desde una cierta distancia, unas flechas denominadas dardos a un objetivo circular (diana) fijado en una pared.`,pre:`La representación gráfica muestra la circunferencia C de centro O, correspondiente al borde de una diana, que se utilizó durante un juego de dardos:`,fig:'5',ask:`Asimismo, durante ese juego una persona lanzó tres dardos R, S y T, que impactaron en los puntos que corresponden a (6, 1), (9, 4) y (6, 5), respectivamente.<br><br>De acuerdo con la información anterior, ¿cuál de esos dardos impactó en el interior de esa diana?`,options:['R','S','T']},
{lead:`Un juego consiste en formar figuras con algunas de sus piezas, las cuales se colocan una a la par de la otra. Las piezas que trae el juego tienen forma de distintos polígonos regulares y la medida de los lados es la misma en todas las piezas.`,pre:`Con algunas de esas piezas se podrían formar las siguientes tres figuras identificadas con 1, 2 y 3:`,fig:'6',ask:`De acuerdo con la información anterior, ¿cuál de las figuras formadas tiene menor perímetro?`,options:['1','2','3']},
{lead:`Miguel necesita construir una mesa de madera cuya superficie tenga forma de hexágono regular. Si él requiere que la medida de un radio del hexágono que representa esa superficie sea de 1 m, entonces, ¿cuál será el perímetro de la superficie de la mesa que Miguel requiere construir?`,options:['3 m','6 m','12 m']},
{lead:`La siguiente representación gráfica, cuyas unidades están en metros, muestra el polígono ABCD que representa la superficie de una ventana de una casa:`,fig:'8',ask:`De acuerdo con la información anterior, si se requiere colocar un vidrio en la totalidad de la superficie de esa ventana, entonces, ¿cuántos metros cuadrados de ese vidrio se requieren colocar?`,options:['56','28','18']},
{lead:`Un rótulo publicitario tiene forma de octágono regular, cuya medida de uno de sus lados es 3 m. Si a partir de una lámina metálica se necesita construir otro rótulo publicitario, con forma de cuadrado y con el mismo perímetro que el del rótulo octagonal, entonces, ¿cuántos metros cuadrados de lámina metálica, como mínimo, se necesitarían para construir ese rótulo cuadrado?`,options:['12','24','36']},
{lead:`La siguiente representación gráfica, cuyas unidades están en metros, muestra la figura ABCDE correspondiente a la superficie de una zona verde en una casa:`,fig:'10',ask:`De acuerdo con la información anterior, si se requiere colocar zacate a la totalidad de la superficie de esa zona, entonces la cantidad de metros cuadrados de zacate que se requieren colocar es mayor que`,options:['20 y menor que 27.','27 y menor que 34.','34 y menor que 41.']},
{lead:`En una fábrica de alimentos, un trozo de queso con forma de cilindro circular recto será dividido en dos pedazos para su empaque. Para ello, una máquina realiza un corte plano, a ese cilindro, que pasa por el centro de cada una de sus bases. La sección plana que se obtuvo en cada uno de los pedazos, producto del corte realizado a ese trozo de queso, corresponde a`,options:['una elipse.','un rectángulo.','una circunferencia.']},
{lead:`Un recipiente para almacenar confites se fabrica a partir de una esfera de vidrio. Para formar ese recipiente a la esfera se le realizan dos cortes para obtener dos secciones planas, paralelas y del mismo tamaño, que representan la base y la abertura del recipiente. La medida del radio de esa esfera es 13 cm. Además, cuando se realizan los cortes, la distancia entre los centros de esas secciones es 24 cm. La siguiente figura muestra ese recipiente:`,fig:'12',ask:`De acuerdo con la información anterior, ¿cuál es la medida del radio de la abertura del recipiente?`,options:['5 cm','10 cm','11 cm']},
{lead:`¿Cuál fue el volumen, en millones de metros cúbicos, contenido en el embalse en el día 10 desde el inicio de ese estudio?`,options:['30','50','60']},
{lead:`Durante todo ese tiempo, ¿en cuántas ocasiones el volumen de ese embalse fue igual a veinte millones de metros cúbicos?`,options:['Ninguna ocasión.','Dos ocasiones.','Una ocasión.']},
{lead:`¿Cuál opción muestra un intervalo dónde v es creciente?`,options:['[5, 10]','[20, 40]','[50, 60]']},
{lead:`Considere la siguiente información:`,pre:`La función c, que determina la cantidad diaria “c(x)”, en fanegas, de café recolectado en una finca durante una cosecha, está dada por c(x) = 0,8x + 2, donde “x” representa el tiempo, en días, transcurrido desde que comenzó esa cosecha, con 1 ≤ x ≤ 12.`,ask:`De acuerdo con la información anterior, si en un día se recolectó un total de seis fanegas de café, entonces, ¿cuántos días transcurrieron desde que comenzó esa cosecha?`,options:['5','6','7']},
{lead:`Una empresa quiere construir adornos con forma esférica cuya área “a” de su superficie, en centímetros cuadrados, está dada por a(r) = 4πr<sup>2</sup> donde “r” representa la medida del radio, en centímetros, de cada uno de los adornos. Si se necesita conocer la medida del radio de cada uno de los adornos para acomodarlos en cajas, entonces la medida del radio en función del área corresponde a`,options:[m(mi('r')+mo('(')+mi('a')+mo(')')+mo('=')+frac(root(mi('a')),num(4)+mi('π'))),m(mi('r')+mo('(')+mi('a')+mo(')')+mo('=')+root(frac(mi('a'),num(4)+mi('π')))),m(mi('r')+mo('(')+mi('a')+mo(')')+mo('=')+root(mi('a')+mo('−')+num(4)+mi('π')))]},
{lead:`Considere la siguiente información:`,pre:`La función m, la cual determina la cantidad de datos “m(k)”, en megabytes, procesados por una red informática, está dada por m(k) = 2<sup>k</sup>, donde “k” representa el tiempo en minutos transcurridos desde que esa red comenzó a procesar datos, con 1 ≤ k ≤ 10.`,ask:`De acuerdo con la información anterior, si se requiere determinar el criterio de la función k, la cual corresponde a la función inversa de m, entonces, ¿cuál opción muestra ese criterio?`,options:['k(m) = log<sub>2</sub>(m)','k(m) = log<sub>m</sub>(2)',m(mi('k')+mo('(')+mi('m')+mo(')')+mo('=')+'<msub><mi>log</mi>'+frac(num(1),num(2))+'</msub>'+mo('(')+mi('m')+mo(')'))]},
{lead:`La siguiente representación gráfica corresponde a la función f, que determina el monto total “y”, en miles de colones, por el alquiler de una bicicleta, en función del tiempo “x”, en horas transcurridas desde el inicio de su alquiler, con 0 ≤ x ≤ 6:`,fig:'19',ask:`De acuerdo con la información anterior, la representación gráfica de f<sup>−1</sup> corresponde a`,options:['<span data-fig="19A"></span>','<span data-fig="19B"></span>','<span data-fig="19C"></span>']},
{lead:`La siguiente representación gráfica corresponde a la función r, que determina la rapidez “r(t)”, en kilómetros por hora, de un camión de transportes durante una entrega de paquetes, en función del tiempo “t”, en horas transcurridas desde la salida de ese camión del centro de distribución, con 0 &lt; t ≤ 13:`,fig:'20',ask:`De acuerdo con la información anterior, si para registrar con precisión el tiempo en función de la rapidez se requiere determinar un posible intervalo del dominio de r tal que esta función tenga inversa, entonces, ¿cuál opción corresponde a ese posible intervalo?`,options:['[1, 6]','[3, 8]','[6, 9]']},
{lead:`Considere la siguiente información:`,pre:`Bajo ciertas condiciones se establece que la función m, la cual determina la cantidad diaria de calcio “m(t)”, en miligramos, que absorbe desde el suelo una planta, está dada por m(t) = ${m(num(4)+root(mi('t')+mo('−')+num(1))+mo('+')+num(20))}, donde “t” representa el tiempo, en días, desde que inició un tratamiento especial, con 1 ≤ t ≤ 37.`,ask:`De acuerdo con la información anterior, ¿cuál fue la cantidad de calcio, en miligramos, que absorbió esa planta en el día 17 desde que inició el tratamiento?`,options:['96','36','24']},
{lead:`La siguiente representación gráfica corresponde a la función c, la cual determina la cantidad de agua “c(x)”, en centenas de litros, contenida en un tanque, en función del tiempo “x” en horas transcurridas a partir de una observación, con 2 &lt; x ≤ 18:`,fig:'22',ask:`De acuerdo con la información anterior, si c involucra a la función raíz cuadrada, entonces, ¿cuál opción corresponde al criterio de c?`,options:[m(mi('c')+mo('(')+mi('x')+mo(')')+mo('=')+root(num(2)+mi('x'))),m(mi('c')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')+mo('−')+num(2))),m(mi('c')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')+mo('+')+num(2)))]},
{lead:`Considere la siguiente información:`,pre:`La función q, la cual determina la cantidad “q(t)” de libros vendidos diariamente en una librería, está dada por q(t) = −t<sup>2</sup> + 4t + 10, donde “t” representa el tiempo, en días, desde el inicio de las ventas, con 0 &lt; t ≤ 5.`,ask:`De acuerdo con la información anterior, ¿cuál fue la cantidad de libros vendidos en esa librería en el día cuatro desde el inicio de las ventas?`,options:['5','10','42']},
{lead:`Considere la siguiente información:`,pre:`El número total de estudiantes de un colegio está linealmente relacionado con el número de aulas disponibles. Si en el colegio hay 10 aulas disponibles, entonces el número total de estudiantes es 250. Además, si en el colegio hay 15 aulas disponibles, entonces el número total de estudiantes es 350.`,ask:`De acuerdo con la información anterior, ¿cuál es la ecuación de la recta que representa el número total de estudiantes “y” de ese colegio, en función del número de aulas “x” que tiene disponibles?`,options:['y = 20 + 50x','y = 50 + 20x','y = 70x']},
{lead:`Considere la siguiente información:`,pre:`La función m, la cual determina la cantidad “m(t)” de mensajes de texto que una persona envió diariamente desde su teléfono celular, está dada por m(t) = 3 · 2<sup>t</sup>, donde “t” representa el tiempo, en días, desde el inicio de un mes, con 1 ≤ t ≤ 7.`,ask:`De acuerdo con la información anterior, ¿cuántos mensajes de texto envió esa persona en el día seis desde el inicio de ese mes?`,options:['1','36','192']},
{lead:`Considere la siguiente información:`,pre:`La función r, que determina el nivel de intensidad del sonido “r(x)”, en decibeles, percibido en una fábrica, está dada por r(x) = 16 · log<sub>2</sub>(x), donde “x” representa el número de máquinas que están encendidas en esa fábrica, con 4 ≤ x ≤ 64.`,ask:`De acuerdo con la información anterior, ¿cuál es el nivel de intensidad del sonido, en decibelios, percibido en esa fábrica si hay 16 máquinas encendidas?`,options:['2','64','128']},
{lead:`La siguiente representación gráfica corresponde a la función cuadrática h, la cual determina la altura “h(x)”, en metros sobre el nivel del mar, que alcanzó un delfín al saltar sobre el agua, en función del tiempo “x”, en segundos, luego de haber iniciado ese salto, con 0 &lt; x ≤ 6:`,fig:'27',ask:`De acuerdo con la información anterior, durante todo ese tiempo, ¿a los cuántos segundos el delfín alcanzó la mayor altura sobre el nivel del mar?`,options:['A los 3 s','A los 6 s','A los 9 s']},
{lead:`La función p, que determina la profundidad “p(x)”, en metros desde la superficie de un terreno, de una excavación, está dada por p(x) = 1,5x + 2, donde “x” representa el tiempo, en días, desde el momento en que se inició la excavación, con 0 &lt; x ≤ 4.`,ask:`De acuerdo con la información anterior, ¿cuál es la representación gráfica de p?`,options:['<span data-fig="28A"></span>','<span data-fig="28B"></span>','<span data-fig="28C"></span>']},
{lead:`Considere la siguiente información:`,pre:`La función u, que determina la cantidad de levaduras “u(x)”, en miles, que había en un recipiente de un laboratorio, está dada por u(x) = (1,1)<sup>x</sup>, donde “x” representa el tiempo, en días, desde el inicio de un estudio, con 0 ≤ x ≤ 7.`,ask:`De acuerdo con la información anterior, conforme aumentó el tiempo, desde el inicio de ese estudio, la cantidad de levaduras que había en ese recipiente fue`,options:['disminuyendo.','aumentando.','constante.']},
{lead:`Considere la siguiente información:`,pre:`La función n, que determina la cantidad de usuarios “n(t)”, que acceden diariamente a una plataforma en línea, está dada por n(t) = 9 · log<sub>3</sub>(t), donde “t” representa el tiempo, en días transcurridos desde que esa plataforma fue lanzada, con 3 ≤ t ≤ 81.`,ask:`De acuerdo con la información anterior, si en un día accedieron 18 usuarios a la plataforma, entonces, ¿cuántos días transcurrieron desde que esa plataforma fue lanzada?`,options:['6','9','24']},
{lead:`Considere la siguiente información:`,pre:`En una empresa se fabrican únicamente bloques de concreto de dos tipos: rectangulares y cilíndricos. Cada bloque rectangular de concreto se fabrica con cuatro bolsas de cemento y dos sacos de arena. Asimismo, cada bloque cilíndrico de concreto se fabrica con tres bolsas de cemento y dos sacos de arena.`,ask:`De acuerdo con la información anterior, si para la fabricación de bloques rectangulares y cilíndricos se utilizaron 90 bolsas de cemento y 52 sacos de arena, entonces, ¿cuántos bloques cilíndricos de concreto se fabricaron en total en esa empresa?`,options:['13','14','38']},
{lead:`Considere la siguiente información:`,pre:`Laura e Isabel fueron a una feria artesanal a comprar collares y pulseras. Laura compró dos collares y tres pulseras, por los cuales pagó ₡25 565. Isabel compró tres collares y una pulsera, por los cuales pagó ₡23 385. Si cada collar tenía el mismo precio y cada pulsera tenía el mismo precio, entonces; ¿cuál fue el precio que tenía cada collar?`,options:['₡7616','₡6370','₡5113']},
{lead:`La siguiente tabla muestra la función f, que determina la cantidad diaria “f(x)” de libros vendidos por una editorial durante una campaña promocional, en función del tiempo “x”, en días, desde el inicio de la campaña, con 1 ≤ x ≤ 5:`,pre:tableHTML([['x','1','2','3','4','5'],['f(x)','20','45','75','110','150']],true),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar f?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`La siguiente tabla muestra la función b, que determina la cantidad diaria “b(x)” de botellas de agua vendidas en una tienda, en función del tiempo “x”, en días, desde el inicio de un mes, con 1 ≤ x ≤ 5:`,pre:tableHTML([['x','1','2','3','4','5'],['b(x)','30','60','90','120','150']],true),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar b?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`La siguiente representación gráfica corresponde a la función h, la cual determina la altura “h(x)”, en metros, de un árbol de cierta especie, en función del tiempo “x” en años transcurridos desde el momento que ese árbol fue plantado, con 1 ≤ x ≤ 8:`,fig:'35',ask:`De acuerdo con la información anterior, ¿cuál opción corresponde a un tipo de función involucrada en el modelo matemático que se adapta mejor para representar a h?`,options:['Función lineal.','Función logarítmica.','Función exponencial.']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondiente al tiempo, en minutos, que una persona pasa diariamente conectada a internet, durante un mes. Además, se muestra el promedio de esos datos:`,fig:'36',ask:`De acuerdo con la información anterior, la mediana de esos tiempos es`,options:['mayor que 175 min.','menor que 175 min.','igual que 175 min.']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondiente a las alturas, en metros, de un grupo de árboles que hay en una reserva natural. Además, se muestran, en metros, los valores 9 y 11 que representan, respectivamente, la mediana y la moda de esos datos:`,fig:'37',ask:`De acuerdo con la información anterior, si la moda de esos datos es única, entonces el promedio de las alturas de esos árboles`,options:['es menor que 9 m.','es mayor que 11 m.','está entre 9 m y 11 m.']},
{lead:`Al menos la mitad de esas personas estudiantes recorrió una distancia menor o igual que`,options:['1800 m','2150 m','2200 m']},
{lead:`¿Cuál fue la distancia recorrida con mayor frecuencia por esas personas estudiantes durante la caminata?`,options:['2000 m','2500 m','2800 m']},
{lead:`La siguiente tabla muestra la distribución de frecuencias correspondiente a la cantidad de horas extra que trabajó cada una de las personas que laboran en una empresa, durante un mes:`,pre:tableHTML([['Cantidad de horas extra','Cantidad de personas'],['De 0 a menos de 10','8'],['De 10 a menos de 20','12'],['De 20 a 30','5'],['Total','25']],true),ask:`De acuerdo con la información anterior, ¿cuál es el promedio de la cantidad de horas extras que trabajaron esas personas durante el mes?`,options:['13,8','12,0','8,3']}
];
const SHARED={
13:{lead:`Para responder los ítems 13, 14 y 15, considere la siguiente información:`,pre:`La siguiente representación gráfica corresponde a la función v que determina el volumen “v(x)”, en millones de metros cúbicos, contenido en el embalse de una represa hidroeléctrica, en función del tiempo “x”, en días, desde el inicio de un estudio científico, con 0 &lt; x ≤ 60:`,fig:'13'},
38:{lead:`Para responder los ítems 38 y 39, considere la siguiente información:`,pre:`En la siguiente tabla se presentan algunas medidas de posición referentes a las distancias, en metros, recorridas por las personas estudiantes de un colegio durante una caminata ecológica organizada como parte de una actividad recreativa:${tableHTML([['Medida de posición','Valor'],['Mínimo','1200'],['Máximo','2800'],['Moda','2000'],['Mediana','2200'],['Promedio','2150'],['Primer Cuartil','1800'],['Tercer Cuartil','2500']],true)}`}
};
if(QUESTIONS.length!==40||QUESTIONS.some(q=>q.options.length!==3))throw Error('Transcripción incompleta.');
