// Soluciones calculadas a partir de los datos y las gráficas del cuadernillo original.
const ANSWER_KEY=['C','A','A','B','C','A','B','B','C','B','B','A','B','C','A','A','B','A','B','C','B','B','B','B','C','B','A','B','B','B','B','B','B','A','B','B','A','C','A','A'].join('');
const SOLUTIONS=[
`El centro es M(6, 5) y el radio es 4 m. Por tanto, la ecuación es (x − 6)<sup>2</sup> + (y − 5)<sup>2</sup> = 4<sup>2</sup> = 16.`,
`El centro debe ser T(15, 20) y el radio debe medir 10 m. En A, el punto superior (15, 30) está a 10 m del centro.`,
`El centro cambia de (2, 2) a (2 − 3, 2 − 1) = (−1, 1). El radio permanece en 1 km. La ecuación es (x + 1)<sup>2</sup> + (y − 1)<sup>2</sup> = 1.`,
`La recta que une los postes (5, 2) y (−1, −4) es y = x − 3. El centro de la circunferencia es (2, −1), que pertenece a esa recta. Una recta que pasa por el centro corta la circunferencia en dos puntos: es secante.`,
`El centro es O(6, 4) y el radio es 2. R(6, 1) y S(9, 4) están a 3 unidades del centro, fuera de la diana. T(6, 5) está a 1 unidad del centro, dentro.`,
`Si cada lado mide L, la figura 1 tiene 8 lados en su borde, la figura 2 tiene 9 y la figura 3 tiene 9. El menor perímetro es el de la figura 1: 8L.`,
`En un hexágono regular, el lado mide lo mismo que el radio. Como el radio mide 1 m, el perímetro es 6 · 1 = 6 m.`,
`La diagonal AC divide la ventana en dos triángulos. AC mide 10 − 2 = 8 m. Las alturas correspondientes son 9 − 4 = 5 m y 4 − 2 = 2 m. El área es ${m(frac(num(8)+mo('·')+num(5),num(2))+mo('+')+frac(num(8)+mo('·')+num(2),num(2))+mo('=')+num(28))} m<sup>2</sup>.`,
`El perímetro del octágono es 8 · 3 = 24 m. El cuadrado de igual perímetro tiene lado 24 ÷ 4 = 6 m y área 6<sup>2</sup> = 36 m<sup>2</sup>.`,
`El rectángulo ABCD mide 6 m por 6 m y tiene área 36 m<sup>2</sup>. Al estimar en la gráfica la región que se recorta entre AD y la curva AED, se obtienen aproximadamente 7 m<sup>2</sup>. La zona verde tiene un área aproximada de 29 m<sup>2</sup>, mayor que 27 y menor que 34.`,
`El plano que pasa por los centros de las dos bases corta longitudinalmente al cilindro. La sección resultante es un rectángulo.`,
`Las secciones son iguales, por lo que cada plano de corte está a 24 ÷ 2 = 12 cm del centro de la esfera. Por Pitágoras, el radio de la abertura es ${m(mi('r')+mo('=')+root('<msup><mn>13</mn><mn>2</mn></msup>'+mo('−')+'<msup><mn>12</mn><mn>2</mn></msup>')+mo('=')+root(num(25))+mo('=')+num(5))} cm.`,
`En el día 10, el punto de la gráfica indica un volumen de 50 millones de metros cúbicos.`,
`El punto inicial (0, 20) es abierto y no pertenece al dominio. La gráfica alcanza 20 millones de metros cúbicos una sola vez, en el tramo descendente entre los días 50 y 60.`,
`La función aumenta entre los días 0 y 10. El intervalo [5, 10] está dentro de ese tramo creciente.`,
`Se despeja x en 6 = 0,8x + 2: 4 = 0,8x y x = 5. Transcurrieron cinco días.`,
`De a = 4πr<sup>2</sup>, se obtiene ${m(frac(mi('a'),num(4)+mi('π'))+mo('=')+'<msup><mi>r</mi><mn>2</mn></msup>')}. Como el radio es positivo, ${m(mi('r')+mo('=')+root(frac(mi('a'),num(4)+mi('π'))))}.`,
`La inversa de la función exponencial de base 2 es el logaritmo de base 2. De m = 2<sup>k</sup> se obtiene k(m) = log<sub>2</sub>(m).`,
`La gráfica original va de (0, 3) a (6, 9). La inversa intercambia las coordenadas y va de (3, 0) a (9, 6). Esto corresponde a B.`,
`Una función tiene inversa si es uno a uno en el intervalo elegido. En [6, 9], la rapidez disminuye estrictamente. Los otros intervalos incluyen parte de un tramo horizontal, donde se repite la misma rapidez.`,
`m(17) = ${m(num(4)+root(num(17)+mo('−')+num(1))+mo('+')+num(20)+mo('=')+num(4)+root(num(16))+mo('+')+num(20)+mo('=')+num(36))} miligramos.`,
`La gráfica pasa por (6, 2), (11, 3) y (18, 4), y su extremo abierto es (2, 0). Estos datos cumplen ${m(mi('c')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')+mo('−')+num(2)))}.`,
`q(4) = −4<sup>2</sup> + 4 · 4 + 10 = −16 + 16 + 10 = 10 libros.`,
`La pendiente es ${m(frac(num(350)+mo('−')+num(250),num(15)+mo('−')+num(10))+mo('=')+num(20))}. De 250 = 20 · 10 + b, se obtiene b = 50. La ecuación es y = 50 + 20x.`,
`m(6) = 3 · 2<sup>6</sup> = 3 · 64 = 192 mensajes.`,
`r(16) = 16 · log<sub>2</sub>(16) = 16 · 4 = 64 decibeles.`,
`La mayor altura se alcanza en el vértice de la parábola, que está en (3, 9). Por tanto, ocurre a los 3 segundos.`,
`La función se aproxima a 2 cuando x se aproxima a 0 y cumple p(4) = 8. Como 0 &lt; x ≤ 4, el extremo (0, 2) es abierto y el extremo (4, 8) es cerrado. Esa gráfica es B.`,
`La base 1,1 es mayor que 1, por lo que la función exponencial (1,1)<sup>x</sup> aumenta conforme aumenta x.`,
`18 = 9 · log<sub>3</sub>(t) implica log<sub>3</sub>(t) = 2. Por tanto, t = 3<sup>2</sup> = 9 días.`,
`Si r es la cantidad de bloques rectangulares y c la de cilíndricos, entonces 4r + 3c = 90 y 2r + 2c = 52. La segunda ecuación da r + c = 26. Sustituyendo r = 26 − c en la primera, se obtiene 104 − c = 90, de donde c = 14.`,
`Si c es el precio del collar y p el de la pulsera, entonces 2c + 3p = 25 565 y 3c + p = 23 385. Al triplicar la segunda y restar la primera: 7c = 44 590. Por tanto, cada collar costó ₡6370.`,
`Las primeras diferencias son 25, 30, 35 y 40. Las segundas diferencias son constantes e iguales a 5, por lo que el modelo es cuadrático.`,
`La cantidad vendida aumenta 30 botellas cada día. Una tasa constante corresponde a una función lineal.`,
`Los puntos (1, 2), (2, 3), (4, 4) y (8, 5) se ajustan a h(x) = log<sub>2</sub>(x) + 2. El modelo involucra una función logarítmica.`,
`La distribución tiene una cola hacia la derecha. En esta asimetría, el promedio está a la derecha de la mediana. Por ello, la mediana es menor que 175 min.`,
`La distribución tiene una cola hacia la izquierda. En esta asimetría, el promedio es menor que la mediana. Como la mediana es 9 m, el promedio es menor que 9 m.`,
`La mediana es 2200 m: al menos la mitad de los datos son menores o iguales que ese valor.`,
`La moda es el dato de mayor frecuencia. La tabla indica una moda de 2000 m.`,
`Los puntos medios de los intervalos son 5, 15 y 25 horas. El promedio agrupado es ${m(frac(num(5)+mo('·')+num(8)+mo('+')+num(15)+mo('·')+num(12)+mo('+')+num(25)+mo('·')+num(5),num(25))+mo('=')+frac(num(345),num(25))+mo('=')+num('13,8'))} horas.`
];
if(ANSWER_KEY.length!==40||SOLUTIONS.length!==40)throw Error('Clave o soluciones incompletas.');
