const ANSWER_KEY='A C C B A C B B C B B A C B B B C A B A B C C B B B B C A C A A C C C'.replace(/\s/g,'');
const SOLUTIONS=[
`El centro es (12, 18) y el radio es 6 m. La ecuación es (x − 12)<sup>2</sup> + (y − 18)<sup>2</sup> = 36.`,
`El centro (−30, 20) se ubica a la izquierda del eje y y por encima del eje x. La gráfica C muestra ese centro y un radio de 10 m.`,
`El centro se traslada de (3, 2) a (3 + 2, 2 + 1) = (5, 3). El radio continúa siendo 1 m. La ecuación es (x − 5)<sup>2</sup> + (y − 3)<sup>2</sup> = 1.`,
`El centro es (75, 60) y el radio es 45 cm. Para (70, 80), la distancia al centro es ${m(root('<msup><mn>5</mn><mn>2</mn></msup>'+mo('+')+'<msup><mn>20</mn><mn>2</mn></msup>')+mo('≈')+num('20,62'))} cm, menor que 45. Los otros puntos están fuera.`,
`P = (48, 30) y R = (24, 20). La distancia es ${m(root('<msup><mn>24</mn><mn>2</mn></msup>'+mo('+')+'<msup><mn>10</mn><mn>2</mn></msup>')+mo('=')+root(num(676))+mo('=')+num(26))} m.`,
`Cada cuadrado tiene área 4<sup>2</sup> = 16 m<sup>2</sup>. El hexágono regular tiene área ${m(frac(num(3)+root(num(3)),num(2))+mo('·')+num(16)+mo('=')+num(24)+root(num(3)))}. El área total es ${m(num(32)+mo('+')+num(24)+root(num(3)))} m<sup>2</sup>.`,
`El lado del cuadrado mide ${m(root(num(324))+mo('=')+num(18))} cm. El perímetro del hexágono es 6 · 18 = 108 cm.`,
`El polígono ocupa 10 cuadrados de la cuadrícula. Cada cuadrado tiene área 1 m<sup>2</sup>, por lo que se requieren 10 m<sup>2</sup> de cerámica.`,
`El borde inferior mide 6 m, el derecho 3 m y el tramo horizontal superior 2 m. Sumando las longitudes de los dos tramos curvos de la gráfica se obtiene un perímetro aproximado de 16,4 m, mayor que 15 y menor que 18.`,
`El corte longitudinal perpendicular a las bases y que pasa por sus centros produce una sección rectangular.`,
`El radio de la base es ${m(root('<msup><mn>29</mn><mn>2</mn></msup>'+mo('−')+'<msup><mn>20</mn><mn>2</mn></msup>')+mo('=')+root(num(441))+mo('=')+num(21))} cm. El diámetro es 2 · 21 = 42 cm.`,
`A las 9 h, la gráfica cruza el eje horizontal. La temperatura es 0 °C.`,
`La menor temperatura es −6 °C y se alcanza a las 12 h.`,
`p(20) = 100 + 40 · 20<sup>3</sup> = 100 + 320 000 = 320 100 partículas.`,
`p = 50(t + 4) = 50t + 200. Despejando, ${m(mi('t')+mo('=')+frac(mi('p')+mo('−')+num(200),num(50)))}.`,
`La función c une (2, 4) y (10, 20). Su inversa intercambia las coordenadas: une (4, 2) y (20, 10), como muestra B.`,
`De w = 2s + 60 se obtiene ${m(mi('s')+mo('=')+frac(mi('w')+mo('−')+num(60),num(2)))}.`,
`k = 25m<sup>2</sup> + 5000. Al despejar el área positiva, ${m(mi('m')+mo('=')+root(frac(mi('k')+mo('−')+num(5000),num(25))))}.`,
`f(34) = ${m(num('0,9')+root(num(34)+mo('+')+num(30))+mo('+')+num(70)+mo('=')+num('0,9')+mo('·')+num(8)+mo('+')+num(70)+mo('=')+num('77,2'))} pulsaciones por minuto.`,
`La pendiente es ${m(frac(num(588000)+mo('−')+num(555000),num(16)+mo('−')+num(10))+mo('=')+num(5500))}. El salario fijo es 555 000 − 5500 · 10 = 500 000. La ecuación es y = 5500x + 500 000.`,
`La parábola abre hacia abajo. Su máximo está en ${m(mi('t')+mo('=')+frac(mo('−')+num(20),num(2)+mo('·')+mo('(')+mo('−')+num(1)+mo(')'))+mo('=')+num(10))} años.`,
`w(3) = 3<sup>3</sup> = 27 computadoras.`,
`La gráfica pasa por (3, 1), (9, 2) y (27, 3). Estos puntos cumplen h(x) = log<sub>3</sub>(x).`,
`El costo variable es 50x y el fijo 5000. El costo total es y = 50x + 5000.`,
`w(5) = 9 · 5 − 5<sup>2</sup> = 45 − 25 = 20,0 min.`,
`v(3) = 2 · (1,2)<sup>3</sup> = 3,456, aproximadamente 3,46 m/s.`,
`n(81) = 27 · log<sub>3</sub>(81) = 27 · 4 = 108 empleados.`,
`Si s es la cantidad de sillas y m la de mesas: 3s + 5m = 125 y s + 2m = 45. Al triplicar la segunda ecuación y restar la primera, m = 10. Entonces s = 45 − 20 = 25 sillas.`,
`Si b es el precio de un balón y g el de un par de guantes: 2b + 3g = 66 000 y 4b + 2g = 64 000. Al triplicar la segunda ecuación y restar dos veces la primera, 8b = 60 000. Cada balón costó ₡7500.`,
`La cantidad de medicamento se reduce a la mitad cada hora: 32, 16, 8 y 4. Una razón constante corresponde a una función exponencial.`,
`Las diferencias entre valores consecutivos son constantes e iguales a 34. El modelo es lineal.`,
`La distribución tiene una cola hacia la izquierda. Su promedio es menor que la mediana de 9 h.`,
`El tercer cuartil es 100 km. Al menos el 75 % de las personas ciclistas recorrió una distancia menor o igual que ese valor.`,
`La distancia mínima es 25 km. Por tanto, es imposible que una persona haya recorrido 20 km.`,
`La nota ponderada es 0,45 · 95 + 0,30 · 85 + 0,25 · 80 = 42,75 + 25,5 + 20 = 88,25.`
];
if(ANSWER_KEY.length!==35||SOLUTIONS.length!==35)throw Error('Clave o soluciones incompletas.');
