// Transcripción manual cotejada con la prueba sumativa 2024-D01.
const m=body=>`<math xmlns="http://www.w3.org/1998/Math/MathML" displaystyle="true">${body}</math>`;
const root=body=>`<msqrt><mrow>${body}</mrow></msqrt>`;
const frac=(a,b)=>`<mfrac><mrow>${a}</mrow><mrow>${b}</mrow></mfrac>`;
const num=n=>`<mn>${n}</mn>`,mi=x=>`<mi>${x}</mi>`,mo=x=>`<mo>${x}</mo>`;
const tableHTML=(rows,open=false)=>`<div class="table-wrap"><table class="exam-table${open?' open-table':''}">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'}>${c}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table></div>`;
const QUESTIONS=[
{lead:`El terreno de un corral para caballos tiene forma circular, cuyo centro está ubicado a 12 m al este y 18 m al norte de la entrada a una propiedad. La medida del radio de la circunferencia, que representa el borde de ese terreno, es 6 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones, Q del centro del terreno del corral y P de la entrada a esa propiedad, así como la ubicación de la circunferencia correspondiente al borde de ese terreno:`,fig:'1',ask:`De acuerdo con la información anterior, ¿cuál es la representación algebraica, cuyas unidades están en metros, de la circunferencia correspondiente al borde del terreno de ese corral?`,options:['(x − 12)<sup>2</sup> + (y − 18)<sup>2</sup> = 36','(x + 12)<sup>2</sup> + (y − 18)<sup>2</sup> = 12','(x + 12)<sup>2</sup> + (y + 18)<sup>2</sup> = 6']},
{lead:`En un complejo deportivo se estableció sobre el suelo una zona de seguridad, con forma circular, cuyo centro M está ubicado en el punto correspondiente a (−30, 20) con respecto a la ubicación E de una estatua. Además, la medida del radio de la circunferencia que representa el borde de la zona es 10 m. ¿Cuál de las siguientes representaciones gráficas, cuyas unidades están en metros, corresponde a la ubicación de la circunferencia que representa el borde de esa zona de seguridad?`,options:['<span data-fig="2A"></span>','<span data-fig="2B"></span>','<span data-fig="2C"></span>']},
{lead:`En un laboratorio científico, la base de una lámpara se ubica 2 m al norte y 3 m al este de la entrada de ese laboratorio. Además, la lámpara ilumina una zona circular en el piso cuyo alcance máximo se ubica a 1 m alrededor de su base.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones, K de la base de esa lámpara y W de la entrada del laboratorio, así como la ubicación de la circunferencia correspondiente al alcance máximo de la zona iluminada en el piso:`,fig:'3',ask:`Además, debido a un experimento científico, la base de la lámpara se traslada, desde su ubicación actual, a 2 m al este y 1 m al norte.<br><br>De acuerdo con la información anterior, ¿cuál es la representación algebraica, cuyas unidades están en metros, de la circunferencia correspondiente al alcance máximo de la zona iluminada en el piso, en la nueva ubicación de la base de esa lámpara?`,options:['(x − 1)<sup>2</sup> + (y − 3)<sup>2</sup> = 1','(x − 2)<sup>2</sup> + (y − 4)<sup>2</sup> = 1','(x − 5)<sup>2</sup> + (y − 3)<sup>2</sup> = 1']},
{lead:`En un parque hay una mesa de cemento cuya superficie es circular. La medida del diámetro, de la circunferencia que representa el borde de esa superficie, es 90 cm.`,pre:`La siguiente representación gráfica, cuyas unidades están en centímetros, muestra la circunferencia que representa el borde de la superficie de esa mesa:`,fig:'4',ask:`Además, una persona requiere colocar un vaso encima de la superficie de esa mesa.<br><br>De acuerdo con la información anterior, ¿cuál de las siguientes opciones muestra un par ordenado, cuyas unidades están en centímetros, correspondiente a un posible punto donde la persona colocó ese vaso?`,options:['(50, 115)','(70, 80)','(90, 5)']},
{lead:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones, P de un vehículo, R del centro de un terreno circular y Q de la entrada a ese terreno. Además, se muestra la recta n que representa una carretera, así como la circunferencia correspondiente al borde de ese terreno:`,fig:'5',ask:`De acuerdo con la información anterior, si la medida del diámetro de esa circunferencia es 20 m, entonces, ¿a qué distancia está el vehículo del centro de ese terreno?`,options:['26,00 m','49,03 m','52,00 m']},
{lead:`La siguiente figura representa una superficie lateral (cara) de una columna de una iglesia, la cual está formada por un hexágono regular y dos cuadrados congruentes entre sí:`,fig:'6',ask:`De acuerdo con la información anterior, si se requiere pintar la totalidad de esa cara de la columna, entonces, ¿cuántos metros cuadrados se requieren pintar?`,options:[m(num(56)+root(num(3))),m(num(16)+mo('+')+num(24)+root(num(3))),m(num(32)+mo('+')+num(24)+root(num(3)))]},
{lead:`El área de un rótulo cuadrado es 324 cm<sup>2</sup>. Si se quiere construir otro rótulo, con forma de hexágono regular, cuyo lado tenga la misma medida que el lado del rótulo cuadrado, entonces, ¿cuál será la medida del perímetro del rótulo hexagonal que se quiere construir?`,options:['72 cm','108 cm','842 cm']},
{lead:`La siguiente representación gráfica muestra la forma que tiene el piso del balcón de una casa:`,fig:'8',ask:`De acuerdo con la información anterior, si se requiere colocar cerámica a la totalidad del piso de ese balcón, entonces, ¿cuántos metros cuadrados de cerámica se requieren colocar?`,options:['6','10','16']},
{lead:`La siguiente representación gráfica muestra una superficie lateral (cara) de un muro:`,fig:'9',ask:`De acuerdo con la información anterior, si se requiere colocar un alambre decorativo en la totalidad del borde de esa cara del muro, entonces la cantidad mínima de metros de alambre que se requiere colocar es mayor que`,options:['11 y menor que 13.','13 y menor que 15.','15 y menor que 18.']},
{lead:`Una barra de jabón, con forma de cilindro circular recto, se utilizó para elaborar un par de figuras decorativas. Para ello se realizó a la barra de jabón un corte perpendicular a sus bases y que pasa por el centro de estas. La sección plana que se obtuvo en cada figura decorativa, producto del corte realizado a esa barra de jabón, corresponde a`,options:['una elipse.','un rectángulo.','una circunferencia.']},
{lead:`Un adorno de jardín se fabrica a partir de una esfera de cemento, a la cual se le realiza un corte para obtener así una sección plana que representa la base del adorno. La medida del radio de esa esfera es 29 cm. Además, cuando se realiza el corte, el centro de esa base está a 20 cm del centro de la esfera. ¿Cuál es la medida del diámetro de la base de ese adorno?`,options:['18 cm','42 cm','70 cm']},
{lead:`¿Cuál fue la temperatura, que registró ese termómetro, transcurridas 9 h desde el inicio de ese día?`,options:['0 °C','12 °C','−6 °C']},
{lead:`¿A qué hora, desde el inicio de ese día, ese termómetro registró la menor temperatura?`,options:['0','3','12']},
{lead:`Considere la siguiente información:`,pre:`Para cada una de las habitaciones de una casa, la cantidad “p” de partículas de polvo que había en una de las habitaciones, está dada por p(v) = 100 + 40v<sup>3</sup>, donde “v” representa el volumen, en metros cúbicos, de esa habitación, con 15 ≤ v ≤ 30.`,ask:`De acuerdo con la información anterior, si el volumen de una habitación de esa casa es 20 m<sup>3</sup>, entonces, ¿cuál fue la cantidad de partículas de polvo que había en esa habitación?`,options:['2500','320 100','1 120 000']},
{lead:`Considere la siguiente información:`,pre:`Un economista establece que la función p, la cual determina el ingreso “p(t)” en miles de dólares que una empresa obtiene, está dada por p(t) = 50(t + 4), donde “t” representa el tiempo en meses transcurridos a partir del inicio de labores de esa empresa, con 1 ≤ t ≤ 10.`,ask:`De acuerdo con la información anterior, si el economista requiere determinar la función t la cual relaciona el tiempo “t(p)”, en meses trascurridos a partir del inicio de labores de la empresa, con el ingreso “p” en miles de dólares que esa empresa obtiene, entonces, ¿cuál es el criterio de t?`,options:['t(p) = −50t − 200',m(mi('t')+mo('(')+mi('p')+mo(')')+mo('=')+frac(mi('p')+mo('−')+num(200),num(50))),m(mi('t')+mo('(')+mi('p')+mo(')')+mo('=')+frac(mi('p')+mo('−')+num(4),num(50)))]},
{lead:`La siguiente representación gráfica corresponde a la función c que determina la altura “y” en centímetros que tiene una planta, en función del tiempo “x” en semanas transcurridas desde que esa planta fue sembrada, con 2 ≤ x ≤ 10:`,fig:'16',ask:`De acuerdo con la información anterior, la representación gráfica de c<sup>−1</sup> corresponde a`,options:['<span data-fig="16A"></span>','<span data-fig="16B"></span>','<span data-fig="16C"></span>']},
{lead:`Considere la siguiente información:`,pre:`Una nutricionista establece que la función w que determina el peso (masa) “w(s)” en kilogramos de un paciente, está dado por w(s) = 2s + 60, donde “s” representa el tiempo en semanas transcurridas desde el inicio de un plan nutricional, con 1 ≤ s ≤ 7.`,ask:`De acuerdo con la información anterior, si la nutricionista requiere determinar la función s la cual relaciona el tiempo “s(w)”, en semanas trascurridas a partir del inicio del plan nutricional, con el peso (masa) “w” en kilogramos del paciente, entonces, ¿cuál es el criterio de s?`,options:[m(mi('s')+mo('(')+mi('w')+mo(')')+mo('=')+frac(num(60)+mi('w'),num(2))),m(mi('s')+mo('(')+mi('w')+mo(')')+mo('=')+frac(num(60)+mo('+')+mi('w'),num(2))),m(mi('s')+mo('(')+mi('w')+mo(')')+mo('=')+frac(mi('w')+mo('−')+num(60),num(2)))]},
{lead:`Considere la siguiente información:`,pre:`La función k, la cual determina el costo “k(m)” en dólares que debe pagar una persona por la construcción de una piscina, está dada por k(m) = 25(m<sup>2</sup> + 200), donde “m” representa el área, en metros cuadrados, que debe tener esa piscina, con 24 ≤ m ≤ 40.`,ask:`De acuerdo con la información anterior, si se requiere determinar la función m que relaciona el área “m(k)”, en metros cuadrados, que debe tener la piscina, con el costo “k”, en dólares, que debe pagar la persona por la construcción de esa piscina, entonces, ¿cuál es el criterio de m?`,options:[m(mi('m')+mo('(')+mi('k')+mo(')')+mo('=')+root(frac(mi('k')+mo('−')+num(5000),num(25)))),m(mi('m')+mo('(')+mi('k')+mo(')')+mo('=')+root(frac(num(5000)+mo('−')+mi('k'),num(25)))),m(mi('m')+mo('(')+mi('k')+mo(')')+mo('=')+root(frac(mi('k')+mo('+')+num(5000),num(25))))]},
{lead:`Considere la siguiente información:`,pre:`La función f, la cual determina la frecuencia cardíaca “f(t)” en pulsaciones por minuto de una persona, está dada por ${m(mi('f')+mo('(')+mi('t')+mo(')')+mo('=')+num('0,9')+root(mi('t')+mo('+')+num(30))+mo('+')+num(70))}, donde “t” representa el tiempo en minutos que duró esa persona en ejercitarse de forma continua, con 1 ≤ t ≤ 60.`,ask:`De acuerdo con la información anterior, ¿cuál es la frecuencia cardíaca, en pulsaciones por minuto, de esa persona si se ejercitó de forma continua durante 34 min?`,options:['10,4','77,2','105,2']},
{lead:`El salario mensual en colones, que obtiene un agente de ventas, está relacionado linealmente con la cantidad de artículos vendidos por ese agente en cada mes de un año. En la siguiente tabla se muestran la cantidad de artículos vendidos y el salario mensual del agente de ventas, durante dos meses de ese año:`,pre:tableHTML([['Mes','Cantidad de artículos vendidos','Salario mensual'],['Mayo','10','₡555 000'],['Agosto','16','₡588 000']],true),ask:`De acuerdo con la información anterior, la ecuación de la recta que relaciona el salario mensual “y” obtenido por el agente de ventas, en función de la cantidad “x” de artículos vendidos por el agente en cada mes de ese año, corresponde a`,options:['y = 5500x + 500 000','y = 500 000x + 5500','y = 5500x + 610 000']},
{lead:`Considere la siguiente información:`,pre:`La cantidad “p” en miles de habitantes que tuvo una ciudad, está dada por p(t) = −t<sup>2</sup> + 20t + 50, donde “t” representa el tiempo en años transcurridos desde que esa ciudad fue fundada, con 0 &lt; t ≤ 18.`,ask:`De acuerdo con la información anterior, ¿cuántos años transcurrieron, desde su fundación, para que esa ciudad tuviera la mayor cantidad de habitantes?`,options:['9','10','18']},
{lead:`Considere la siguiente información:`,pre:`La cantidad de computadoras “w” que fueron infectadas por un virus informático propagado por medio de una red, está dada por w(x) = 3<sup>x</sup>, donde “x” representa el tiempo en minutos desde que el virus fue activado, con 0 &lt; x ≤ 5.`,ask:`De acuerdo con la información anterior, ¿cuántas computadoras fueron infectadas por ese virus en el minuto tres desde que fue activado?`,options:['1','9','27']},
{lead:`La siguiente representación gráfica corresponde a la función h, la cual determina la altura “h(x)”, en kilómetros desde el suelo, a la que vuela un águila, en función del tiempo “x” en minutos transcurridos desde el momento en que esa águila comenzó a volar, con 1 &lt; x ≤ 27:`,fig:'23',ask:`De acuerdo con la información anterior, ¿cuál de las siguientes opciones corresponde al criterio de la función h?`,options:['h(x) = 3<sup>x</sup>',m(mi('h')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')+mo('+')+num(3))),'h(x) = log<sub>3</sub>(x)']},
{lead:`Considere la siguiente información:`,pre:`El costo que una persona emprendedora paga al producir galletas es ₡50 por cada galleta. Además, esa persona debe pagar ₡5000 mensuales por costos fijos, independientemente de la cantidad de galletas producidas.`,ask:`De acuerdo con la información anterior, la ecuación de la recta que representa el costo total mensual “y” en colones que esa persona paga por producir galletas, en función de la cantidad “x” de galletas producidas corresponde a`,options:['y = 5000x + 50','y = 50x + 5000','y = 5050x']},
{lead:`Considere la siguiente información:`,pre:`El tiempo “w”, en minutos, que un grupo de insectos tardó en reaccionar a partir del contacto con un insecticida orgánico, está dado por w(x) = 9x − x<sup>2</sup>, donde “x” representa la cantidad de gramos utilizada de ese insecticida, con 0 &lt; x ≤ 8.`,ask:`De acuerdo con la información anterior, si se utilizaron 5 g de ese insecticida, entonces, ¿cuál fue el tiempo que tardó en reaccionar ese grupo de insectos, a partir del contacto con el insecticida orgánico?`,options:['8,4 min','20,0 min','35,0 min']},
{lead:`Considere la siguiente información:`,pre:`La rapidez “v” en metros por segundo de un cohete espacial, está dada por v(x) = 2 · (1,2)<sup>x</sup>, donde “x” representa el tiempo en segundos transcurridos desde que ese cohete fue lanzado, con 1 ≤ x ≤ 9.`,ask:`De acuerdo con la información anterior, ¿cuál es, aproximadamente, la rapidez de ese cohete, en metros por segundo, transcurridos 3 s desde que fue lanzado?`,options:['2,22','3,46','13,82']},
{lead:`Considere la siguiente información:`,pre:`En una empresa, la cantidad “n” de empleados que utilizan una nueva herramienta tecnológica, está dada por n(d) = 27 · log<sub>3</sub>(d), donde “d” representa el tiempo en días transcurridos desde que esa herramienta comenzó a utilizarse, con 1 &lt; d ≤ 243.`,ask:`De acuerdo con la información anterior, si desde que la nueva herramienta comenzó a utilizarse transcurrieron 81 días, entonces, ¿cuántos empleados de la empresa utilizan esa herramienta?`,options:['27','108','729']},
{lead:`Considere la siguiente información:`,pre:`En una mueblería se fabrican únicamente sillas y mesas. Cada silla requiere para su fabricación de 3 h de carpintería y 1 h de pintura. Además, cada mesa requiere para su fabricación de 5 h de carpintería y 2 h de pintura.`,ask:`De acuerdo con la información anterior, si en esa mueblería se utilizaron 125 h de carpintería y 45 h de pintura, entonces, ¿cuántas sillas se fabricaron?`,options:['15','16','25']},
{lead:`Marta compró dos balones de fútbol y tres pares de guantes de portero y pagó ₡66 000. Andrea compró cuatro balones de fútbol y dos pares de guantes de portero y pagó ₡64 000. Si cada balón de fútbol tenía el mismo precio y cada par de guantes tenía el mismo precio, entonces, ¿cuál es el precio que tenía cada balón de fútbol?`,options:['₡7500','₡8750','₡15 500']},
{lead:`La siguiente representación gráfica corresponde a la función m, la cual determina la cantidad de medicamento “m(x)”, en mililitros, que hay en la sangre de una persona, en función del tiempo “x” en horas transcurridas desde el momento que ese medicamento ingresó a la sangre de esa persona, con 0 ≤ x ≤ 3:`,fig:'30',ask:`De acuerdo con la información anterior, ¿cuál de las siguientes opciones corresponde al tipo de función que mejor se adapta para modelar la cantidad de medicamento, en mililitros, que hay en la sangre de la persona, en función del tiempo en horas transcurridas desde el momento que ese medicamento ingresó a la sangre de esa persona?`,options:['Función lineal','Función logarítmica','Función exponencial']},
{lead:`En la siguiente tabla se muestra la cantidad “c(x)” de licencias de programas informáticos vendidas por una empresa, en función del tiempo “x” en meses transcurridos desde el inicio de un año, con 1 ≤ x ≤ 5:`,pre:tableHTML([['x','1','2','3','4','5'],['c(x)','50','84','118','152','186']]),ask:`De acuerdo con la información anterior, ¿cuál de las siguientes opciones corresponde al tipo de función que mejor se adapta para modelar la cantidad de licencias de programas informáticos vendidas por la empresa, en función del tiempo “x” en meses transcurridos desde el inicio de ese año?`,options:['Función lineal','Función logarítmica','Función exponencial']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondiente a la cantidad de horas que una persona adulta durmió, cada noche, durante un año:`,fig:'32',ask:`De acuerdo con la información anterior, si 9 h corresponde a la mediana de esos datos, entonces el promedio de la cantidad de horas, que la persona durmió cada noche durante ese año, es`,options:['menor que 9 h.','mayor que 9 h.','igual que 9 h.']},
{lead:`Al menos el 75 % de las personas ciclistas de esa competencia recorrió una distancia menor o igual que`,options:['40 km.','75 km.','100 km.']},
{lead:`Con certeza, ¿cuál de las siguientes distancias es imposible que la haya recorrido una persona ciclista de esa competencia?`,options:['120 km','70 km','20 km']},
{lead:`La siguiente tabla muestra el valor porcentual en cada uno de los tres componentes que se toman en cuenta al calificar los postres presentados por las personas participantes en un concurso de cocina. Además, se muestra la calificación obtenida por componente, en una escala de 1 a 100, del postre presentado por Melissa. La nota final de ese postre corresponde a la media aritmética ponderada de todos los componentes que se toman en cuenta al calificarlo:`,pre:tableHTML([['Componente','Porcentaje','Calificación del postre de Melissa'],['Sabor','45 %','95'],['Creatividad','30 %','85'],['Presentación','25 %','80']],true),ask:`De acuerdo con la información anterior, ¿cuál es la nota final del postre presentado por Melissa en ese concurso?`,options:['85,00','86,67','88,25']}
];
const SHARED={
12:{lead:`Para responder los ítems 12 y 13, considere la siguiente información:`,pre:`La siguiente representación gráfica muestra la temperatura “t(x)” en grados Celsius, que registró un termómetro de una ciudad en un día, en función del tiempo “x” en horas transcurridas desde el inicio de ese día, con 0 ≤ x ≤ 15:`,fig:'12'},
33:{lead:`Para responder los ítems 33 y 34, considere la siguiente información:`,pre:`En la siguiente tabla se muestran algunas medidas de posición referentes a las distancias, en kilómetros, recorridas por las personas ciclistas de una competencia:${tableHTML([['Medida de posición','Valor'],['Mínimo','25'],['Máximo','130'],['Moda','50'],['Mediana','75'],['Primer Cuartil','40'],['Tercer Cuartil','100']],true)}`}
};
if(QUESTIONS.length!==35||QUESTIONS.some(q=>q.options.length!==3))throw Error('Transcripción incompleta.');
