const ANSWER_KEY='CBACCCBABABBBBBCCCCCCBBAABBBBBBBBBCCBCAB';
const SOLUTIONS=[
`El centro es (20, 24) y el radio es 6 m. La ecuación es (x − 20)<sup>2</sup> + (y − 24)<sup>2</sup> = 6<sup>2</sup> = 36.`,
`El radar M está en (12, 8) y el radio es 4 km. La opción B muestra esos valores y el punto (16, 8) sobre la circunferencia.`,
`El centro pasa de (90, 30) a (90 − 30, 30 + 20) = (60, 50). El radio sigue siendo 30 y su cuadrado es 900.`,
`La pista tiene centro (12, 9) y radio 3 m. Las distancias al centro son ${m(root(num(29)))} para W, ${m(root(num(26)))} para R y 2 para Z. Solo Z está dentro de la pista.`,
`La circunferencia tiene centro (10, 6) y radio 2 m. El sendero es x = 12; su distancia al centro es 2 m, igual al radio. Por eso es tangente.`,
`El cuadrado tiene área 4<sup>2</sup> = 16 m<sup>2</sup>. Cada hexágono aporta ${m(num(24)+root(num(3)))} m<sup>2</sup>. El área total es ${m(num(16)+mo('+')+num(48)+root(num(3)))} m<sup>2</sup>.`,
`AB = 100, BC = 40, CD = 70. Aplicando Pitágoras a AD: ${m(root(`<msup>${num(30)}${num(2)}</msup>`+mo('+')+`<msup>${num(40)}${num(2)}</msup>`))} = 50. El perímetro es 100 + 40 + 70 + 50 = 260 cm.`,
`Si cada lado mide s, los tres cuadros juntos forman un rectángulo de 3s por s, con perímetro 8s. Los dos separados tienen en total 2 · 4s = 8s. Son iguales.`,
`La figura combina el rectángulo de 40 por 40 cm con la región bajo el borde curvo. La estimación de la superficie en la representación corresponde a la opción B: mayor que 2700 y menor que 3300 cm<sup>2</sup>.`,
`El hexágono W tiene área ${m(num(150)+root(num(3)))} m<sup>2</sup>; el triángulo R tiene área ${m(num(100)+root(num(3)))} m<sup>2</sup>. Por tanto, en W se colocó más cerámica.`,
`El plano que pasa por los centros de las dos bases es un corte longitudinal del cilindro circular recto. Las secciones obtenidas son rectángulos.`,
`Por Pitágoras, el radio de la base es ${m(root(`<msup>${num(25)}${num(2)}</msup>`+mo('−')+`<msup>${num(20)}${num(2)}</msup>`))} = ${m(root(num(225)))} = 15 cm.`,
`La gráfica llega a 200 L al subir, en t = 4 h, y vuelve a cruzar ese nivel al bajar entre las 16 h y 24 h. Son dos ocasiones.`,
`Entre las 3 h y 9 h, la gráfica es creciente. La cantidad de agua va aumentando.`,
`El valor 0 no se alcanza porque los extremos son abiertos. El máximo 375 sí se alcanza. El ámbito es ]0, 375].`,
`Se sustituye p(t) en f: (f ∘ p)(t) = 2500(2t + 10) = 5000t + 25 000.`,
`La inversa intercambia las coordenadas: (1, 2) pasa a (2, 1) y (3, 4) pasa a (4, 3). Es la gráfica C.`,
`c = 20(n + 2,5). Al despejar: n(c) = ${m(frac(mi('c'),num(20))+mo('−')+frac(num(5),num(2)))}.`,
`Para que la función tenga inversa debe ser inyectiva. En [13, 23] la gráfica es estrictamente decreciente; los otros intervalos incluyen valores a ambos lados del máximo.`,
`r = 170 + 5d<sup>2</sup>. Se obtiene d<sup>2</sup> = ${m(frac(mi('r')+mo('−')+num(170),num(5)))}. Como d es positivo, d(r) = ${m(root(frac(mi('r')+mo('−')+num(170),num(5))))}.`,
`3 = 0,2 + ${m(num('0,7')+root(mi('t')+mo('+')+num(10)))}. Entonces ${m(root(mi('t')+mo('+')+num(10)))} = 4, de modo que t + 10 = 16 y t = 6 h.`,
`t(24) = ${m(num(4)+root(num(24)+mo('+')+num(1))+mo('+')+num(11))} = 4 · 5 + 11 = 31 °C.`,
`La pendiente es ${m(frac(num('721 500')+mo('−')+num('681 000'),num(18)+mo('−')+num(12)))} = 6750. El término constante es 681 000 − 6750 · 12 = 600 000. La ecuación es y = 6750x + 600 000.`,
`El punto más alto de la gráfica es (6, 138). La mayor cantidad de fruta fue 138 kg.`,
`1,62 = 2 · (0,9)<sup>t</sup>, por lo que (0,9)<sup>t</sup> = 0,81 = (0,9)<sup>2</sup>. Transcurrieron 2 años.`,
`b(32) = 4 · log<sub>2</sub>(32) = 4 · 5 = 20 bolsas.`,
`La longitud inicial es 5 cm y aumenta 4 cm por semana. La ecuación es y = 4x + 5.`,
`h(2) = −5 · 2<sup>2</sup> + 20 · 2 + 5 = −20 + 40 + 5 = 25 m.`,
`0,75 = 6 · ${m(`<msup><mrow>${mo('(')+frac(num(1),num(2))+mo(')')}</mrow>${mi('t')}</msup>`)}. Al dividir entre 6 se obtiene ${m(frac(num(1),num(8)))} = ${m(`<msup><mrow>${mo('(')+frac(num(1),num(2))+mo(')')}</mrow>${num(3)}</msup>`)}. Por tanto, t = 3 días.`,
`n(4) = 8 · log<sub>2</sub>(4) = 8 · 2 = 16.`,
`Al restar las compras, 2 kg de papas cuestan 18 943 − 17 587 = ₡1356; cada kilogramo cuesta ₡678. Luego, 5 kg de carne cuestan 17 587 − 4 · 678 = ₡14 875. Cada kilogramo de carne cuesta ₡2975.`,
`Al restar las compras, 2 kg de azúcar cuestan 19 615 − 17 919 = ₡1696; cada kilogramo cuesta ₡848. Entonces, 3 kg de café cuestan 17 919 − 3 · 848 = ₡15 375. Cada kilogramo de café cuesta ₡5125.`,
`Las diferencias sucesivas son 6, 8, 10, 12, 14 y 16. Las segundas diferencias son constantes e iguales a 2. El modelo es cuadrático.`,
`Al duplicar x, n(x) aumenta una unidad. Los datos corresponden a n(x) = log<sub>2</sub>(x), una función logarítmica.`,
`La cantidad se duplica cada día. Una razón constante entre valores sucesivos corresponde a una función exponencial.`,
`La distribución presenta una cola hacia los tiempos menores. En una distribución con asimetría a la izquierda, el promedio es menor que la mediana de 18 min.`,
`La mediana es 15 min. Al menos la mitad de los datos son menores o iguales que la mediana.`,
`El máximo indicado en la tabla es 28 min. Ese fue el mayor tiempo de entrega.`,
`El primer cuartil es 10 min. Al menos el 75 % de los datos son mayores o iguales que ese valor.`,
`La media ponderada es 0,20 · 69 + 0,35 · 78 + 0,45 · 80 = 13,80 + 27,30 + 36 = 77,10.`
];
if(ANSWER_KEY.length!==40||SOLUTIONS.length!==40)throw Error('Clave o soluciones incompletas.');
