// Transcripción del cuadernillo de ampliación de Matemática, 2025.
// Expresiones accesibles y nativas; raíces y fracciones conservan su estructura.
const m = body => `<math xmlns="http://www.w3.org/1998/Math/MathML">${body}</math>`;
const root = body => `<msqrt><mrow>${body}</mrow></msqrt>`;
const frac = (a,b) => `<mfrac><mrow>${a}</mrow><mrow>${b}</mrow></mfrac>`;
const num = n => `<mn>${n}</mn>`;
const mi = x => `<mi>${x}</mi>`;
const mo = x => `<mo>${x}</mo>`;
const tableHTML=(rows,open=false)=>`<div class="table-wrap"><table class="exam-table${open?' open-table':''}">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'}>${c}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table></div>`;
const QUESTIONS = [
{lead:`Un dispositivo mecánico se coloca en el jardín de una casa y lanza un chorro continuo de agua, cuyo alcance máximo es 6 m alrededor del dispositivo.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones K de la casa, B del dispositivo y C de la circunferencia correspondiente al alcance máximo del chorro de agua lanzado por el dispositivo:`,fig:'1',ask:`De acuerdo con la información anterior, ¿cuál es la representación algebraica de C?`,options:[`(x − 20)<sup>2</sup> + (y − 24)<sup>2</sup> = 6`,`(x + 20)<sup>2</sup> + (y + 24)<sup>2</sup> = 36`,`(x − 20)<sup>2</sup> + (y − 24)<sup>2</sup> = 36`]},
{lead:`En un aeropuerto, un radar emite una señal capaz de detectar aviones que se encuentran a una distancia menor o igual que 4 km a su alrededor. La ubicación M del radar es de 12 km al este y 8 km al norte de la ubicación D de la torre de control del aeropuerto, la cual se considera el origen de un sistema de coordenadas. ¿Cuál es la representación gráfica, cuyas unidades están en kilómetros, de la circunferencia correspondiente al alcance máximo de la señal emitida por el radar?`,options:[`<span data-fig="2A"></span>`,`<span data-fig="2B"></span>`,`<span data-fig="2C"></span>`]},
{lead:`En una cancha se colocó un parlante redondo, el cual emite un sonido cuyo alcance máximo es 30 m a su alrededor.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones R del parlante, Z de la entrada a la cancha y C de la circunferencia correspondiente al alcance máximo del sonido emitido por el parlante:`,fig:'3',ask:`Además, con el fin de lograr una mejor cobertura se decidió trasladar el parlante, desde su ubicación actual, a 20 m al norte y 30 m al oeste.<br><br>De acuerdo con la información anterior, ¿cuál es la representación algebraica de la circunferencia correspondiente al alcance máximo del sonido emitido por el parlante en la nueva ubicación?`,options:[`(x − 60)<sup>2</sup> + (y − 50)<sup>2</sup> = 900`,`(x − 60)<sup>2</sup> + (y − 10)<sup>2</sup> = 900`,`(x − 110)<sup>2</sup> + (y − 50)<sup>2</sup> = 900`]},
{lead:`Una empresa construyó una pista de baile con forma circular, cuya medida del diámetro es 6 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra la circunferencia C correspondiente al borde de la pista:`,fig:'4',ask:`Además, durante un evento bailable se colocaron tres parlantes (identificados con W, R y Z) en distintos lugares:<ul><li>W se colocó en el punto correspondiente a (10, 14).</li><li>R se colocó en el punto correspondiente a (11, 4).</li><li>Z se colocó en el punto correspondiente a (14, 9).</li></ul>De acuerdo con la información anterior, ¿cuál parlante se colocó sobre la pista de baile?`,options:['W','R','Z']},
{lead:`En un parque nacional hay un sendero, una oficina de guardaparques y un mirador. El sendero tiene forma de línea recta con dirección de norte a sur y pasa por un lugar ubicado a 12 m al este de la oficina. Además, el mirador tiene forma circular, cuya medida de su diámetro es 4 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones G de la oficina del guardaparques y C de la circunferencia correspondiente al borde del mirador:`,fig:'5',ask:`De acuerdo con la información anterior, la recta que representa el sendero es`,options:['exterior a C.','secante a C.','tangente a C.']},
{lead:`La siguiente figura representa el piso del patio de una casa, la cual está compuesta por un cuadrado y dos hexágonos regulares:`,fig:'6',ask:`De acuerdo con la información anterior, si se requiere pintar la totalidad del piso de ese patio, entonces, ¿cuántos metros cuadrados se requieren pintar?`,options:[m(num(64)+`<mspace width="0.15em"/>`+root(num(3))),m(num(16)+mo('+')+num(24)+`<mspace width="0.15em"/>`+root(num(3))),m(num(16)+mo('+')+num(48)+`<mspace width="0.15em"/>`+root(num(3)))]},
{lead:`La siguiente representación gráfica, cuyas unidades están en centímetros, muestra el cuadrilátero ABCD correspondiente a la superficie de un escritorio:`,fig:'7',ask:`De acuerdo con la información anterior, si se requiere colocar una cinta adhesiva sobre la totalidad del borde de la superficie, entonces, ¿cuántos centímetros de cinta, como mínimo, se requieren colocar?`,options:['250','260','290']},
{lead:`En una feria de arte, hay cinco cuadros del mismo tamaño y la superficie de cada uno de ellos tiene forma de cuadrado. Se juntan tres cuadros formando una figura y los otros dos cuadros se colocan separados, tal y como se muestra en la siguiente tabla:`,fig:'8',ask:`De acuerdo con la información anterior, el perímetro de la figura formada por los cuadros juntos es`,options:['igual que la suma de los perímetros de los cuadros separados.','mayor que la suma de los perímetros de los cuadros separados.','menor que la suma de los perímetros de los cuadros separados.']},
{lead:`La siguiente representación gráfica, cuyas unidades están en centímetros, muestra la figura ABCD correspondiente a la forma que tiene la ventana de un vehículo:`,fig:'9',ask:`De acuerdo con la información anterior, si se requiere colocar un vidrio en la totalidad de la ventana, entonces la cantidad de centímetros cuadrados de vidrio que se requiere colocar es mayor que`,options:['240 pero menor que 280.','2700 pero menor que 3300.','3800 pero menor que 4200.']},
{lead:`La siguiente tabla muestra dos polígonos regulares y cada uno de estos representa, el piso de una cabaña. Además, los polígonos se identifican con las letras W y R:`,fig:'10',ask:`De acuerdo con la información anterior, si una persona le colocó cerámica a la totalidad del piso de cada una de las cabañas, entonces la cantidad de metros cuadrados de cerámica colocada en W es`,options:['mayor que la colocada en R.','menor que la colocada en R.','igual que la colocada en R.']},
{lead:`Considere la siguiente información:`,pre:`Un tallo de bambú con forma de cilindro circular recto se utilizó para elaborar dos instrumentos musicales. Para ello, a ese tallo se le realizó un corte plano y que pasa por el centro de cada una de las bases.`,ask:`De acuerdo con la información anterior, las secciones planas que se obtuvieron en el tallo, producto del corte realizado, corresponden a`,options:['elipses.','rectángulos.','circunferencias.']},
{lead:`Un farol decorativo se fabricó a partir de una esfera de vidrio, a la cual se le realizó un corte para obtener una sección plana que representa la base del farol. La medida del radio de esa esfera es de 25 cm. Además, cuando se realizó el corte, el centro de la base quedó a 20 cm del centro de la esfera. ¿Cuál es la medida del radio, en centímetros, de la base del farol?`,options:['10','15','32']},
{lead:`¿En cuántas ocasiones en total la cantidad de agua fue igual a 200 L?`,options:['En una ocasión','En dos ocasiones','En tres ocasiones']},
{lead:`Conforme avanzó el tiempo entre las 3 h y 9 h, desde el inicio del día, la cantidad de litros de agua contenida en el tanque fue`,options:['constante.','aumentando.','disminuyendo.']},
{lead:`¿Cuál es el ámbito de a?`,options:[']0, 24[',']0, 375]','[200, 375]']},
{lead:`Considere la siguiente información:`,pre:`La función f, que determina el ingreso mensual “f(p)”, en colones, obtenido en una cafetería, está dada por f(p) = 2500p, donde “p” representa la cantidad mensual de paquetes de café vendidos en la cafetería, con 12 ≤ p ≤ 22. Asimismo, la función p, que determina la cantidad mensual “p(t)” de paquetes de café vendidos, está dada por p(t) = 2t + 10, donde “t” representa el tiempo, en meses cumplidos, transcurridos desde que la cafetería inició labores, con 1 ≤ t ≤ 6.`,ask:`De acuerdo con la información anterior, si para un estudio de mercado en la cafetería se requiere conocer el criterio de la función (f ∘ p), entonces, ¿cuál opción corresponde a ese criterio?`,options:['(f ∘ p)(t) = 2500t','(f ∘ p)(t) = 5000t + 10','(f ∘ p)(t) = 5000t + 25 000']},
{lead:`La siguiente representación gráfica corresponde a la función r, que determina la altura “y” en kilómetros sobre el nivel del mar de un vehículo, en función del tiempo “x” en horas a partir del inicio de un viaje, con 1 ≤ x ≤ 3:`,fig:'17',ask:`De acuerdo con la información anterior, la representación gráfica de r<sup>−1</sup> corresponde a`,options:[`<span data-fig="17A"></span>`,`<span data-fig="17B"></span>`,`<span data-fig="17C"></span>`]},
{lead:`Considere la siguiente información:`,pre:`Un biólogo establece que la función c, la cual determina la cantidad de bacterias “c(n)”, en millones, que tiene una colonia, está dada por c(n) = 20(n + 2,5), donde “n” representa el tiempo en semanas desde el inicio de un experimento, con 1 ≤ n ≤ 5.`,ask:`De acuerdo con la información anterior, si el biólogo requiere determinar el criterio de la función n, la cual corresponde a la función inversa de c, entonces, ¿cuál opción corresponde a ese criterio?`,options:['n(c) = −20c − 50',m(mi('n')+mo('(')+mi('c')+mo(')')+mo('=')+frac(mi('c'),num(20))+mo('−')+frac(num('2,5'),num(20))),m(mi('n')+mo('(')+mi('c')+mo(')')+mo('=')+frac(mi('c'),num(20))+mo('−')+frac(num(5),num(2)))]},
{lead:`La siguiente representación gráfica muestra la función cuadrática h, que determina la altura “h(x)” en metros desde el suelo que alcanzó un papalote (cometa), en función del tiempo “x” en minutos, desde el lanzamiento del papalote, con 0 ≤ x ≤ 24:`,fig:'19',ask:`Además, en un estudio científico se necesita determinar el tiempo de vuelo del papalote en función de su altura. Para ello, se requiere determinar la función k, la cual tiene el mismo criterio que h. Asimismo, k tiene inversa y su dominio es un subconjunto del dominio de h.<br><br>De acuerdo con la información anterior, ¿cuál opción muestra un posible intervalo del dominio de k?`,options:['[0, 15]','[10, 20]','[13, 23]']},
{lead:`Considere la siguiente información:`,pre:`La función r, que determina la cantidad diaria de litros de agua potable “r(d)” procesada en una planta de tratamiento, está dada por r(d) = 170 + 5d<sup>2</sup>, donde “d” representa el tiempo en días, desde que la planta comenzó a procesar, con 10 ≤ d ≤ 20.`,ask:`De acuerdo con la información anterior, si se requiere determinar el criterio de la función d, la cual corresponde a la función inversa de r, entonces, ¿cuál opción corresponde a ese criterio?`,options:[m(mi('d')+mo('(')+mi('r')+mo(')')+mo('=')+root(frac(mi('r'),num(175)))),m(mi('d')+mo('(')+mi('r')+mo(')')+mo('=')+root(frac(mi('r')+mo('−')+num(5),num(170)))),m(mi('d')+mo('(')+mi('r')+mo(')')+mo('=')+root(frac(mi('r')+mo('−')+num(170),num(5))))]},
{lead:`Considere la siguiente información:`,pre:`En un estudio científico se determinó que la función q, que determina la cantidad de energía “q(t)” en kilovatios hora, generada por un panel solar, está dada por q(t) = ${m(num('0,2')+mo('+')+num('0,7')+`<mspace width="0.15em"/>`+root(mi('t')+mo('+')+num(10)))}, donde “t” representa el tiempo en horas que el panel estuvo expuesto a la luz del sol, con 1 ≤ t ≤ 8.`,ask:`De acuerdo con la información anterior, si el panel solar generó una cantidad de energía igual a tres kilovatios hora, entonces, ¿cuántas horas estuvo expuesto el panel a la luz del sol?`,options:['1,1','2,7','6,0']},
{lead:`Considere la siguiente información:`,pre:`La función t, que determina la temperatura “t(x)” en grados Celsius, medida por una persona en el interior de una cueva, está dada por t(x) = ${m(num(4)+`<mspace width="0.15em"/>`+root(mi('x')+mo('+')+num(1))+mo('+')+num(11))}, donde “x” representa la cantidad de metros de profundidad a la que se ubica la persona desde la entrada de la cueva, con 0 ≤ x ≤ 99.`,ask:`De acuerdo con la información anterior, si Andrés se ubica a 24 m de profundidad, desde la entrada de la cueva, entonces, ¿cuál es la temperatura medida por Andrés en esa ubicación?`,options:['24 °C','31 °C','64 °C']},
{lead:`El salario mensual en colones que obtiene un agente de ventas está relacionado linealmente con la cantidad de artículos que él vende en cada mes de un año. En la siguiente tabla se muestra la cantidad de artículos vendidos por el agente y el salario mensual de este, durante dos meses del año:`,pre:tableHTML([['Mes','Cantidad de artículos','Salario mensual'],['Junio','12','₡681 000'],['Setiembre','18','₡721 500']],true),ask:`De acuerdo con la información anterior, la ecuación de la recta que representa el salario mensual “y” obtenido por el agente de ventas, en función de la cantidad “x” de artículos que él vende en cada mes del año, corresponde a`,options:['y = 600 000x + 6750','y = 6750x + 600 000','y = 606 750x']},
{lead:`La siguiente representación gráfica corresponde a la función cuadrática m, la cual determina la cantidad de fruta “m(x)”, en kilogramos, obtenida de un árbol durante un período de cosecha, en función de la cantidad de fertilizante “x”, en kilogramos, utilizada en ese árbol, con 0 &lt; x ≤ 12:`,fig:'24',ask:`De acuerdo con la información anterior, ¿cuál fue la mayor cantidad de fruta, en kilogramos, obtenida del árbol durante el período de cosecha?`,options:['138','12','6']},
{lead:`Considere la siguiente información:`,pre:`La función v, que determina el valor “v(t)” en miles de dólares de una máquina, está dada por v(t) = 2 · (0,9)<sup>t</sup>, donde “t” representa el tiempo en años después de adquirida la máquina, con 0 &lt; t ≤ 8.`,ask:`De acuerdo con la información anterior, ¿cuántos años después de adquirida la máquina su valor, en miles de dólares, fue de 1,62?`,options:['2,0','1,7','0,8']},
{lead:`Considere la siguiente información:`,pre:`En una campaña de donación de sangre se determinó que la función b, que determina la cantidad “b(x)” de bolsas de sangre recolectadas, está dada por b(x) = 4 · log<sub>2</sub>(x), donde “x” representa el tiempo en días desde que inició esa campaña, con 1 &lt; x ≤ 128.`,ask:`De acuerdo con la información anterior, ¿cuántas bolsas de sangre fueron recolectadas a los 32 días desde que inició la campaña?`,options:['8','20','256']},
{lead:`Considere la siguiente información:`,pre:`Al inicio de un experimento científico un gusano tenía una longitud de 5 cm. Además, se determinó que, por cada semana transcurrida desde el inicio del experimento, ese gusano crecía 4 cm.`,ask:`De acuerdo con la información anterior, la ecuación de la recta correspondiente a la longitud “y” en centímetros de ese gusano, en función de la cantidad “x” de semanas transcurridas desde el inicio del experimento, corresponde a`,options:['y = 9x','y = 4x + 5','y = 5x + 4']},
{lead:`Considere la siguiente información:`,pre:`La función h, que determina la altura “h(x)” en metros desde el suelo de una pelota lanzada hacia arriba, está dada por h(x) = −5x<sup>2</sup> + 20x + 5, donde “x” representa el tiempo en segundos desde que la pelota fue lanzada, con 0 &lt; x ≤ 4.`,ask:`De acuerdo con la información anterior, ¿cuál fue la altura en metros desde el suelo alcanzada por la pelota a los 2 s desde que fue lanzada?`,options:['4','25','65']},
{lead:`Considere la siguiente información:`,pre:`La función q, que determina la cantidad “q(t)” en millones de partículas, que tenía una muestra de un elemento radiactivo, está dada por q(t) = ${m(num(6)+mo('·')+`<msup><mrow>${mo('(')+frac(num(1),num(2))+mo(')')}</mrow>${mi('t')}</msup>`)}, donde “t” representa el tiempo, en días, después de iniciado un experimento, con 0 ≤ t ≤ 6.`,ask:`De acuerdo con la información anterior, ¿cuántos días después de iniciado el experimento la cantidad de partículas, en millones, que tenía la muestra fue igual a 0,75?`,options:['3,6','3,0','2,2']},
{lead:`Considere la siguiente información:`,pre:`En un experimento científico la función n, que determina la cantidad de nutrientes “n(x)” que una planta absorbe de la tierra, durante un período continuo de exposición a una fuente de luz, está dada por n(x) = 8 · log<sub>2</sub>(x), donde “x” representa el tiempo en horas de exposición de la planta a la fuente, con 4 ≤ x ≤ 12.`,ask:`De acuerdo con la información anterior, si una planta estuvo expuesta a la fuente de luz durante 4 h, entonces, ¿cuántos nutrientes absorbió la planta?`,options:['1','16','32']},
{lead:`Elena compró 4 kg de papas y 5 kg de carne, por los cuales pagó en total ₡17 587. Javier compró 6 kg de papas y 5 kg de carne, por los cuales pagó en total ₡18 943. Si cada kilogramo de papas tiene el mismo precio y cada kilogramo de carne tiene el mismo precio, entonces, ¿cuál es el precio de cada kilogramo de carne?`,options:['₡4331','₡2975','₡1894']},
{lead:`Jorge compró 3 kg de café y 5 kg de azúcar, por los cuales pagó en total ₡19 615. Elizabeth compró 3 kg de café y 3 kg de azúcar, por los cuales pagó en total ₡17 919. Si cada kilogramo de ese café tenía el mismo precio y cada kilogramo de esa azúcar tenía el mismo precio, entonces, ¿cuál es el precio que tenía cada kilogramo de café?`,options:['₡3269','₡5125','₡7386']},
{lead:`La siguiente tabla muestra la función p, que determina la cantidad “p(x)” de plantas que crecieron cada año en una reserva natural, en función del tiempo “x” en años desde el inicio de un experimento, con 1 ≤ x ≤ 7:`,pre:tableHTML([['x','1','2','3','4','5','6','7'],['p(x)','82','88','96','106','118','132','148']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar a p?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`La siguiente tabla corresponde a la función n, la cual determina la cantidad de residuos “n(x)”, en miles de kilogramos, reciclada por una planta de tratamiento, en función del tiempo “x” en meses transcurridos desde su apertura, con 2 ≤ x ≤ 32:`,pre:tableHTML([['x','2','4','8','16','32'],['n(x)','1','2','3','4','5']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar a n?`,options:['Función exponencial','Función logarítmica','Función cuadrática']},
{lead:`Considere la siguiente información referente a la función w que determina la cantidad diaria de clientes “w(t)” que visitaron un centro comercial, en función del tiempo “t” en días transcurridos desde el inicio de una quincena, con 1 ≤ t ≤ 7:`,pre:tableHTML([['t','1','2','3','4','5','6','7'],['w(t)','100','200','400','800','1600','3200','6400']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función involucrada en el modelo matemático que se adapta mejor para representar a w?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondientes a los tiempos en minutos que tardaron varios atletas en completar una carrera. Además, se muestra la mediana de los datos:`,fig:'36',ask:`De acuerdo con la información anterior, el tiempo promedio que tardaron los atletas en completar la carrera fue`,options:['igual que 18 min.','mayor que 18 min.','menor que 18 min.']},
{lead:`Al menos la mitad del total de repartidores de la empresa entregaron los pedidos en un tiempo menor o igual a`,options:['13 min.','15 min.','16 min.']},
{lead:`¿Cuál fue el mayor tiempo que tardó al menos un repartidor de la empresa en entregar un pedido a un cliente?`,options:['16 min','21 min','28 min']},
{lead:`El tiempo que tardó al menos el 75 % del total de repartidores de la empresa en entregar los pedidos a los clientes, fue mayor o igual que`,options:['10 min.','16 min.','21 min.']},
{lead:`La siguiente tabla muestra el porcentaje de cada uno de tres componentes que se consideraron al calificar las fotografías presentadas por las personas participantes en un concurso. Asimismo, se muestra la calificación obtenida por componente, en una escala de 1 a 100, de la fotografía presentada por Rodolfo:`,pre:tableHTML([['Componente','Porcentaje','Calificación de la fotografía<br>de Rodolfo'],['Nitidez','20 %','69'],['Originalidad','35 %','78'],['Impacto visual','45 %','80']],true),ask:`Además, la nota final de esa fotografía corresponde a la media aritmética ponderada de todos los componentes que se consideraron al calificar.<br><br>De acuerdo con la información anterior, ¿cuál es la nota final de la fotografía presentada por Rodolfo en el concurso?`,options:['75,66','77,10','78,00']}
];
const SHARED={
13:{lead:`Para responder los ítems 13, 14 y 15 considere la siguiente información:`,pre:`La siguiente representación gráfica muestra la función a, que determina la cantidad de litros de agua “a(t)” contenida en un tanque de almacenamiento, en función del tiempo “t” en horas desde el inicio de un día, con 0 &lt; t &lt; 24:`,fig:'13'},
37:{lead:`Para responder los ítems 37, 38 y 39 considere la siguiente información:`,pre:`La siguiente tabla muestra algunas medidas de posición referentes a los tiempos, en minutos, que tardaron los repartidores de una empresa en entregar los pedidos solicitados por los clientes, durante un día:<br>${tableHTML([['Medida de posición','Valor'],['Tercer cuartil','21'],['Primer cuartil','10'],['Promedio','16'],['Mediana','15'],['Moda','13'],['Máximo','28'],['Mínimo','6']],true)}`}
};
if(QUESTIONS.length!==40||QUESTIONS.some(q=>q.options.length!==3))throw Error('Transcripción incompleta.');
