const ANSWER_KEY='ABACCCCBBACABBCBACBCAAABBCAAAABBCCA'.split('');
const SOLUTIONS=[
'La circunferencia tiene centro (4, 3) y radio 2 km. Su ecuación es (x − 4)<sup>2</sup> + (y − 3)<sup>2</sup> = 2<sup>2</sup> = 4.',
'El centro debe estar 30 m al este y 15 m al norte de L, con radio 10 m. En B el punto extremo al este tiene coordenada 40, de modo que el radio es 40 − 30 = 10.',
'La nueva ubicación es W = (20 − 5, 5) = (15, 5). El radio permanece igual a 5 km; esta es la gráfica A.',
'Cada trayectoria es tangente: el radar detecta cada barco una sola vez. La recta n es horizontal y tangente debajo de la circunferencia. Dos puntos de tangencia separados por el diámetro de 4 km son opuestos; las tangentes son paralelas.',
'La diana tiene centro (61, 61) y radio 61 cm. Las distancias del centro a R, S y T son 72, 62 y 52 cm. Solo T cumple 52 &lt; 61.',
'Si el lado es l, el área triangular es (√3/4)l<sup>2</sup> ≈ 0,433l<sup>2</sup>. Sobra aproximadamente 0,567l<sup>2</sup>; el área del rótulo es menor.',
'Al unir los dos hexágonos, el lado compartido deja de formar parte del borde exterior. La suma separada es 12 lados y el perímetro unido tiene 10 lados.',
'El piso triangular tiene área (4 × 3)/2 = 6 m<sup>2</sup>. Compró 12 m<sup>2</sup>, de modo que le sobraron 6 m<sup>2</sup>.',
'La figura ocupa aproximadamente 22 celdas, cada una de 10 000 km<sup>2</sup>: alrededor de 220 000 km<sup>2</sup>, entre 180 000 y 280 000.',
'Un plano oblicuo a las bases de un cilindro circular recto, que no las interseca, produce una sección elíptica.',
'Para un mismo radio esférico R, el radio de abertura r y la distancia al centro d cumplen d<sup>2</sup> = R<sup>2</sup> − r<sup>2</sup>. La abertura mayor, P (diámetro 24 cm), está más cerca del centro.',
'Desde el minuto 50 hasta el 90, la rapidez baja de 72 km/h a 0 km/h. Por ello fue disminuyendo.',
'La rapidez cruza 54 km/h una vez al subir entre 0 y 15 minutos y otra vez al bajar, en el minuto 65. Fueron dos ocasiones.',
'C(2) = 1000 × 2<sup>3</sup> + 4000 = 8000 + 4000 = 12 000 suscriptores.',
'De p = 4h se despeja h = p/4.',
'De a = πr<sup>2</sup> se obtiene r<sup>2</sup> = a/π y, como r es positivo, r = √(a/π). La raíz abarca toda la fracción.',
'La inversa intercambia las coordenadas: (0, 32) pasa a (32, 0) y (285, 545) pasa a (545, 285). Corresponde a la gráfica A.',
'La parábola tiene vértice en t = 2. Los intervalos ]0,3[ y ]1,4[ incluyen valores de ambos lados del vértice y repiten alturas. En ]3,4[ la función es estrictamente decreciente y admite inversa.',
'2 = √(x + 1). Al elevar al cuadrado: 4 = x + 1, por tanto x = 3 semanas.',
'El monto fijo es ₡500 y cada kilómetro cuesta ₡700. Entonces y = 700x + 500.',
'E(28) = 3 × 28 + 64 = 148 y E(42) = 3 × 42 + 64 = 190. La gráfica A une (28,148) y (42,190).',
'El máximo de C(x) = −x<sup>2</sup> + 16x + 400 ocurre en x = −16/(2 × −1) = 8 árboles.',
'El vértice de la gráfica está en (4,34). El precio máximo ocurre a los 4 años; 34 corresponde al precio, no al tiempo.',
'Al inicio x = 0: C(0) = 2<sup>0</sup> = 1, en miles de bacterias.',
'Solo S tiene base mayor que 1: 6/5 = 1,2. Las bases 9/10 = 0,9 y 3/4 = 0,75 producen un monto menor al invertido al cabo de un año.',
'log(x) = 1 implica x = 10<sup>1</sup> = 10 segundos.',
'243 = 3<sup>5</sup>, por tanto log<sub>3</sub>(243) = 5 relojes adicionales.',
'La compra de Miguel da 3x + 2y = 1830 y la de Natalia da x + 5y = 935. Es el sistema de la opción A.',
'W: y = 1000x + 1500. H: al dividir entre 2, y − 1000x = 1500, es decir, y = 1000x + 1500. Los montos son iguales.',
'La razón P(x)/x es siempre 10; el criterio es P(x) = 10x. El modelo es una función lineal.',
'Los valores 2, 4, 8, 16, 32 y 64 son 2<sup>1</sup>, 2<sup>2</sup>, …, 2<sup>6</sup>. El criterio es N(x) = 2<sup>x</sup>.',
'Una asimetría positiva presenta una cola hacia valores mayores, que eleva la media por encima de la mediana. En el modelo del ítem, el promedio es mayor que 3,08 kg.',
'La mayor cantidad es el máximo de la tabla: 137 puntos.',
'La moda es 108 puntos: es la cantidad que se repite con mayor frecuencia y, conforme al enunciado, se anotó en al menos dos partidos.',
'El mínimo es 9 meses: esa fue la menor edad. La moda 10 no permite afirmar que la mayoría caminó a esa edad, y el máximo es 15, no 11 meses.'
];
if(ANSWER_KEY.length!==35||SOLUTIONS.length!==35)throw Error('Solucionario incompleto.');
