// Clave calculada y soluciones verificadas; los valores no se toman de marcas de respuesta.
const ANSWER_KEY='CBAABBCCAAABBACBCBBABCB BACBCAAABCB AACCBB'.replace(/ /g,'');
const SOLUTIONS=[
`El centro es A(40, 30) y el radio es 15 m. La ecuación es (x − 40)<sup>2</sup> + (y − 30)<sup>2</sup> = 15<sup>2</sup> = 225.`,
`La circunferencia debe tener centro T(20, 15) y radio 10 m. En B, el punto (30, 15) está a 10 m del centro.`,
`Al trasladar el dispositivo 5 m al sur, su centro pasa de (10, 5) a (10, 0). El radio sigue siendo 5 m: (x − 10)<sup>2</sup> + y<sup>2</sup> = 25.`,
`El centro del objetivo es (10, 10) y su radio es 5 m. La distancia al cuadrado desde el centro hasta (11, 12) es 1<sup>2</sup> + 2<sup>2</sup> = 5, menor que 25. La moneda de Fabián quedó dentro.`,
`h es vertical y j es horizontal. Estas dos rectas forman un ángulo de 90°.`,
`El rectángulo mide 8 m por 4 m y tiene área 32 m<sup>2</sup>. El triángulo superior tiene base 8 m y altura 6 − 4 = 2 m: su área es 8 m<sup>2</sup>. El triángulo de la derecha tiene base 10 − 8 = 2 m y altura 4 m: su área es 4 m<sup>2</sup>. El total es 44 m<sup>2</sup>.`,
`En un hexágono regular, la apotema es ${m(frac(root(num(3)),num(2))+mi('s'))}. De ${m(num(30)+root(num(3))+mo('=')+frac(root(num(3)),num(2))+mi('s'))} se obtiene s = 60 m. El perímetro es 360 m y el área es ${m(frac(num(360)+mo('·')+num(30)+root(num(3)),num(2))+mo('=')+num(5400)+root(num(3)))} m<sup>2</sup>.`,
`El panel es un rectángulo de 2 m por 1 m. Su perímetro es 2(2 + 1) = 6 m.`,
`El lado de la tarima cuadrada es ${m(root(num(64))+mo('=')+num(8))} m. El lado del pentágono es la mitad: 4 m. Su perímetro es 5 · 4 = 20 m.`,
`El rectángulo que contiene la figura tiene base 9 − 1 = 8 cm y altura 5 − 2 = 3 cm; su área es 24 cm<sup>2</sup>. Las dos curvas recortan regiones de ancho 1 cm y altura 3 cm, cuya área conjunta es menor que 6 cm<sup>2</sup>. Por ello, el área de la etiqueta es mayor que 18 y menor que 24 cm<sup>2</sup>.`,
`La intersección del plano que pasa por el centro de una esfera con su superficie es una circunferencia.`,
`El corte produce un rectángulo de altura 30 cm y base igual al diámetro 2 · 10 = 20 cm. Su perímetro es 2(30 + 20) = 100 cm.`,
`En la gráfica, el punto correspondiente al día 10 tiene temperatura 50 °C.`,
`Al inicio del monitoreo, x = 0 y la temperatura es 0 °C. Es la menor temperatura de la gráfica.`,
`La función aumenta en el tramo entre los días 0 y 10. El intervalo [3, 9] está contenido en ese tramo.`,
`En II, cada valor de x aparece una única vez y se relaciona con un solo valor de p. En I y III hay valores de x asociados con distintas salidas.`,
`La función h pasa por (0, 4) y (6, 2). Al intercambiar las coordenadas, la inversa pasa por (4, 0) y (2, 6), como se muestra en C.`,
`De v = 50(n + 2), se obtiene ${m(frac(mi('v'),num(50))+mo('=')+mi('n')+mo('+')+num(2))}. Al despejar: ${m(mi('n')+mo('=')+frac(mi('v'),num(50))+mo('−')+num(2))}.`,
`De m = 2000(h<sup>2</sup> + 12), se obtiene ${m(frac(mi('m'),num(2000))+mo('−')+num(12)+mo('=')+`<msup>${mi('h')}${num(2)}</msup>`)}. Como h es positivo, ${m(mi('h')+mo('=')+root(frac(mi('m'),num(2000))+mo('−')+num(12)))}.`,
`El ámbito de la función inversa es el dominio de la función original. El dominio de c es [2, 20], por lo que ese es el ámbito de t.`,
`Al sustituir d = 15: p(15) = ${m(num(10)+mo('+')+num(4)+root(num(15)+mo('+')+num(1))+mo('=')+num(10)+mo('+')+num(4)+mo('·')+num(4)+mo('=')+num(26))} kg.`,
`Los puntos (1, 1), (4, 2), (9, 3) y (16, 4) cumplen ${m(mi('f')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')))}.`,
`h(1) = −5(1)<sup>2</sup> + 20(1) + 60 = −5 + 20 + 60 = 75 m.`,
`La pendiente es ${m(frac(num(410)+mo('−')+num(250),num(9)+mo('−')+num(5))+mo('=')+num(40))}. De 250 = 40 · 5 + b se obtiene b = 50. La ecuación es y = 40x + 50.`,
`La base de la función exponencial es 0,85, que está entre 0 y 1. Por ello, la cantidad de residuo disminuye al aumentar x.`,
`v(t) = 1,5t + 2 se aproxima a 2 L cuando t se aproxima a 0 y alcanza v(4) = 8 L. El extremo (0, 2) es abierto y (4, 8) es cerrado. La opción C cumple estas condiciones.`,
`c(8) = log<sub>2</sub>(8) = 3, porque 2<sup>3</sup> = 8.`,
`La parábola abre hacia abajo. Su máximo está en ${m(mi('t')+mo('=')+frac(mo('−')+num(3),num(2)+mo('·')+mo('(')+mo('−')+num('0,5')+mo(')'))+mo('=')+num(3))}. Al sustituir: r(3) = −0,5 · 9 + 3 · 3 = 4,50 m/s.`,
`g(4) = (1,3)<sup>4</sup> = 2,8561 picogramos, aproximadamente 2,86.`,
`d(32) = 5 · log<sub>2</sub>(32) = 5 · 5 = 25 megabytes.`,
`Si c es la cantidad de cajas y e la cantidad de estantes: 15c + 10e = 345 y 12c + 7e = 264. Al multiplicar la primera ecuación por 7 y la segunda por 10 y restar, se obtiene 15c = 225. Por tanto, se fabricaron 15 cajas.`,
`Si m es el precio del kilogramo de café molido y g el del café en grano: 3m + 2g = 24 500 y 2m + 4g = 27 000. Al duplicar la primera ecuación y restar la segunda: 4m = 22 000. Entonces m = ₡5500.`,
`La presión se duplica en cada minuto: 100, 200, 400 y 800. Una razón constante entre valores sucesivos corresponde a un modelo exponencial.`,
`Las diferencias sucesivas son 14, 20, 26, 32 y 38. Las segundas diferencias son constantes e iguales a 6. El modelo es cuadrático.`,
`La cantidad de hojas aumenta siempre en 5 por semana. Una tasa de cambio constante corresponde a una función lineal.`,
`120 personas representan el 75 % de 160. El primer cuartil es 40 min, de modo que al menos el 75 % de los datos son mayores o iguales que 40 min.`,
`El máximo es 180 min. Por tanto, ninguna de las personas dedicó 200 min al estudio.`,
`La media ponderada es 0,50 · 82 + 0,30 · 90 + 0,20 · 75 = 41 + 27 + 15 = 83,00.`,
`La distribución presenta una cola hacia los tiempos mayores. En una distribución con asimetría a la derecha, la mediana es menor que el promedio indicado de 18 min.`,
`Los puntos medios de los intervalos son 25, 75 y 125 min. La media agrupada es ${m(frac(num(25)+mo('·')+num(8)+mo('+')+num(75)+mo('·')+num(22)+mo('+')+num(125)+mo('·')+num(10),num(40))+mo('=')+frac(num(3100),num(40))+mo('=')+num('77,5'))} min.`
];
if(ANSWER_KEY.length!==40||SOLUTIONS.length!==40)throw Error('Clave o soluciones incompletas.');
