// Transcripción revisada contra el cuadernillo CINDEA 2025-N01.
const m=body=>`<math xmlns="http://www.w3.org/1998/Math/MathML" displaystyle="true">${body}</math>`;
const root=body=>`<msqrt><mrow>${body}</mrow></msqrt>`;
const frac=(a,b)=>`<mfrac><mrow>${a}</mrow><mrow>${b}</mrow></mfrac>`;
const num=n=>`<mn>${n}</mn>`,mi=x=>`<mi>${x}</mi>`,mo=x=>`<mo>${x}</mo>`;
const tableHTML=(rows,open=false)=>`<div class="table-wrap"><table class="exam-table${open?' open-table':''}">${rows.map((r,i)=>`<tr>${r.map(c=>`<${i?'td':'th'}>${c}</${i?'td':'th'}>`).join('')}</tr>`).join('')}</table></div>`;
const QUESTIONS=[
{lead:`Una piedra se dejó caer desde cierta altura e impactó la superficie del agua de un lago. La ubicación A donde impactó la piedra con el agua es 30 m al norte y 40 m al este de la ubicación P de una casa. Posterior al impacto de la piedra, se formó una onda circular en la superficie del agua de ese lago. En cierto instante, el alcance máximo de esa onda se ubicó a 15 m alrededor de A.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones A del impacto de la piedra con el agua, P de la casa y C de la circunferencia correspondiente al alcance máximo de esa onda:`,fig:'1',ask:`De acuerdo con la información anterior, ¿cuál es la representación algebraica, cuyas unidades están en metros, de C?`,options:['(x + 40)<sup>2</sup> + (y + 30)<sup>2</sup> = 15','(x − 30)<sup>2</sup> + (y + 40)<sup>2</sup> = 30','(x − 40)<sup>2</sup> + (y − 30)<sup>2</sup> = 225']},
{lead:`El alcance máximo de la señal inalámbrica emitida por un teléfono celular es de 10 m a su alrededor. La ubicación T de ese teléfono es 20 m al este y 15 m al norte de la ubicación D del dormitorio de una casa. ¿Cuál es la representación gráfica, cuyas unidades están en metros, de la circunferencia correspondiente al alcance máximo de la señal emitida por el celular?`,options:['<span data-fig="2A"></span>','<span data-fig="2B"></span>','<span data-fig="2C"></span>']},
{lead:`Un dispositivo electrónico, que emite una señal inalámbrica con forma circular, se ubica 10 m al este y 5 m al norte del laboratorio de una escuela. El alcance máximo de la señal emitida por ese dispositivo es de 5 m a su alrededor.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra las ubicaciones T del dispositivo, L del laboratorio y C de la circunferencia correspondiente al alcance máximo de la señal emitida por ese dispositivo:`,fig:'3',ask:`De acuerdo con la información anterior, si desde su ubicación actual el dispositivo se traslada 5 m al sur, entonces, ¿cuál es la representación algebraica, cuyas unidades están en metros, de la circunferencia correspondiente al alcance máximo de la señal emitida por el dispositivo en su nueva ubicación?`,options:['(x − 10)<sup>2</sup> + y<sup>2</sup> = 25','(x − 15)<sup>2</sup> + (y − 5)<sup>2</sup> = 25','(x − 10)<sup>2</sup> + (y − 10)<sup>2</sup> = 25']},
{lead:`Un juego consiste en lanzar una moneda a un objetivo circular ubicado en el suelo, cuya medida del radio es 5 m.`,pre:`La siguiente representación gráfica, cuyas unidades están en metros, muestra la circunferencia correspondiente al borde del objetivo:`,fig:'4',ask:`Además, durante el juego:<ul><li>Fabián lanzó una moneda y esta se ubicó en el punto correspondiente a (11, 12).</li><li>Génesis lanzó una moneda y esta se ubicó en el punto correspondiente a (10, 16).</li><li>Humberto lanzó una moneda y esta se ubicó en el punto correspondiente a (3, 13).</li></ul>De acuerdo con la información anterior, ¿cuál persona lanzó la moneda que se ubicó en el interior del objetivo?`,options:['Fabián','Génesis','Humberto']},
{lead:`Un parque tiene forma circular y la medida de su diámetro es 32 m. Las rectas h, k, representan aceras que pasan por el centro de ese parque. Las rectas j, n, representan dos aceras paralelas entre sí. La siguiente representación gráfica, cuyas unidades están en metros, muestra la circunferencia que representa el parque y las rectas que representan las aceras:`,fig:'5',ask:`De acuerdo con la información anterior, dos rectas perpendiculares entre sí corresponden a`,options:['j y k.','h y j.','k y n.']},
{lead:`Considere la siguiente información:`,pre:`La siguiente figura representa una superficie lateral (fachada) de un edificio, la cual está compuesta por dos triángulos y un rectángulo:`,fig:'6',ask:`De acuerdo con la información anterior, si se requiere pintar la totalidad de esa fachada, entonces, ¿cuántos metros cuadrados se requieren pintar?`,options:['40','44','56']},
{lead:`El dueño de una propiedad contrató a un jardinero para cortar la totalidad del zacate de un jardín que está dentro de la propiedad. La superficie del jardín tiene forma de hexágono regular, cuya medida de la apotema es ${m(num(30)+'<mspace width="0.15em"/>'+root(num(3)))} m. Si el zacate cubre la totalidad de la superficie del jardín, entonces, ¿cuántos metros cuadrados de zacate debe cortar el jardinero?`,options:[m(num(2700)+'<mspace width="0.15em"/>'+root(num(3))),m(num(4860)+'<mspace width="0.15em"/>'+root(num(3))),m(num(5400)+'<mspace width="0.15em"/>'+root(num(3)))]},
{lead:`Andrea es ingeniera en una empresa que produce paneles solares para generar energía limpia. La siguiente representación gráfica, cuyas unidades están en metros, muestra el polígono ABCD que representa un panel solar diseñado por ella:`,fig:'8',ask:`De acuerdo con la información anterior, si Andrea requiere colocar una cinta metálica sobre la totalidad del borde de ese panel, entonces, ¿cuál es la menor cantidad de metros de cinta que ella requiere colocar?`,options:['2','3','6']},
{lead:`Para colocar las obras de arte en una exposición se construirán dos tarimas. Una de las tarimas tendrá la superficie con forma de pentágono regular y la otra con forma de cuadrado. Para esas construcciones se debe considerar lo siguiente:`,pre:`<ul><li>El lado de la superficie de la tarima cuadrada medirá el doble de la medida del lado de la superficie de la tarima pentagonal.</li><li>El área de la superficie de la tarima cuadrada será 64 m<sup>2</sup>.</li></ul>`,ask:`De acuerdo con la información anterior, ¿cuál será el perímetro de la superficie de la tarima pentagonal?`,options:['20 m','40 m','80 m']},
{lead:`La siguiente representación gráfica, cuyas unidades están en centímetros, muestra la figura ABCDEF que representa la forma que tiene una etiqueta decorativa elaborada con lámina adhesiva y que se colocará en un frasco de pintura, durante una clase de arte:`,fig:'10',ask:`De acuerdo con la información anterior, la cantidad de centímetros cuadrados de lámina adhesiva requerida para elaborar esa etiqueta es mayor que`,options:['18 y menor que 24.','24 y menor que 28.','28 y menor que 32.']},
{lead:`Dos adornos se fabrican a partir de una esfera de plástico a la que se le realiza un corte plano que pasa por el centro de la esfera. La sección plana obtenida en cada uno de los adornos, producto del corte realizado a esa esfera, corresponde a una`,options:['circunferencia.','hipérbola.','parábola.']},
{lead:`Considere la siguiente información:`,pre:`Un artista trabaja con un bloque de hielo con forma de cilindro circular recto, cuyo radio de la base mide 10 cm y la altura del cilindro mide 30 cm. Para elaborar una escultura, el artista realiza un corte plano al bloque, que pasa por el centro de las bases y es perpendicular a estas.`,ask:`De acuerdo con la información anterior, ¿cuál es el perímetro de la sección plana obtenida producto del corte?`,options:['80 cm','100 cm','600 cm']},
{lead:`¿Cuál fue la temperatura registrada en el interior del invernadero en el día 10 desde el inicio del monitoreo?`,options:['10','50','60']},
{lead:`Durante todo ese tiempo, ¿cuál fue la menor temperatura registrada en el interior del invernadero?`,options:['0 °C','10 °C','60 °C']},
{lead:`¿Cuál opción muestra un intervalo donde t es creciente?`,options:['[45, 56]','[22, 29]','[3, 9]']},
{lead:`En un laboratorio de física, se estudia la relación entre la variable “x” y “p”, que describe características de una partícula. En esta relación “x” es la variable independiente y “p” es la variable dependiente. Cada una de las siguientes tablas (identificadas con I, II y III) muestra la relación en cada una de tres partículas:`,pre:`<p>I.</p>${tableHTML([['x','4','1','0','1','4'],['p','−2','−1','0','1','2']])}<p>II.</p>${tableHTML([['x','−1','0','3','8','15'],['p','0','1','2','3','4']])}<p>III.</p>${tableHTML([['x','2','−3','5','−3','2'],['p','−1','0','4','2','3']])}`,ask:`De acuerdo con la información anterior, ¿cuál tabla muestra una relación que corresponde a una función?`,options:['I','II','III']},
{lead:`La siguiente representación gráfica corresponde a la función h, que determina la cantidad de medicamento “y” en miligramos por litro, presente en la sangre de una persona, en función del tiempo “x” en minutos, desde que se administró una dosis, con 0 ≤ x ≤ 6:`,fig:'17',ask:`De acuerdo con la información anterior, la representación gráfica de h<sup>−1</sup> corresponde a`,options:['<span data-fig="17A"></span>','<span data-fig="17B"></span>','<span data-fig="17C"></span>']},
{lead:`Considere la siguiente información:`,pre:`Un administrador de un parque nacional establece que la función v, la cual determina la cantidad diaria de visitantes “v(n)” que han ingresado a ese parque, está dada por v(n) = 50(n + 2), donde “n” representa el tiempo en días, desde que inició la temporada alta, con 1 ≤ n ≤ 10.`,ask:`De acuerdo con la información anterior, si para un reporte el administrador requiere determinar el criterio de la función n, la cual corresponde a la función inversa de v, entonces, ¿cuál opción corresponde a ese criterio?`,options:['n(v) = 50v + 2',m(mi('n')+mo('(')+mi('v')+mo(')')+mo('=')+frac(mi('v'),num(50))+mo('−')+num(2)),m(mi('n')+mo('(')+mi('v')+mo(')')+mo('=')+frac(mi('v')+mo('−')+num(2),num(50)))]},
{lead:`Considere la siguiente información:`,pre:`En una empresa se establece que la función m, la cual determina la tarifa “m(h)” en colones, que se cobra por utilizar cierta maquinaria agrícola, está dada por m(h) = 2000(h<sup>2</sup> + 12), donde “h” representa el tiempo en horas, que se utilizó esa maquinaria, con 2 ≤ h ≤ 5.`,ask:`De acuerdo con la información anterior, si para un estudio de control de la maquinaria en la empresa se requiere determinar el criterio de la función h, la cual corresponde a la función inversa de m, entonces, ¿cuál opción corresponde a ese criterio?`,options:[6,12,24].map(n=>m(mi('h')+mo('(')+mi('m')+mo(')')+mo('=')+root(frac(mi('m'),num(2000))+mo('−')+num(n))))},
{lead:`Considere la siguiente información:`,pre:`La función c, que determina la cantidad de café “c(t)” en kilogramos, que se obtiene después de un proceso de secado, está dada por c(t) = 2t + 8, donde “t” representa el tiempo en horas, desde que comenzó el secado, con 2 ≤ t ≤ 20.`,ask:`De acuerdo con la información anterior, si se define la función t, la cual corresponde a la función inversa de c, entonces, ¿cuál es el ámbito de t?`,options:['[2, 20]','[12, 48]','[20, 48]']},
{lead:`Considere la siguiente información:`,pre:`En una planta procesadora de cacao se establece que la función p, la cual determina la cantidad total de manteca de cacao “p(d)” en kilogramos, que se obtuvo en un proceso, está dada por p(d) = ${m(num(10)+mo('+')+num(4)+root(mi('d')+mo('+')+num(1)))}, donde “d” representa el tiempo en horas, desde que comenzó ese proceso, con 3 ≤ d ≤ 48.`,ask:`De acuerdo con la información anterior, ¿cuál es la cantidad total de manteca de cacao que se obtuvo a las 15 h desde que comenzó el proceso?`,options:['18 kg','26 kg','56 kg']},
{lead:`La siguiente representación gráfica corresponde a la función f, la cual determina la altura sobre el nivel del mar “f(x)” en miles de metros, de un vehículo durante un viaje, en función de la distancia recorrida “x” en kilómetros, a partir del inicio del viaje, con 0 &lt; x ≤ 16:`,fig:'22',ask:`De acuerdo con la información anterior, ¿cuál opción podría corresponder al criterio de f?`,options:[m(mi('f')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x'))+mo('+')+num(4)),m(mi('f')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')+mo('+')+num(4))),m(mi('f')+mo('(')+mi('x')+mo(')')+mo('=')+root(mi('x')))]},
{lead:`Considere la siguiente información:`,pre:`La función h, la cual determina la altura “h(x)” en metros desde el suelo, que tuvo un objeto al ser lanzado desde la azotea de un edificio, está dada por h(x) = −5x<sup>2</sup> + 20x + 60, donde “x” representa el tiempo en segundos, desde que ese objeto fue lanzado, con 0 ≤ x &lt; 6.`,ask:`De acuerdo con la información anterior, ¿cuál fue la altura, en metros desde el suelo, que tuvo ese objeto en el segundo uno desde que fue lanzado?`,options:['70','75','105']},
{lead:`Considere la siguiente información:`,pre:`En una finca cafetalera, la cantidad semanal de canastos de café recolectados está linealmente relacionada con el número de trabajadores disponibles en la finca. Si en una semana había cinco trabajadores disponibles en la finca, entonces se recolectaron 250 canastos, pero si en otra semana había nueve trabajadores disponibles en la finca, entonces se recolectaron 410 canastos.`,ask:`De acuerdo con la información anterior, ¿cuál es la ecuación de la recta que representa la cantidad semanal “y” de canastos recolectados, en función del número “x” de trabajadores disponibles en la finca?`,options:['y = 50x + 40','y = 40x + 50','y = 90x']},
{lead:`Considere la siguiente información:`,pre:`La función r, que determina la cantidad “r(x)” en miligramos, de cierto residuo radiactivo que había en un recipiente de un laboratorio, está dada por r(x) = (0,85)<sup>x</sup>, donde “x” representa el tiempo en días, desde el inicio de un experimento, con 0 ≤ x ≤ 10.`,ask:`De acuerdo con la información anterior, conforme aumentó el tiempo, desde el inicio de ese experimento, la cantidad de residuo que había en el recipiente fue`,options:['disminuyendo.','aumentando.','constante.']},
{lead:`La función v, que determina el volumen “v(t)” en litros, de agua acumulada en un tanque durante una lluvia, está dada por v(t) = 1,5t + 2, donde “t” representa el tiempo en horas, transcurridas desde que comenzó la lluvia, con 0 &lt; t ≤ 4.`,ask:`De acuerdo con la información anterior, ¿cuál es la representación gráfica de v?`,options:['<span data-fig="26A"></span>','<span data-fig="26B"></span>','<span data-fig="26C"></span>']},
{lead:`Considere la siguiente información:`,pre:`La función c, la cual determina la cantidad “c(x)” de camisetas adicionales a las que usualmente vende una tienda en cada mes, está dada por c(x) = log<sub>2</sub>(x), donde “x” representa el monto en dólares, que se descuenta al precio de cada camiseta durante el mes, con 2 ≤ x ≤ 16.`,ask:`De acuerdo con la información anterior, si durante un mes cada camiseta tuvo un descuento de ocho dólares en su precio, entonces, ¿cuántas camisetas adicionales vendió la tienda en ese mes?`,options:['2','3','4']},
{lead:`Considere la siguiente información:`,pre:`La función r, la cual determina la rapidez “r(t)” en metros por segundo, que alcanzó una persona en un recorrido, está dada por r(t) = −0,5t<sup>2</sup> + 3t, donde “t” representa el tiempo en minutos, desde que inició el recorrido, con 1 &lt; t &lt; 5.`,ask:`De acuerdo con la información anterior, durante todo ese tiempo, ¿cuál fue la mayor rapidez, en metros por segundo, que alcanzó la persona?`,options:['3,00','3,38','4,50']},
{lead:`Considere la siguiente información:`,pre:`En condiciones especiales la función g, que determina la masa “g(x)”, en picogramos, de un grupo de bacterias cultivadas en un laboratorio, está dada por g(x) = (1,3)<sup>x</sup>, donde “x” representa el tiempo en horas, desde el inicio del cultivo, con 1 ≤ x ≤ 5.`,ask:`De acuerdo con la información anterior, ¿cuál es la masa aproximada del grupo de bacterias, en picogramos, a las 4 h desde el inicio del cultivo?`,options:['2,86','3,07','5,20']},
{lead:`Considere la siguiente información:`,pre:`La función d, que determina la cantidad de datos “d(n)” en megabytes, almacenados en un archivo comprimido, está dada por d(n) = 5 · log<sub>2</sub>(n), donde “n” representa el número de imágenes que contiene ese archivo, con 4 ≤ n ≤ 64.`,ask:`De acuerdo con la información anterior, ¿cuántos datos en megabytes, tiene almacenados ese archivo si contiene 32 imágenes?`,options:['25','80','84']},
{lead:`Considere la siguiente información:`,pre:`En un taller artesanal se elaboran únicamente cajas de madera y estantes. Para su elaboración, cada caja requiere 15 min de ensamblaje y 12 min de lijado. Asimismo, cada estante requiere 10 min de ensamblaje y 7 min de lijado.`,ask:`De acuerdo con la información anterior, si para la elaboración de estantes y cajas se utilizaron 345 min de ensamblaje y 264 min de lijado, entonces, ¿cuántas cajas de madera se fabricaron en total?`,options:['15','50','107']},
{lead:`Carlos y Mariana fueron a una cafetería a comprar café molido y café en grano. Carlos compró 3 kg de café molido y 2 kg de café en grano, por los cuales pagó ₡24 500. Mariana compró 2 kg de café molido y 4 kg de café en grano, por los cuales pagó ₡27 000. Si cada kilogramo de café molido tenía el mismo precio y cada kilogramo de café en grano tenía el mismo precio, entonces, ¿cuál fue el precio de cada kilogramo de café molido?`,options:['₡7375','₡5500','₡4900']},
{lead:`La siguiente representación gráfica corresponde a la función p, la cual determina la presión “p(x)” en pascales, registrada en el interior de un tanque donde ocurre una reacción química, en función del tiempo “x” en minutos, desde el inicio de la reacción, con 1 ≤ x ≤ 4:`,fig:'33',ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función involucrada en el modelo matemático que se adapta mejor para representar a p?`,options:['Función lineal','Función logarítmica','Función exponencial']},
{lead:`La siguiente tabla muestra la función r, que determina la cantidad diaria “r(t)” en kilogramos, de fruta cosechada por una finca agroecológica, en función del tiempo “t” en días, desde el inicio de la temporada de cosecha, con 1 ≤ t ≤ 6:`,pre:tableHTML([['t','1','2','3','4','5','6'],['r(t)','38','52','72','98','130','168']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar a r?`,options:['Función lineal','Función cuadrática','Función logarítmica']},
{lead:`La siguiente tabla muestra la función d, que determina la cantidad semanal “d(t)” de hojas nuevas que crecen en una planta, en función del tiempo “t” en semanas, desde el inicio de un estudio, con 0 ≤ t ≤ 5:`,pre:tableHTML([['t','0','1','2','3','4','5'],['d(t)','5','10','15','20','25','30']]),ask:`De acuerdo con la información anterior, ¿cuál opción corresponde al tipo de función que se adapta mejor para modelar a d?`,options:['Función lineal','Función cuadrática','Función exponencial']},
{lead:`La cantidad de minutos dedicados al estudio individual por cada una de al menos 120 personas estudiantes, al finalizar la semana, fue mayor o igual que`,options:['40','70','120']},
{lead:`Con certeza, ¿cuál opción corresponde a una cantidad de minutos que ninguna de las 160 personas estudiantes dedicó al estudio individual al finalizar la semana?`,options:['55','110','200']},
{lead:`La siguiente tabla muestra el porcentaje de cada uno de los tres componentes que se consideraron al calificar el desempeño académico de las personas estudiantes en un curso. Asimismo, se muestra la calificación obtenida por componente, en una escala de 1 a 100, del desempeño académico de Matías:`,pre:tableHTML([['Componente','Porcentaje','Calificación del desempeño<br>académico de Matías'],['Exámenes','50 %','82'],['Proyectos','30 %','90'],['Participación','20 %','75']],true),ask:`Además, la nota final de ese curso corresponde a la media aritmética ponderada de los tres componentes calificados.<br><br>De acuerdo con la información anterior, ¿cuál es la nota final de Matías en el curso?`,options:['81,50','82,33','83,00']},
{lead:`La siguiente representación gráfica muestra la distribución de los datos correspondientes al tiempo en minutos, que las personas tardaron para ser atendidas en una ventanilla de servicio al cliente durante una mañana. Además, se muestra el promedio de los datos:`,fig:'39',ask:`De acuerdo con la información anterior, la mediana de los tiempos es`,options:['mayor que 18 min.','menor que 18 min.','igual que 18 min.']},
{lead:`La siguiente tabla muestra la distribución de frecuencias correspondientes al tiempo en minutos, que dedicaron a redes sociales un grupo de personas, durante un día:`,pre:tableHTML([['Cantidad de minutos','Cantidad de personas'],['De 0 a menos de 50','8'],['De 50 a menos de 100','22'],['De 100 a 150','10'],['Total','40']],true),ask:`De acuerdo con la información anterior, ¿cuál es el promedio de la cantidad de minutos que dedicaron a redes sociales esas personas?`,options:['13,3','77,5','102,5']}
];
const SHARED={
13:{lead:`Para responder los ítems 13, 14 y 15, considere la siguiente información:`,pre:`La siguiente representación gráfica corresponde a la función t, que determina la temperatura “t(x)” en grados Celsius, registrada en el interior de un invernadero automatizado, en función del tiempo “x” en días, desde el inicio de un monitoreo, con 0 ≤ x ≤ 60:`,fig:'13'},
36:{lead:`Para responder los ítems 36 y 37, considere la siguiente información:`,pre:`La siguiente tabla muestra algunas medidas de posición referentes a la cantidad de minutos que cada una de 160 personas estudiantes dedicó al estudio individual al finalizar una semana, como parte de un programa de acompañamiento académico:${tableHTML([['Medida de posición','Valor'],['Moda','50'],['Media Aritmética','75'],['Mediana','70'],['Primer Cuartil','40'],['Tercer Cuartil','120'],['Mínimo','15'],['Máximo','180']],true)}`}
};
if(QUESTIONS.length!==40||QUESTIONS.some(q=>q.options.length!==3))throw Error('Transcripción incompleta.');
